'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {BellRing,CalendarDays,Check,Globe2,LayoutGrid,List,MapPin,Palette,PanelTop,Phone,Shapes,UserRound} from 'lucide-react';
import {usePreferences} from '@/components/platform/preferences';

type Template='grid'|'list'|'gallery';
export default function BrandThemeManager({slug}:{slug:string}){
 const {locale}=usePreferences(); const ar=locale==='ar',fr=locale==='fr';
 const L=(a:string,e:string,f=e)=>ar?a:fr?f:e;
 const [tab,setTab]=useState<'templates'|'themes'|'identity'|'actions'|'pages'|'contact'>('templates');
 const [template,setTemplate]=useState<Template>('grid');
 const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/restaurant/appearance?slug='+encodeURIComponent(slug)).then(r=>r.json()).then(v=>{const t=v?.draft?.template||v?.published?.template;if(t==='grid'||t==='list'||t==='gallery')setTemplate(t)}).catch(()=>{})},[slug]);
 const select=(v:Template)=>setTemplate(v);
 async function persist(action:'save'|'publish'){setSaving(true);setMessage('');try{const response=await fetch('/api/restaurant/appearance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,action,settings:{template}})});if(!response.ok)throw new Error();setMessage(action==='publish'?L('تم نشر القالب','Template published','Modèle publié'):L('تم حفظ المسودة','Draft saved','Brouillon enregistré'))}catch{setMessage(L('تعذر الحفظ','Could not save','Enregistrement impossible'))}finally{setSaving(false)}}
 const templates:[Template,string,string,typeof LayoutGrid][]=[
  ['grid',L('شبكة','Grid','Grille'),L('بطاقات متوازنة وسريعة للتسوق.','Balanced cards for fast shopping.','Cartes équilibrées pour commander rapidement.'),LayoutGrid],
  ['list',L('قائمة','List','Liste'),L('عرض أفقي واضح للأصناف والتفاصيل.','Clear horizontal item layout.','Présentation horizontale claire.'),List],
  ['gallery',L('صور','Gallery','Galerie'),L('صور أكبر وتجربة بصرية للأصناف.','Image-led menu experience.','Expérience visuelle centrée sur les images.'),PanelTop]
 ];
 return <div className="restaurant-brand-page">
  <header className="restaurant-v2-page-heading"><div><span className="restaurant-v2-eyebrow">{L('المظهر العام','Appearance','Apparence')}</span><h1>{L('المظهر والواجهة','Appearance & interface','Apparence et interface')}</h1><p>{L('تحكم بقالب المنيو والسمات وهوية المطعم من مكان واحد.','Manage menu templates, themes and restaurant identity in one place.','Gérez les modèles, thèmes et identité du restaurant.')}</p></div><Link className="primary-button" href={'/menu/'+encodeURIComponent(slug)+'?template='+template} target="_blank">{L('معاينة المنيو','Preview menu','Aperçu du menu')}</Link></header>
  <div className="restaurant-brand-publish"><button type="button" disabled={saving} onClick={()=>persist('save')}>{L('حفظ مسودة','Save draft','Enregistrer')}</button><button type="button" disabled={saving} onClick={()=>persist('publish')}>{L('نشر التغييرات','Publish changes','Publier')}</button>{message&&<span role="status">{message}</span>}</div>
  <nav className="restaurant-brand-tabs">{([['templates',L('القوالب','Templates','Modèles'),Shapes],['themes',L('الهوية والسمات','Brand & themes','Identité et thèmes'),Palette],['actions',L('عناصر المنيو','Menu elements','Éléments du menu'),BellRing],['pages',L('الهيدر والفوتر والصفحات','Header, footer & pages','En-tête, pied et pages'),LayoutGrid],['contact',L('بيانات التواصل','Contact details','Coordonnées'),MapPin]] as const).map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon/>{label}</button>)}</nav>
  {tab==='templates'&&<section className="restaurant-template-grid">{templates.map(([id,title,desc,Icon])=><article key={id} className={template===id?'selected':''}><div className={'restaurant-template-preview '+id}><Icon/></div><div><h2>{title}</h2><p>{desc}</p></div><button type="button" onClick={()=>select(id)}>{template===id?<><Check/>{L('محدد','Selected','Sélectionné')}</>:L('اختيار القالب','Select template','Choisir')}</button></article>)}</section>}
  {tab==='themes'&&<section className="restaurant-v2-card restaurant-brand-settings"><h2>{L('السمات','Themes','Thèmes')}</h2><p>{L('ألوان المنيو والخلفية والخطوط والحواف والوضع الليلي ستدار من هنا.','Menu colors, backgrounds, fonts, radius and dark mode are managed here.','Couleurs, arrière-plans, polices, rayons et mode sombre.')}</p><div className="brand-setting-grid"><label>{L('اللون الرئيسي','Primary color','Couleur principale')}<input type="color" defaultValue="#f28c28"/></label><label>{L('لون الخلفية','Background','Arrière-plan')}<input type="color" defaultValue="#ffffff"/></label><label>{L('شكل الحواف','Corner style','Coins')}<select defaultValue="rounded"><option value="rounded">{L('دائري','Rounded','Arrondis')}</option><option value="soft">{L('ناعم','Soft','Doux')}</option><option value="square">{L('مربع','Square','Carrés')}</option></select></label></div></section>}
  {tab==='actions'&&<section className="restaurant-v2-card restaurant-brand-settings"><h2>{L('أزرار المنيو ومواضعها','Menu actions & positions','Actions du menu et positions')}</h2><p>{L('تحكم بظهور وترتيب الأدوات العامة للعميل.','Control visibility and placement of public menu actions.','Contrôlez la visibilité et la position des actions.')}</p><div className="brand-action-list">{[[BellRing,L('نداء النادل','Call waiter','Appeler le serveur')],[CalendarDays,L('الحجز','Reservation','Réservation')],[Globe2,L('اللغة','Language','Langue')],[Palette,L('الوضع الليلي','Dark mode','Mode sombre')],[UserRound,L('حسابي','My account','Mon compte')]].map(([Icon,label],i)=><div key={String(label)}><span><Icon/><b>{String(label)}</b></span><label>{L('إظهار','Show','Afficher')} <input type="checkbox" defaultChecked/></label><select defaultValue={i<2?'cover':'menu'}><option value="cover">{L('تحت الغلاف','Below cover','Sous la couverture')}</option><option value="menu">{L('القائمة العلوية','Top menu','Menu supérieur')}</option><option value="bottom">{L('الشريط السفلي','Bottom bar','Barre inférieure')}</option></select></div>)}</div></section>}
  {tab==='pages'&&<section className="restaurant-v2-card restaurant-brand-settings"><h2>{L('الصفحات والهيدر والفوتر','Pages, header & footer','Pages, en-tête et pied')}</h2><p>{L('إدارة روابط المطعم والصفحات العامة وترتيب ظهورها في أعلى وأسفل المنيو.','Manage restaurant public pages and links shown in the menu header and footer.','Gérez les pages publiques et les liens de navigation.')}</p><div className="brand-setting-grid"><label>{L('الهيدر','Header','En-tête')}<select defaultValue="compact"><option value="compact">{L('مختصر','Compact','Compact')}</option><option value="full">{L('كامل','Full','Complet')}</option></select></label><label>{L('الفوتر','Footer','Pied de page')}<select defaultValue="full"><option value="full">{L('كامل','Full','Complet')}</option><option value="compact">{L('مختصر','Compact','Compact')}</option></select></label><label>{L('الصفحات العامة','Public pages','Pages publiques')}<button type="button">{L('إدارة الصفحات','Manage pages','Gérer les pages')}</button></label></div></section>}
  {tab==='contact'&&<section className="restaurant-v2-card restaurant-brand-settings"><h2>{L('التواصل والموقع','Contact & location','Contact et localisation')}</h2><p>{L('بيانات التواصل التي تظهر للعميل في المنيو وصفحات المطعم.','Contact information shown on the public menu and restaurant pages.','Coordonnées affichées sur le menu public.')}</p><div className="brand-setting-grid"><label><Phone/>{L('الهاتف','Phone','Téléphone')}<input inputMode="tel" placeholder="+966"/></label><label>{L('البريد الإلكتروني','Email','E-mail')}<input type="email" placeholder="name@example.com"/></label><label>{L('WhatsApp','WhatsApp','WhatsApp')}<input inputMode="tel" placeholder="+966"/></label><label>{L('الموقع','Location','Localisation')}<input placeholder={L('رابط أو إحداثيات الموقع','Map link or coordinates','Lien ou coordonnées')}/></label><label>Instagram<input placeholder="@restaurant"/></label><label>TikTok<input placeholder="@restaurant"/></label><label>Snapchat<input placeholder="@restaurant"/></label><label>{L('الموقع الإلكتروني','Website','Site web')}<input type="url" placeholder="https://"/></label></div></section>}
  {tab==='identity'&&<section className="restaurant-v2-card restaurant-brand-settings"><h2>{L('هوية المطعم','Restaurant identity','Identité du restaurant')}</h2><p>{L('الشعار والغلاف واسم العلامة ومظهر المنيو العام.','Logo, cover, brand name and public menu appearance.','Logo, couverture, marque et apparence publique.')}</p><div className="brand-setting-grid"><label>{L('الشعار','Logo','Logo')}<input type="file" accept="image/*"/></label><label>{L('صورة الغلاف','Cover image','Image de couverture')}<input type="file" accept="image/*"/></label></div></section>}
 </div>
}