'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';
type Station={id:string;name:string;station_key:string;enabled:number};type Printer={id:string;name:string;station:string;connection_type:string;enabled:number};
export default function OperationsSettings({slug,stations,printers}:{slug:string;stations:Station[];printers:Printer[]}){const router=useRouter(),[mode,setMode]=useState<'station'|'printer'|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const fd=new FormData(e.currentTarget);const body=mode==='station'?{action:'create_station',slug,name:fd.get('name'),stationKey:fd.get('stationKey')}:{action:'create_printer',slug,name:fd.get('name'),station:fd.get('station')||'kitchen',connectionType:fd.get('connectionType')||'network',connectionValue:fd.get('connectionValue')};try{const r=await fetch('/api/restaurant/operations-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'SAVE_FAILED');setMode(null);setMsg('تم الحفظ');router.refresh()}catch(e){setMsg(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}}
return <article className="restaurant-v2-card"><header><div><small>التشغيل</small><h2>المطبخ والطابعات</h2></div><div><button type="button" onClick={()=>setMode('station')}>+ محطة</button> <button type="button" onClick={()=>setMode('printer')}>+ طابعة</button></div></header>
<div className="restaurant-v2-status"><div><b>{stations.length}</b><small>محطات KDS</small></div><div><b>{printers.length}</b><small>الطابعات</small></div><div><b>{printers.filter(x=>x.enabled).length}</b><small>طابعات مفعلة</small></div></div>
{mode&&<form onSubmit={submit} className="subscription-form"><label>الاسم<input name="name" required maxLength={120}/></label>{mode==='station'?<label>رمز المحطة<input name="stationKey" required pattern="[a-z0-9_-]{2,60}" placeholder="kitchen"/></label>:<><label>المحطة<select name="station" defaultValue="kitchen"><option value="kitchen">المطبخ</option>{stations.filter(x=>x.station_key!=='kitchen').map(x=><option key={x.id} value={x.station_key}>{x.name}</option>)}</select></label><label>نوع الاتصال<select name="connectionType" defaultValue="network"><option value="network">Network</option><option value="usb">USB</option><option value="bluetooth">Bluetooth</option><option value="system">System</option></select></label><label>عنوان/معرف الاتصال<input name="connectionValue" maxLength={500} placeholder="192.168.1.50:9100"/></label></>}<div><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ'}</button> <button type="button" className="quiet-button" onClick={()=>setMode(null)}>إلغاء</button></div></form>}
{stations.length?<div className="restaurant-v2-orders">{stations.map(x=><div key={x.id}><span><b>{x.name}</b><small>{x.station_key}</small></span><strong>{x.enabled?'مفعل':'متوقف'}</strong></div>)}</div>:<div className="restaurant-v2-empty">لا توجد محطات مخصصة؛ الأصناف غير الموجهة تذهب إلى kitchen تلقائيًا.</div>}
{printers.length?<div className="restaurant-v2-orders">{printers.map(x=><div key={x.id}><span><b>{x.name}</b><small>{x.station} · {x.connection_type}</small></span><strong>{x.enabled?'مفعل':'متوقف'}</strong></div>)}</div>:null}<p role="status">{msg}</p></article>}