'use client';

import {useEffect,useMemo,useState} from 'react';
import {ClipboardList,RefreshCw} from 'lucide-react';
import {usePreferences} from '@/components/platform/preferences';

type Order={id:string;reference:string;source:string;status:string;order_type?:string|null;service_reference?:string|null;room_number?:string|null;pickup_label?:string|null;customer_name?:string|null;customer_phone?:string|null;customer_email?:string|null;notes?:string|null;total:number|string;currency:string;created_at:number};
type Item={id:string;order_id:string;item_name:string;quantity:number;unit_price:number|string;line_total:number|string};
type OrdersResponse={orders?:Order[];items?:Item[];error?:string};
const states=['new','pending','confirmed','preparing','ready','completed','delivered','cancelled'] as const;

export default function RestaurantOrders({slug}:{slug:string}){
 const {locale}=usePreferences(),ar=locale==='ar';
 const L=(a:string,e:string,f:string)=>ar?a:locale==='fr'?f:e;
 const [orders,setOrders]=useState<Order[]>([]),[items,setItems]=useState<Item[]>([]),[filter,setFilter]=useState(''),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 const url='/api/restaurant/orders?slug='+encodeURIComponent(slug)+(filter?'&status='+filter:'');
 const load=async()=>{try{const r=await fetch(url,{cache:'no-store'}),j=await r.json() as OrdersResponse;if(!r.ok)throw new Error(j.error);setOrders(j.orders||[]);setItems(j.items||[]);setMsg('')}catch(e){setMsg(e instanceof Error?e.message:'ERROR')}};
 useEffect(()=>{let active=true;const sync=async()=>{try{const r=await fetch(url,{cache:'no-store'}),j=await r.json() as OrdersResponse;if(!r.ok)throw new Error(j.error);if(active){setOrders(j.orders||[]);setItems(j.items||[]);setMsg('')}}catch(e){if(active)setMsg(e instanceof Error?e.message:'ERROR')}};void sync();return()=>{active=false}},[url]);
 const grouped=useMemo(()=>Object.groupBy(items,item=>item.order_id),[items]);
 async function change(id:string,status:string){setBusy(id);const r=await fetch('/api/restaurant/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,id,status})}),j=await r.json() as {error?:string};setBusy('');if(!r.ok){setMsg(j.error||'ERROR');return}await load()}
 function orderTypeLabel(type:string|null|undefined){return type==='dine_in'?L('داخل المطعم','Dine in','Sur place'):type==='room_service'?L('خدمة الغرف','Room service','Service en chambre'):L('استلام','Pickup','À emporter')}

 return <main className="restaurant-workspace-shell"><section className="restaurant-ops"><div className="restaurant-ops-head"><div><span className="restaurant-ops-kicker"><ClipboardList/>{L('الطلبات المباشرة','Live orders','Commandes en direct')}</span><h1>{L('الطلبات','Orders','Commandes')}</h1><p>{L('متابعة الطلبات الحقيقية وتحديث حالتها.','Track real orders and update their status.','Suivez les commandes réelles et leur statut.')}</p></div><button className="primary-button" onClick={load}><RefreshCw/> {L('تحديث','Refresh','Actualiser')}</button></div><div className="restaurant-orders-toolbar"><label>{L('الحالة','Status','Statut')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{L('الكل','All','Toutes')}</option>{states.map(s=><option key={s} value={s}>{s}</option>)}</select></label><strong>{orders.length} {L('طلب','orders','commandes')}</strong></div>
 {orders.length?<div className="restaurant-live-orders">{orders.map(order=><article className="records-card" key={order.id}><div className="restaurant-card-head"><div><strong>{order.reference}</strong><small>{order.source} · {new Date(order.created_at).toLocaleString(ar?'ar-SA':locale==='fr'?'fr-FR':'en-US')}</small></div><b>{new Intl.NumberFormat('en-US',{style:'currency',currency:order.currency}).format(Number(order.total))}</b></div><div className="restaurant-order-customer"><span>{order.customer_name||L('بدون اسم','No name','Sans nom')}</span>{order.customer_phone&&<span dir="ltr">{order.customer_phone}</span>}{order.customer_email&&<a href={'mailto:'+order.customer_email}>{order.customer_email}</a>}</div>{(order.order_type||order.service_reference||order.room_number||order.pickup_label)&&<p className="restaurant-order-context">{orderTypeLabel(order.order_type)}{order.service_reference?' · '+order.service_reference:''}{order.room_number?' · '+L('غرفة','Room','Chambre')+' '+order.room_number:''}{order.pickup_label?' · '+order.pickup_label:''}</p>}{order.notes&&<p className="restaurant-order-context">{L('ملاحظة','Note','Note')}: {order.notes}</p>}<div className="restaurant-order-lines">{(grouped[order.id]||[]).map(item=><div key={item.id}><span>{item.quantity} × {item.item_name}</span><b>{Number(item.line_total).toFixed(2)}</b></div>)}</div><label>{L('حالة الطلب','Order status','Statut')}<select disabled={busy===order.id} value={order.status} onChange={e=>change(order.id,e.target.value)}>{states.map(s=><option key={s} value={s}>{s}</option>)}</select></label></article>)}</div>:<div className="records-card"><p>{L('لا توجد طلبات مطابقة.','No matching orders.','Aucune commande correspondante.')}</p></div>}<p role="status">{msg}</p></section></main>;
}
