'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {usePreferences} from '@/components/platform/preferences';
type Row={id:string;name?:string;code?:string;discount_type:string;discount_value:number|string;min_order?:number|string;usage_limit?:number|null;used_count?:number;starts_at:number|null;ends_at:number|null;enabled:number|string};
type Data={promotions:Row[];coupons:Row[]};
export default function PromoManager({slug}:{slug:string}){
 const {locale}=usePreferences(),ar=locale==='ar',L=(a:string,e:string,f=e)=>ar?a:locale==='fr'?f:e;
 const [data,setData]=useState<Data>({promotions:[],coupons:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[name,setName]=useState(''),[discountType,setDiscountType]=useState('percent'),[discountValue,setDiscountValue]=useState(''),[code,setCode]=useState(''),[minOrder,setMinOrder]=useState('0'),[usageLimit,setUsageLimit]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/restaurant/promo?slug='+encodeURIComponent(slug),{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setData({promotions:j.promotions||[],coupons:j.coupons||[]})}catch{setError(L('تعذر تحميل العروض. أعد المحاولة.','Could not load promotions. Try again.','Impossible de charger les promotions. Réessayez.'))}finally{setLoading(false)}},[slug,locale]);
 useEffect(()=>{void load()},[load]);
 async function create(e:FormEvent,action:'create_promotion'|'create_coupon'){e.preventDefault();setBusy(true);setError('');setMsg('');try{const body=action==='create_promotion'?{slug,action,name,discountType,discountValue:Number(discountValue)}:{slug,action,code,discountType,discountValue:Number(discountValue),minOrder:Number(minOrder),usageLimit:usageLimit?Number(usageLimit):null};const r=await fetch('/api/restaurant/promo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error);setName('');setCode('');setDiscountValue('');setUsageLimit('');setMsg(L('تم الحفظ بنجاح.','Saved successfully.','Enregistré.'));await load()}catch(e){const code=e instanceof Error?e.message:'';setError(code==='COUPON_EXISTS'?L('رمز القسيمة مستخدم مسبقًا.','This coupon code already exists.','Ce code promo existe déjà.'):L('تعذر الحفظ. راجع البيانات وحاول مرة أخرى.','Could not save. Check the details and retry.','Échec de l’enregistrement. Vérifiez les données.'))}finally{setBusy(false)}}
 async function toggle(row:Row,kind:'promotion'|'coupon'){setBusy(true);setError('');try{const r=await fetch('/api/restaurant/promo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,action:'set_enabled',id:row.id,kind,enabled:!Boolean(Number(row.enabled))})}),j=await r.json();if(!r.ok)throw new Error(j.error);await load()}catch{setError(L('تعذر تغيير الحالة.','Could not change status.','Impossible de changer le statut.'))}finally{setBusy(false)}}
 const fieldStyle={width:'100%',minWidth:0,padding:'10px 12px',border:'1px solid var(--border)',borderRadius:10,background:'var(--card)',color:'inherit'};
 function form(title:string,action:'create_promotion'|'create_coupon'){return <form className="promo-form" onSubmit={e=>void create(e,action)}><h3>{title}</h3>{action==='create_promotion'?<label>{L('اسم العرض','Promotion name','Nom de l’offre')}<input style={fieldStyle} required minLength={2} maxLength={180} value={name} onChange={e=>setName(e.target.value)}/></label>:<><label>{L('رمز القسيمة','Coupon code','Code promo')}<input style={fieldStyle} required minLength={3} maxLength={80} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>{L('أقل قيمة للطلب','Minimum order','Commande minimum')}<input style={fieldStyle} type="number" min="0" step=".01" value={minOrder} onChange={e=>setMinOrder(e.target.value)}/></label><label>{L('حد الاستخدام (اختياري)','Usage limit (optional)','Limite (facultatif)')}<input style={fieldStyle} type="number" min="1" value={usageLimit} onChange={e=>setUsageLimit(e.target.value)}/></label></>}<label>{L('نوع الخصم','Discount type','Type de remise')}<select style={fieldStyle} value={discountType} onChange={e=>setDiscountType(e.target.value)}><option value="percent">{L('نسبة مئوية','Percentage','Pourcentage')}</option><option value="fixed">{L('مبلغ ثابت','Fixed amount','Montant fixe')}</option></select></label><label>{L('قيمة الخصم','Discount value','Valeur')}<input style={fieldStyle} required type="number" min=".01" max={discountType==='percent'?100:100000} step=".01" value={discountValue} onChange={e=>setDiscountValue(e.target.value)}/></label><button className="primary-button" disabled={busy}>{busy?L('جارٍ الحفظ…','Saving…','Enregistrement…'):L('حفظ','Save','Enregistrer')}</button></form>}
 function list(title:string,rows:Row[],kind:'promotion'|'coupon'){return <section className="restaurant-v2-card"><header><div><small>FOON</small><h2>{title} <span>({rows.length})</span></h2></div></header>{rows.length?<div className="restaurant-v2-orders">{rows.map(row=><div key={row.id}><span><b>{row.name||row.code}</b><small>{Number(row.discount_value)}{row.discount_type==='percent'?'%':' SAR'}{row.min_order!=null?' · '+L('الحد الأدنى','Min order','Min')+' '+row.min_order:''}{row.usage_limit!=null?' · '+row.used_count+'/'+row.usage_limit:''}</small></span><button type="button" className={Number(row.enabled)?'secondary-button':'primary-button'} disabled={busy} onClick={()=>void toggle(row,kind)}>{Number(row.enabled)?L('مفعّل','Active','Actif'):L('متوقف','Paused','En pause')}</button></div>)}</div>:<p className="restaurant-v2-empty">{L('لا توجد سجلات بعد. أنشئ أول عنصر من النموذج.','No records yet. Create the first one using the form.','Aucun élément. Créez le premier avec le formulaire.')}</p>}</section>}
 return <div className="restaurant-v2-workspace"><section className="restaurant-v2-page-heading"><div><span className="restaurant-v2-eyebrow">{L('إدارة النمو','Growth tools','Outils de croissance')}</span><h1>{L('العروض والترويج','Promotions','Promotions')}</h1><p>{L('أنشئ خصومات وقسائم، وأوقفها أو فعّلها حسب الحاجة.','Create discounts and coupons, then activate or pause them.','Créez des remises et coupons, puis activez-les ou mettez-les en pause.')}</p></div></section>{error&&<p role="alert">{error}</p>}{msg&&<p role="status">{msg}</p>}<div className="promo-forms">{form(L('عرض جديد','New promotion','Nouvelle offre'),'create_promotion')}{form(L('قسيمة جديدة','New coupon','Nouveau coupon'),'create_coupon')}</div>{loading?<p>{L('جارٍ التحميل…','Loading…','Chargement…')}</p>:<div className="promo-lists">{list(L('العروض','Promotions','Promotions'),data.promotions,'promotion')}{list(L('القسائم','Coupons','Coupons'),data.coupons,'coupon')}</div>}</div>
}