'use client';
import {useEffect,useState} from 'react';import {CalendarDays,RefreshCw,Users} from 'lucide-react';import {usePreferences} from '@/components/platform/preferences';
type R={id:string;reference:string;status:string;customer_name:string;customer_email?:string|null;customer_phone?:string|null;guests:number;reservation_at:number;notes?:string|null;table_id?:string|null;table_number?:string|null;section_name?:string|null};type W={id:string;reference:string;display_number:string;status:string;customer_name:string;customer_phone:string;guests:number;notes?:string|null;table_id?:string|null;table_number?:string|null;expires_at:number;created_at:number};type T={id:string;table_number:string;capacity:number;section_name:string;runtime_status:string};const states=['pending','confirmed','seated','completed','cancelled','no_show'] as const;
export default function ReservationsManager({slug}:{slug:string}){const {locale}=usePreferences(),ar=locale==='ar',L=(a:string,e:string,f:string)=>ar?a:locale==='fr'?f:e;const [rows,setRows]=useState<R[]>([]),[wait,setWait]=useState<W[]>([]),[tables,setTables]=useState<T[]>([]),[filter,setFilter]=useState(''),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
async function load(){setMsg('');try{const [rr,wr]=await Promise.all([fetch('/api/restaurant/reservations?slug='+encodeURIComponent(slug)+(filter?'&status='+filter:''),{cache:'no-store'}),fetch('/api/restaurant/waitlist?slug='+encodeURIComponent(slug),{cache:'no-store'})]),[rj,wj]=await Promise.all([rr.json(),wr.json()]);if(!rr.ok)throw new Error(rj.error);if(!wr.ok)throw new Error(wj.error);setRows(rj.reservations||[]);setTables(rj.tables||[]);setWait(wj.waitlist||[])}catch(e){setMsg(e instanceof Error?e.message:'ERROR')}}
useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer)},[slug,filter]);
async function change(id:string,status:string,tableId?:string|null){setBusy(id);const r=await fetch('/api/restaurant/reservations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,id,status,tableId:tableId||null})}),j=await r.json();setBusy('');if(!r.ok){setMsg(j.error||'ERROR');return}await load()}
async function changeWait(id:string,status:string,tableId?:string|null){setBusy(id);const r=await fetch('/api/restaurant/waitlist',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,id,status,tableId:tableId||null})}),j=await r.json();setBusy('');if(!r.ok){setMsg(j.error||'ERROR');return}await load()}
const tableOptions=(guests:number)=>tables.filter(t=>Number(t.capacity)>=Number(guests));
return <main className="restaurant-workspace-shell"><section className="restaurant-ops"><div className="restaurant-ops-head"><div><span className="restaurant-ops-kicker"><CalendarDays/>{L('الحجز والانتظار','Reservations & waitlist','Réservations et attente')}</span><h1>{L('إدارة الحجز والطاولات','Reservations and seating','Réservations et placement')}</h1><p>{L('الحجز المسبق حتى 7 أيام والانتظار الفوري مع ربط الطاولة ومنع التعارض.','Advance booking and live waitlist with table conflict protection.','Réservation et liste d’attente avec protection des conflits.')}</p></div><button className="primary-button" onClick={()=>void load()}><RefreshCw/>{L('تحديث','Refresh','Actualiser')}</button></div>
<div className="restaurant-orders-toolbar"><label>{L('حالة الحجز','Reservation status','Statut')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{L('الكل','All','Toutes')}</option>{states.map(s=><option key={s}>{s}</option>)}</select></label><strong>{rows.length} {L('حجز','reservations','réservations')}</strong></div>
{rows.length?<div className="restaurant-live-orders">{rows.map(x=><article className="records-card" key={x.id}><div className="restaurant-card-head"><div><strong>{x.reference}</strong><small>{new Date(Number(x.reservation_at)).toLocaleString(ar?'ar-SA-u-nu-latn':locale==='fr'?'fr-FR':'en-US')}</small></div><b>{x.guests} {L('ضيف','guests','personnes')}</b></div><div className="restaurant-order-customer"><strong>{x.customer_name}</strong>{x.customer_phone&&<span dir="ltr">{x.customer_phone}</span>}</div><div className="restaurant-order-lines"><div><span>{L('الطاولة','Table','Table')}</span><b>{x.table_number||'—'}</b></div><div><span>{L('القسم','Section','Section')}</span><b>{x.section_name||'—'}</b></div></div><label>{L('تعيين الطاولة','Assign table','Affecter une table')}<select disabled={busy===x.id} value={x.table_id||''} onChange={e=>void change(x.id,x.status,e.target.value)}><option value="">—</option>{tableOptions(x.guests).map(t=><option key={t.id} value={t.id}>{t.section_name} · {t.table_number} · {t.capacity}</option>)}</select></label><label>{L('حالة الحجز','Reservation status','Statut')}<select disabled={busy===x.id} value={x.status} onChange={e=>void change(x.id,e.target.value,x.table_id)}>{states.map(s=><option key={s}>{s}</option>)}</select></label></article>)}</div>:<div className="records-card"><p>{L('لا توجد حجوزات مطابقة.','No matching reservations.','Aucune réservation.')}</p></div>}
<div className="restaurant-ops-head"><div><span className="restaurant-ops-kicker"><Users/>{L('قائمة الانتظار','Waitlist','Liste d’attente')}</span><h2>{wait.filter(x=>x.status==='waiting'||x.status==='accepted').length} {L('بانتظار الخدمة','waiting','en attente')}</h2></div></div>
{wait.length?<div className="restaurant-live-orders">{wait.map(x=><article className="records-card" key={x.id}><div className="restaurant-card-head"><div><strong>#{x.display_number}</strong><small>{x.reference} · {new Date(Number(x.created_at)).toLocaleTimeString(ar?'ar-SA-u-nu-latn':'en-US')}</small></div><b>{x.guests} {L('ضيف','guests','personnes')}</b></div><div className="restaurant-order-customer"><strong>{x.customer_name}</strong><span dir="ltr">{x.customer_phone}</span></div><label>{L('الطاولة','Table','Table')}<select disabled={busy===x.id} value={x.table_id||''} onChange={e=>void changeWait(x.id,x.status,e.target.value)}><option value="">—</option>{tableOptions(x.guests).map(t=><option key={t.id} value={t.id}>{t.section_name} · {t.table_number} · {t.capacity}</option>)}</select></label><div className="restaurant-order-actions"><button disabled={busy===x.id||x.status!=='waiting'} onClick={()=>void changeWait(x.id,'accepted',x.table_id)}>{L('قبول','Accept','Accepter')}</button><button disabled={busy===x.id||!x.table_id} onClick={()=>void changeWait(x.id,'seated',x.table_id)}>{L('إجلاس','Seat','Installer')}</button><button disabled={busy===x.id} onClick={()=>void changeWait(x.id,'cancelled',x.table_id)}>{L('إلغاء','Cancel','Annuler')}</button></div><small>{L('ينتهي','Expires','Expire')}: {new Date(Number(x.expires_at)).toLocaleTimeString(ar?'ar-SA-u-nu-latn':'en-US')}</small></article>)}</div>:<div className="records-card"><p>{L('لا توجد قائمة انتظار.','No waitlist entries.','Aucune attente.')}</p></div>}<p role="status">{msg}</p></section></main>}