'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {BarChart3,BookOpen,CalendarDays,ChevronLeft,ClipboardList,ContactRound,CreditCard,LayoutDashboard,Menu,MessageSquare,PackageOpen,Settings2,Share2,ShoppingCart,Star,UsersRound,Warehouse,X} from 'lucide-react';
import {usePreferences} from '@/components/platform/preferences';
type Props={slug:string;name:string;children:React.ReactNode};
type Item={key:string;ar:string;en:string;icon:any;ready?:boolean};
const groups:{ar:string;en:string;items:Item[]}[]=[
 {ar:'عام',en:'General',items:[{key:'overview',ar:'لوحة التحكم',en:'Dashboard',icon:LayoutDashboard,ready:true},{key:'subscription',ar:'الاشتراكات',en:'Subscriptions',icon:PackageOpen}]},
 {ar:'الطلبات',en:'Order',items:[{key:'orders',ar:'الطلبات المباشرة',en:'Live order',icon:ClipboardList,ready:true},{key:'reservations',ar:'الحجوزات',en:'Reservation',icon:CalendarDays,ready:true},{key:'kds',ar:'KDS',en:'KDS',icon:ClipboardList},{key:'pos',ar:'نقاط البيع POS',en:'POS',icon:ShoppingCart},{key:'reports',ar:'التقارير',en:'Reports',icon:BarChart3}]},
 {ar:'المنيو',en:'Menu',items:[{key:'menu',ar:'المنيو',en:'Menu',icon:BookOpen,ready:true}]},
 {ar:'الإعدادات',en:'Settings',items:[{key:'restaurant-settings',ar:'تهيئة المتجر',en:'Shop Configuration',icon:Settings2},{key:'settings',ar:'الإعدادات',en:'Settings',icon:Settings2},{key:'whatsapp',ar:'إعداد WhatsApp',en:'WhatsApp Config',icon:MessageSquare}]},
 {ar:'أخرى',en:'Others',items:[{key:'pages',ar:'الصفحات',en:'Pages',icon:BookOpen},{key:'promo',ar:'العروض',en:'Promo',icon:Star},{key:'payment-history',ar:'سجل المدفوعات',en:'Payment History',icon:CreditCard},{key:'staff',ar:'الموظفون',en:'Staffs',icon:UsersRound},{key:'inventory',ar:'المخزون',en:'Inventory',icon:Warehouse},{key:'customers',ar:'قائمة العملاء',en:'Customer List',icon:ContactRound},{key:'reviews',ar:'التقييمات',en:'Reviews',icon:Star},{key:'features',ar:'إدارة الخصائص',en:'Manage Features',icon:Settings2},{key:'promotion',ar:'الترويج',en:'Promotion',icon:Share2},{key:'chat',ar:'المحادثات',en:'Chat',icon:MessageSquare}]}
];
export default function RestaurantShell({slug,name,children}:Props){const {locale}=usePreferences();const pathname=usePathname();const [open,setOpen]=useState(false);const base='/restaurant/'+encodeURIComponent(slug),rtl=locale==='ar';const L=(a:string,e:string,f:string)=>rtl?a:locale==='fr'?f:e;return <div className="restaurant-shell" dir={rtl?'rtl':'ltr'}><aside className={'restaurant-sidebar '+(open?'is-open':'')}><div className="restaurant-sidebar-brand"><div><strong>FOON.</strong><small>{name}</small></div><button onClick={()=>setOpen(false)} aria-label="Close"><X/></button></div><nav>{groups.map(g=><section className="restaurant-nav-group" key={g.en}><small>{rtl?g.ar:g.en}</small>{g.items.map(({key,ar,en,icon:Icon,ready})=>{const href=key==='overview'?base:base+'/'+key,active=key==='overview'?pathname===base:pathname.startsWith(href);return ready?<Link key={key} href={href} className={active?'active':''} onClick={()=>setOpen(false)}><Icon/><span>{rtl?ar:en}</span><ChevronLeft/></Link>:<span key={key} className="restaurant-nav-pending" title={L('قيد نقل الوظيفة من النظام المرجعي','Function migration in progress','Migration de la fonction en cours')}><Icon/><span>{rtl?ar:en}</span></span>})}</section>)}</nav><div className="restaurant-sidebar-foot"><Link href={'/menu/'+encodeURIComponent(slug)} target="_blank"><BookOpen/>{L('فتح منيو المطعم','Open restaurant menu','Ouvrir le menu')}</Link><span className="restaurant-nav-pending"><PackageOpen/>{L('الباقة والخصائص','Plan & features','Forfait et fonctionnalités')}</span></div></aside><div className="restaurant-main"><header className="restaurant-topbar"><button className="restaurant-mobile-menu" onClick={()=>setOpen(true)} aria-label="Menu"><Menu/></button><div><strong>{name}</strong><small>{L('إدارة وتشغيل المطعم','Restaurant operations','Gestion du restaurant')}</small></div><Link href={base}>{L('مركز التشغيل','Operations','Opérations')}</Link></header>{children}</div>{open&&<button className="restaurant-sidebar-backdrop" aria-label="Close" onClick={()=>setOpen(false)}/>}</div>}
