import Link from 'next/link';import {BookOpen,ClipboardList,Eye,LayoutDashboard,PackageOpen,Share2,ShoppingCart,Star,UtensilsCrossed} from 'lucide-react';
type Order={id:string;reference:string;source:string;status:string;customer_name?:string|null;total:number|string;currency:string;created_at:number};
type Sub={planId:string;status:string;nameAr:string;nameEn:string;startsAt:number|null;expiresAt:number|null;enabledFeatures:number;totalFeatures:number};
type Props={slug:string;name:string;status:string;currency:string;categoryCount:number;itemCount:number;orderCount:number;revenue:number;completedSales:number;orderStatuses:Record<string,number>;recentOrders:Order[];subscription:Sub|null};
export default function RestaurantDashboard(p:Props){const base='/restaurant/'+encodeURIComponent(p.slug),money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:p.currency||'SAR'}).format(n),status=(...keys:string[])=>keys.reduce((n,k)=>n+(p.orderStatuses[k]||0),0),pending=status('new','pending','confirmed','preparing'),completed=status('completed'),delivered=status('delivered'),cancelled=status('cancelled','canceled');return <div className="restaurant-ops restaurant-reference-dashboard">
 <div className="restaurant-ops-head"><div><span className="restaurant-ops-kicker"><LayoutDashboard size={16}/> لوحة المطعم</span><h1>{p.name}</h1><p>مركز إدارة وتشغيل المطعم.</p></div><Link className="primary-button" href={'/menu/'+encodeURIComponent(p.slug)} target="_blank"><Eye size={16}/> عرض المتجر</Link></div>
 <section className="restaurant-stat-grid restaurant-reference-stats"><article><span><UtensilsCrossed/></span><div><strong>{p.itemCount}</strong><small>إجمالي الأصناف</small></div></article><article><span><ShoppingCart/></span><div><strong>{p.orderCount}</strong><small>إجمالي الطلبات</small></div></article><article><span><Eye/></span><div><strong>—</strong><small>مشاهدات الملف</small></div></article><article><span><Share2/></span><div><strong>—</strong><small>المشاركات</small></div></article></section>
 <div className="restaurant-dashboard-grid"><section className="restaurant-dashboard-main"><div className="restaurant-profile-grid"><article className="records-card restaurant-profile-card"><h2>{p.name}</h2><small>{p.status}</small><div className="restaurant-profile-counts"><span><BookOpen/> المنيو <b>{p.itemCount}</b></span><span><PackageOpen/> الأقسام <b>{p.categoryCount}</b></span><span><Star/> الخصائص <b>{p.subscription?p.subscription.enabledFeatures:'—'}{p.subscription?' / '+p.subscription.totalFeatures:''}</b></span><span><ClipboardList/> الطلبات <b>{p.orderCount}</b></span></div></article><article className="records-card restaurant-plan-card"><h2>الاشتراك والباقة</h2>{p.subscription?<><strong>{p.subscription.nameAr||p.subscription.nameEn}</strong><span>{p.subscription.status}</span><span>{p.subscription.enabledFeatures} / {p.subscription.totalFeatures} خصائص</span>{p.subscription.expiresAt&&<small>ينتهي: {new Date(p.subscription.expiresAt).toLocaleDateString('ar-SA')}</small>}</>:<p>لا يوجد اشتراك مرتبط.</p>}</article></div>
 <article className="records-card"><h2>إجمالي المبيعات</h2><div className="restaurant-sales-summary"><div><strong>{money(p.revenue)}</strong><small>إجمالي المبيعات المكتملة</small></div><div><strong>{p.completedSales}</strong><small>عدد عمليات البيع المكتملة</small></div></div></article>
 <article className="records-card"><div className="restaurant-card-head"><h2>آخر الطلبات</h2><span>{p.recentOrders.length}</span></div>{p.recentOrders.length?<div className="review-list">{p.recentOrders.map(o=><div className="restaurant-record-row" key={o.id}><span><strong>{o.reference}</strong><small>{o.customer_name||o.source} · {o.status}</small></span><b>{money(Number(o.total))}</b></div>)}</div>:<p>لا توجد طلبات حديثة.</p>}</article></section>
 <aside className="restaurant-dashboard-side"><article className="records-card"><h2>حالة الطلبات</h2><div className="restaurant-order-status-grid"><div><b>{pending}</b><small>قيد التنفيذ</small></div><div><b>{completed}</b><small>مكتمل</small></div><div><b>{delivered}</b><small>تم التوصيل</small></div><div><b>{cancelled}</b><small>ملغي</small></div></div></article><article className="records-card"><h2>إجراءات سريعة</h2><div className="restaurant-quick-actions"><Link href={base+'/menu'}>إضافة صنف</Link><span aria-disabled="true">عرض الطلبات</span><span aria-disabled="true">الإعدادات</span><span aria-disabled="true">معلومات المطعم</span></div></article></aside></div>
 </div>}