'use client';
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';
type Branch={id:string;name:string;is_primary:number};type Table={id:string;branch_id:string;table_number:string;section_name:string;capacity:number;enabled:number;status:string;qr_token:string|null};
export default function TablesManager({slug,branches}:{slug:string;branches:Branch[]}){const router=useRouter(),[tables,setTables]=useState<Table[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
async function load(){try{const r=await fetch('/api/restaurant/tables?slug='+encodeURIComponent(slug),{cache:'no-store'}),j=await r.json();if(r.ok)setTables(j.tables||[])}catch{}}
useEffect(()=>{void load()},[slug]);
async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const fd=new FormData(e.currentTarget);try{const r=await fetch('/api/restaurant/tables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',slug,branchId:fd.get('branchId'),tableNumber:fd.get('tableNumber'),sectionName:fd.get('sectionName'),capacity:fd.get('capacity')})}),j=await r.json();if(!r.ok)throw new Error(j.error||'SAVE_FAILED');e.currentTarget.reset();setMsg('تمت إضافة الطاولة');await load();router.refresh()}catch(e){setMsg(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}}
async function status(id:string,next:string){setBusy(true);setMsg('');try{const r=await fetch('/api/restaurant/tables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',slug,id,status:next})}),j=await r.json();if(!r.ok)throw new Error(j.error||'SAVE_FAILED');await load()}catch(e){setMsg(e instanceof Error?e.message:'تعذر التحديث')}finally{setBusy(false)}}
return <article className="restaurant-v2-card"><header><div><small>الخدمة داخل المطعم</small><h2>الطاولات والأقسام</h2></div></header><form className="subscription-form" onSubmit={create}><label>الفرع<select name="branchId" required defaultValue={branches.find(x=>x.is_primary)?.id||branches[0]?.id||''}>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>القسم<select name="sectionName" defaultValue="غير مدخنين - داخلي"><option>غير مدخنين - داخلي</option><option>غير مدخنين - خارجي</option><option>مدخنين - داخلي</option><option>مدخنين - خارجي</option></select></label><label>رقم الطاولة<input name="tableNumber" required maxLength={40} inputMode="numeric"/></label><label>السعة<input name="capacity" required type="number" min="1" max="100" defaultValue="2"/></label><button className="primary-button" disabled={busy||!branches.length}>{busy?'جارٍ الحفظ…':'+ إضافة طاولة'}</button></form>
{tables.length?<div className="restaurant-v2-orders">{tables.map(x=><div key={x.id}><span><b>{x.section_name} · طاولة {x.table_number}</b><small>السعة {x.capacity} · QR {x.qr_token||'—'}</small></span><select value={x.status||'available'} disabled={busy} onChange={e=>void status(x.id,e.target.value)}><option value="available">متاحة</option><option value="busy">مشغولة</option><option value="reserved">محجوزة</option><option value="service">خدمة جارية</option></select></div>)}</div>:<div className="restaurant-v2-empty">لا توجد طاولات بعد.</div>}<p role="status">{msg}</p></article>}