import {z} from 'zod';
import {database} from '@/db';
import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
import {requireTenantFeature} from '@/lib/platform/entitlements';
export const dynamic='force-dynamic';
const status=z.enum(['new','pending','confirmed','preparing','ready','completed','delivered','cancelled']);
function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT',issues:e.issues},{status:400});console.error('Restaurant orders failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503})}
async function tenant(slug:string){const t=await database().prepare("SELECT id,currency FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string;currency:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);await requireTenantFeature(t.id,'orders');return {...t,userId:u.userId}}
export async function GET(req:Request){try{const url=new URL(req.url),slug=url.searchParams.get('slug')||'',filter=url.searchParams.get('status')||'';const t=await tenant(slug);const allowed=filter?status.parse(filter):null;const q=allowed?"SELECT id,reference,source,status,customer_name,customer_phone,subtotal,total,currency,created_at,updated_at FROM restaurant_orders WHERE tenant_id=? AND status=? ORDER BY created_at DESC LIMIT 200":"SELECT id,reference,source,status,customer_name,customer_phone,subtotal,total,currency,created_at,updated_at FROM restaurant_orders WHERE tenant_id=? ORDER BY created_at DESC LIMIT 200";const orders=allowed?await database().prepare(q).bind(t.id,allowed).all():await database().prepare(q).bind(t.id).all();const ids=(orders.results as any[]).map(x=>x.id);let items:any[]=[];if(ids.length){const marks=ids.map(()=>'?').join(',');items=(await database().prepare(`SELECT oi.id,oi.order_id,oi.item_name,oi.quantity,oi.unit_price,oi.line_total FROM restaurant_order_items oi JOIN restaurant_orders o ON o.id=oi.order_id WHERE o.tenant_id=? AND oi.order_id IN (${marks}) ORDER BY oi.order_id`).bind(t.id,...ids).all()).results as any[]}return Response.json({orders:orders.results,items})}catch(e){return fail(e)}}
export async function PATCH(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>10000)throw new ApiError(413,'INPUT_TOO_LARGE');const data=JSON.parse(raw),t=await tenant(String(data.slug||'')),id=z.string().uuid().parse(data.id),next=status.parse(data.status);const order=await database().prepare('SELECT id,status FROM restaurant_orders WHERE id=? AND tenant_id=? LIMIT 1').bind(id,t.id).first<{id:string;status:string}>();if(!order)throw new ApiError(404,'ORDER_NOT_FOUND');if(order.status===next)return Response.json({ok:true,status:next});await database().prepare('UPDATE restaurant_orders SET status=?,updated_at=? WHERE id=? AND tenant_id=?').bind(next,Date.now(),id,t.id).run();await audit(t.userId,`restaurant.order.status_changed:${order.status}->${next}`,t.id);return Response.json({ok:true,status:next})}catch(e){return fail(e)}}
