import { apiErrorResponse } from '@/lib/platform/error-reporting';
import { database } from '@/db';
import { hashPassword } from '@/lib/platform/password.mjs';
import { ApiError,actor,authorize,sameOrigin,encryptSecret,audit } from '@/lib/platform/security';
import { activities } from '@/lib/platform/activities';
import { events,locales,defaultTemplate,validPlaceholders } from '@/lib/platform/messages';
import { z } from 'zod';
import {sendTransactionalMessage,verifyEmailIntegration} from '@/lib/platform/delivery';
export const dynamic='force-dynamic';
const storeSchema=z.object({name:z.string().trim().min(2).max(120),slug:z.string().regex(/^[a-z][a-z0-9-]{2,59}$/),activityId:z.enum(activities.map(a=>a.id) as [string,...string[]]),countryCode:z.string().regex(/^[A-Z]{2}$/),currency:z.string().regex(/^[A-Z]{3}$/)});
const integrationSchema=z.object({kind:z.enum(['email','payment']),tenantId:z.string().optional(),activityId:z.enum(activities.map(a=>a.id) as [string,...string[]]).optional(),mode:z.enum(['platform','custom']).optional(),provider:z.string(),smtpHost:z.string().max(255).optional().default(''),smtpPort:z.coerce.number().int().min(1).max(65535).optional().default(587),smtpSecure:z.boolean().optional().default(false),smtpUsername:z.string().max(254).optional().default(''),fromEmail:z.string().max(200).optional().default(''),fromName:z.string().max(120).optional().default(''),publicKey:z.string().max(500).optional().default(''),secret:z.string().max(2000).optional().default(''),enabled:z.boolean()});
const templateSchema=z.object({tenantId:z.string().optional(),activityId:z.enum(activities.map(a=>a.id) as [string,...string[]]).optional(),event:z.enum(events),locale:z.enum(locales),subject:z.string().trim().min(1).max(300),body:z.string().trim().min(1).max(12000)});
function failure(error: unknown) { return apiErrorResponse(error, '/app/api/control'); }
async function config(kind:'email'|'payment',tenantId?:string,activityId?:string){const table=tenantId?(kind==='email'?'tenant_email_settings':'tenant_payment_settings'):kind==='email'&&activityId?'activity_email_settings':kind==='email'?'platform_email_settings':'platform_payment_settings';const column=tenantId?'tenant_id':kind==='email'&&activityId?'activity_id':'id';const id=tenantId??activityId??'platform';const row=await database().prepare('SELECT * FROM '+table+' WHERE '+column+'=?').bind(id).first<Record<string,unknown>>();if(!row)return null;const {secret_ciphertext,...safe}=row;return {...safe,hasSecret:Boolean(secret_ciphertext)};}
export async function GET(request:Request){try{const url=new URL(request.url);const action=url.searchParams.get('action')??'summary';const tenantId=url.searchParams.get('tenantId')??undefined;const activityId=url.searchParams.get('activityId')??undefined;
 if(action==='stores'){
  const u=await actor();
  if(u.admin){
   const freePlan=await database().prepare("SELECT id FROM package_plans WHERE enabled=1 AND monthly_price=0 ORDER BY created_at ASC LIMIT 1").first<{id:string}>();
   if(freePlan){
    const marker=await database().prepare("SELECT value FROM platform_settings WHERE key='free_plan_rollout_v1'").first<{value:string}>();
    if(!marker){
     const tenants=await database().prepare('SELECT id FROM tenants').all<{id:string}>();
     const now=Date.now();
     await database().prepare("UPDATE subscriptions SET status='cancelled',updated_at=? WHERE status='active'").bind(now).run();
     for(const tenant of tenants.results){
      await database().prepare("INSERT INTO subscriptions(id,tenant_id,plan_id,status,starts_at,expires_at,created_at,updated_at) VALUES(?,?,?,'active',?,NULL,?,?)").bind(crypto.randomUUID(),tenant.id,freePlan.id,now,now,now).run();
      await audit(u.userId,'subscription.migrated_to_free',tenant.id);
     }
     await database().prepare("INSERT INTO platform_settings(key,value,updated_at) VALUES('free_plan_rollout_v1',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(freePlan.id,Date.now()).run();
    }else{
     const missing=await database().prepare("SELECT t.id FROM tenants t WHERE NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.tenant_id=t.id AND s.status='active')").all<{id:string}>();
     for(const tenant of missing.results){
      const now=Date.now();
      await database().prepare("INSERT INTO subscriptions(id,tenant_id,plan_id,status,starts_at,expires_at,created_at,updated_at) VALUES(?,?,?,'active',?,NULL,?,?)").bind(crypto.randomUUID(),tenant.id,freePlan.id,now,now,now).run();
     }
    }
   }
  }
  const rows=u.admin
   ?await database().prepare("SELECT t.id,t.name,t.slug,t.activity_id,t.country_code,t.currency,t.status,t.created_at,(SELECT s.plan_id FROM subscriptions s WHERE s.tenant_id=t.id AND s.status='active' ORDER BY s.created_at DESC LIMIT 1) AS plan_id,(SELECT COALESCE(p.name_ar,p.name_en) FROM subscriptions s JOIN package_plans p ON p.id=s.plan_id WHERE s.tenant_id=t.id AND s.status='active' ORDER BY s.created_at DESC LIMIT 1) AS plan_name FROM tenants t ORDER BY t.created_at DESC").all()
   :await database().prepare("SELECT t.id,t.name,t.slug,t.activity_id,t.country_code,t.currency,t.status,t.created_at,(SELECT s.plan_id FROM subscriptions s WHERE s.tenant_id=t.id AND s.status='active' ORDER BY s.created_at DESC LIMIT 1) AS plan_id,(SELECT COALESCE(p.name_ar,p.name_en) FROM subscriptions s JOIN package_plans p ON p.id=s.plan_id WHERE s.tenant_id=t.id AND s.status='active' ORDER BY s.created_at DESC LIMIT 1) AS plan_name FROM tenants t JOIN memberships m ON m.tenant_id=t.id WHERE m.user_id=? AND m.role IN ('owner','manager') ORDER BY t.created_at DESC").bind(u.userId).all();
  return Response.json({stores:rows.results,admin:u.admin});
 }
 const u=await authorize(tenantId);if(activityId&&(tenantId||!u.admin))throw new ApiError(403,'FORBIDDEN');
 if(action==='plans'){if(!u.admin)throw new ApiError(403,'FORBIDDEN');await database().batch([
  database().prepare("INSERT IGNORE INTO feature_definitions(id,label_ar,label_en,label_fr,description_ar,description_en,description_fr,created_at) VALUES('reservations','الحجوزات والانتظار','Reservations & waitlist','Réservations et liste d’attente','استقبال طلبات الحجز من المنيو وإدارتها داخل لوحة المطعم.','Accept public booking requests and manage them in the restaurant workspace.','Recevoir les réservations et les gérer dans l’espace restaurant.',UNIX_TIMESTAMP()*1000)"),
  database().prepare("INSERT IGNORE INTO package_plan_features(plan_id,feature_id,enabled,feature_limit,updated_at) SELECT p.id,'reservations',COALESCE(orders.enabled,0),NULL,UNIX_TIMESTAMP()*1000 FROM package_plans p LEFT JOIN package_plan_features orders ON orders.plan_id=p.id AND orders.feature_id='orders'"),
  database().prepare("INSERT IGNORE INTO feature_definitions(id,label_ar,label_en,label_fr,description_ar,description_en,description_fr,created_at) VALUES('qr_menu','قائمة QR للطاولات','QR table menu','Menu QR par table','إنشاء رموز QR للطاولات وربط الطلبات بها.','Create table QR codes and accept orders through them.','Créer des QR de table et recevoir les commandes associées.',UNIX_TIMESTAMP()*1000)"),
  database().prepare("INSERT IGNORE INTO feature_definitions(id,label_ar,label_en,label_fr,description_ar,description_en,description_fr,created_at) VALUES('whatsapp_order','الطلب عبر WhatsApp','WhatsApp ordering','Commande par WhatsApp','إرسال تفاصيل السلة إلى WhatsApp الخاص بالمطعم.','Send cart details to the restaurant WhatsApp number.','Envoyer le panier au WhatsApp du restaurant.',UNIX_TIMESTAMP()*1000)"),
  database().prepare("INSERT IGNORE INTO package_plan_features(plan_id,feature_id,enabled,feature_limit,updated_at) SELECT pf.plan_id,'qr_menu',pf.enabled,NULL,UNIX_TIMESTAMP()*1000 FROM package_plan_features pf WHERE pf.feature_id='dine_in'"),
  database().prepare("INSERT IGNORE INTO package_plan_features(plan_id,feature_id,enabled,feature_limit,updated_at) SELECT pf.plan_id,'whatsapp_order',pf.enabled,NULL,UNIX_TIMESTAMP()*1000 FROM package_plan_features pf WHERE pf.feature_id='orders'"),
  database().prepare("INSERT IGNORE INTO feature_definitions(id,label_ar,label_en,label_fr,description_ar,description_en,description_fr,created_at) VALUES('welcome_page','صفحة الترحيب','Welcome page','Page d’accueil','موجودة ضمن واجهة FOON العامة؛ ليست صلاحية مستقلة للمطعم.','Provided by the shared FOON storefront; not a separate restaurant entitlement.','Incluse dans la vitrine FOON commune; pas une autorisation indépendante du restaurant.',UNIX_TIMESTAMP()*1000),('restaurant_packages','باقات الوجبات','Restaurant meal packages','Formules de repas','باقات الوجبات المركبة غير منفذة بعد؛ لا تُفعّل على الباقات حاليًا.','Meal bundles are not implemented yet; do not enable for plans.','Les formules repas ne sont pas encore implémentées; ne pas activer pour les forfaits.',UNIX_TIMESTAMP()*1000),('specialities','التخصصات والأقسام','Specialties & categories','Spécialités et catégories','تُدار الأقسام الحالية من ميزة المنيو؛ هذه تسمية توضيحية من المرجع.','Current categories are managed under Menu; this is a reference label.','Les catégories actuelles sont gérées dans Menu; cette entrée est informative.',UNIX_TIMESTAMP()*1000),('contacts','بيانات التواصل العامة','Public contact details','Coordonnées publiques','بيانات التواصل جزء من الملف العام للمطعم وليست صلاحية منفصلة.','Contact details are part of the restaurant profile, not a separate entitlement.','Les coordonnées font partie du profil du restaurant, pas d’une autorisation indépendante.',UNIX_TIMESTAMP()*1000),('affiliate','التسويق بالعمولة','Affiliate marketing','Marketing affilié','نظام التسويق بالعمولة غير منفذ بعد؛ لا تُفعّل هذه الميزة حاليًا.','Affiliate marketing is not implemented yet; do not enable this feature.','Le marketing affilié n’est pas encore implémenté; ne pas activer cette fonctionnalité.',UNIX_TIMESTAMP()*1000)"),
  database().prepare("INSERT IGNORE INTO package_plan_features(plan_id,feature_id,enabled,feature_limit,updated_at) SELECT p.id,f.id,0,NULL,UNIX_TIMESTAMP()*1000 FROM package_plans p JOIN feature_definitions f ON f.id IN ('welcome_page','restaurant_packages','specialities','contacts','affiliate')")
 ]);const freePlan=await database().prepare("SELECT id FROM package_plans WHERE enabled=1 AND monthly_price=0 ORDER BY created_at ASC LIMIT 1").first<{id:string}>();if(freePlan){const unassigned=await database().prepare("SELECT t.id FROM tenants t WHERE NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.tenant_id=t.id AND s.status='active')").all<{id:string}>();for(const tenant of unassigned.results)await database().prepare("INSERT INTO subscriptions(id,tenant_id,plan_id,status,starts_at,expires_at,created_at,updated_at) VALUES(?,?,?,'active',?,NULL,?,?)").bind(crypto.randomUUID(),tenant.id,freePlan.id,Date.now(),Date.now(),Date.now()).run()}const plans=await database().prepare(`SELECT p.id,p.name_ar,p.name_en,p.monthly_price,p.currency,p.enabled,m.description_ar,m.description_en,m.description_fr,m.yearly_price FROM package_plans p LEFT JOIN package_plan_meta m ON m.plan_id=p.id ORDER BY p.monthly_price,p.created_at`).all<Record<string,unknown>>();const features=await database().prepare('SELECT id,label_ar,label_en,label_fr,description_ar,description_en,description_fr FROM feature_definitions ORDER BY label_en').all<Record<string,unknown>>();const grants=await database().prepare('SELECT plan_id,feature_id,enabled,feature_limit FROM package_plan_features').all<Record<string,unknown>>();return Response.json({plans:plans.results,features:features.results,grants:grants.results});}
 if(action==='settings'){const rows=await database().prepare('SELECT key,value FROM platform_settings').all<{key:string;value:string}>();return Response.json({settings:Object.fromEntries(rows.results.map(r=>[r.key,r.value]))});}
 if(action==='summary'){const row=await database().prepare('SELECT (SELECT COUNT(*) FROM tenants) AS stores,(SELECT COUNT(*) FROM users) AS accounts,(SELECT COUNT(*) FROM platform_message_templates) AS saved_templates,(SELECT COUNT(*) FROM audit_events) AS audit_events').first();return Response.json({summary:row,email:u.email});}
 if(action==='audit'){if(!u.admin)throw new ApiError(403,'FORBIDDEN');const rows=await database().prepare('SELECT a.id,a.action,a.tenant_id,a.created_at,u.display_name,u.email,t.name AS tenant_name FROM audit_events a LEFT JOIN users u ON u.id=a.actor_id LEFT JOIN tenants t ON t.id=a.tenant_id ORDER BY a.created_at DESC LIMIT 200').all<Record<string,unknown>>();return Response.json({events:rows.results});}
 if(action==='templates'){
  let resolvedActivity=activityId;
  if(tenantId){const row=await database().prepare('SELECT activity_id FROM tenants WHERE id=?').bind(tenantId).first<{activity_id:string}>();resolvedActivity=row?.activity_id;}
  const tenantRows=tenantId?await database().prepare('SELECT event,locale,subject,body FROM tenant_message_templates WHERE tenant_id=?').bind(tenantId).all<Record<string,string>>():{results:[] as Record<string,string>[]};
  const activityRows=resolvedActivity?await database().prepare('SELECT event,locale,subject,body FROM activity_message_templates WHERE activity_id=?').bind(resolvedActivity).all<Record<string,string>>():{results:[] as Record<string,string>[]};
  const globalRows=await database().prepare('SELECT event,locale,subject,body FROM platform_message_templates').all<Record<string,string>>();
  const mode=tenantId?await database().prepare('SELECT mode FROM tenant_email_settings WHERE tenant_id=?').bind(tenantId).first<{mode:string}>():null;
  return Response.json({templates:events.flatMap(event=>locales.map(locale=>{
   const own=tenantId?tenantRows.results.find(x=>x.event===event&&x.locale===locale):undefined;
   const activity=!tenantId&&event!=='password_reset'&&event!=='subscription_updated'?activityRows.results.find(x=>x.event===event&&x.locale===locale):undefined;
   const shared=globalRows.results.find(x=>x.event===event&&x.locale===locale);
   return own?{...own,source:'custom'}:activity?{...activity,source:'activity'}:shared&&!tenantId?{...shared,source:'platform'}:defaultTemplate(event,locale,resolvedActivity);
  }))});
 }
 if(action==='integrations')return Response.json({email:await config('email',tenantId,activityId),payment:await config('payment',tenantId)});
 throw new ApiError(400,'INVALID_ACTION');}catch(e){return failure(e)}}
export async function POST(request:Request){try{sameOrigin(request);if(Number(request.headers.get('content-length'))>20000)throw new ApiError(413,'INPUT_TOO_LARGE');const raw=await request.text();if(raw.length>20000)throw new ApiError(413,'INPUT_TOO_LARGE');let data:Record<string,unknown>;try{data=JSON.parse(raw)}catch{throw new ApiError(400,'INVALID_INPUT')}const action=data.action;
 if(action==='save_translations'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const v=z.object({locale:z.enum(['ar','en','fr']),dictionary:z.record(z.string(),z.string().max(4000))}).parse(data);const entries=Object.entries(v.dictionary);if(entries.length>2000||entries.some(([key])=>!/^[A-Za-z0-9_.-]{1,160}$/.test(key)))throw new ApiError(400,'INVALID_INPUT');await database().prepare('INSERT INTO platform_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind('translations_'+v.locale+'_json',JSON.stringify(v.dictionary),Date.now()).run();await audit(u.userId,'translations.saved');return Response.json({saved:true});}
 if(action==='save_settings'){const u=await authorize();const url=z.union([z.string().url(),z.literal('')]);const v=z.object({siteName:z.string().trim().min(2).max(60),supportEmail:z.union([z.string().email(),z.literal('')]),instagramUrl:url,facebookUrl:url,linkedinUrl:url,snapchatUrl:url,tiktokUrl:url,twitterUrl:url,whatsappUrl:url,siteUrl:url,customPagesJson:z.string().max(12000).default('[]'),termsPageJson:z.string().max(12000).default(''),privacyPageJson:z.string().max(12000).default(''),refundPageJson:z.string().max(12000).default('')}).parse(data);try{const pages=JSON.parse(v.customPagesJson);if(!Array.isArray(pages)||pages.some((p:unknown)=>!p||typeof p!=='object'||!('slug' in p)||!z.string().regex(/^[a-z0-9-]{2,60}$/).safeParse((p as {slug:unknown}).slug).success))throw new Error()}catch{throw new ApiError(400,'INVALID_INPUT')}const now=Date.now();await database().batch([['site_name',v.siteName],['support_email',v.supportEmail],['instagram_url',v.instagramUrl],['facebook_url',v.facebookUrl],['linkedin_url',v.linkedinUrl],['snapchat_url',v.snapchatUrl],['tiktok_url',v.tiktokUrl],['twitter_url',v.twitterUrl],['whatsapp_url',v.whatsappUrl],['site_url',v.siteUrl],['custom_pages_json',v.customPagesJson],['terms_page_json',v.termsPageJson],['privacy_page_json',v.privacyPageJson],['refund_page_json',v.refundPageJson]].map(([key,value])=>database().prepare('INSERT INTO platform_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind(key,value,now)));await audit(u.userId,'platform.settings_saved');return Response.json({saved:true});}
 if(action==='save_plan'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const v=z.object({id:z.string().regex(/^[a-z0-9-]{2,40}$/),nameAr:z.string().trim().min(2).max(120),nameEn:z.string().trim().min(2).max(120),monthlyPrice:z.coerce.number().min(0).max(99999999),yearlyPrice:z.coerce.number().min(0).max(99999999),currency:z.string().regex(/^[A-Z]{3}$/),enabled:z.boolean(),descriptionAr:z.string().max(3000).default(''),descriptionEn:z.string().max(3000).default(''),descriptionFr:z.string().max(3000).default('')}).parse(data);const now=Date.now();await database().batch([database().prepare('UPDATE package_plans SET name_ar=?,name_en=?,monthly_price=?,currency=?,enabled=? WHERE id=?').bind(v.nameAr,v.nameEn,v.monthlyPrice.toFixed(2),v.currency,v.enabled?1:0,v.id),database().prepare('INSERT INTO package_plan_meta(plan_id,description_ar,description_en,description_fr,plan_type,yearly_price,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(plan_id) DO UPDATE SET description_ar=excluded.description_ar,description_en=excluded.description_en,description_fr=excluded.description_fr,yearly_price=excluded.yearly_price,updated_at=excluded.updated_at').bind(v.id,v.descriptionAr,v.descriptionEn,v.descriptionFr,'monthly',v.yearlyPrice.toFixed(2),now)]);await audit(u.userId,'plan.updated');return Response.json({saved:true});}
 if(action==='save_plan_feature'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const v=z.object({planId:z.string().max(40),featureId:z.string().max(80),enabled:z.boolean(),limit:z.union([z.coerce.number().int().min(0),z.null()])}).parse(data);if(['welcome_page','restaurant_packages','specialities','contacts','affiliate'].includes(v.featureId))throw new ApiError(409,'FEATURE_NOT_SEPARATELY_CONFIGURABLE');await database().prepare('INSERT INTO package_plan_features(plan_id,feature_id,enabled,feature_limit,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(plan_id,feature_id) DO UPDATE SET enabled=excluded.enabled,feature_limit=excluded.feature_limit,updated_at=excluded.updated_at').bind(v.planId,v.featureId,v.enabled?1:0,v.limit,Date.now()).run();await audit(u.userId,'plan.feature_updated');return Response.json({saved:true});}
 if(action==='create_feature'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const v=z.object({id:z.string().regex(/^[a-z0-9_-]{2,80}$/),labelAr:z.string().trim().min(2).max(160),labelEn:z.string().trim().min(2).max(160),labelFr:z.string().max(160).default('')}).parse(data);await database().prepare('INSERT INTO feature_definitions(id,label_ar,label_en,label_fr,created_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET label_ar=excluded.label_ar,label_en=excluded.label_en,label_fr=excluded.label_fr').bind(v.id,v.labelAr,v.labelEn,v.labelFr,Date.now()).run();await audit(u.userId,'feature.saved');return Response.json({saved:true});}
 if(action==='set_store_plan'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const v=z.object({tenantId:z.string().uuid(),planId:z.string().regex(/^[a-z0-9-]{2,40}$/)}).parse(data);const [tenant,plan]=await Promise.all([database().prepare('SELECT id FROM tenants WHERE id=?').bind(v.tenantId).first(),database().prepare('SELECT id FROM package_plans WHERE id=? AND enabled=1').bind(v.planId).first()]);if(!tenant||!plan)throw new ApiError(404,'NOT_FOUND');const now=Date.now();await database().batch([database().prepare("UPDATE subscriptions SET status='cancelled',updated_at=? WHERE tenant_id=? AND status='active'").bind(now,v.tenantId),database().prepare("INSERT INTO subscriptions(id,tenant_id,plan_id,status,starts_at,expires_at,created_at,updated_at) VALUES(?,?,?,'active',?,NULL,?,?)").bind(crypto.randomUUID(),v.tenantId,v.planId,now,now,now)]);await audit(u.userId,'store.plan_updated',v.tenantId);return Response.json({saved:true,planId:v.planId});}
 if(action==='reset_store_password'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const v=z.object({tenantId:z.string().uuid(),password:z.string().min(9).max(128)}).parse(data);const owner=await database().prepare("SELECT u.id,u.email FROM tenants t JOIN users u ON u.id=t.created_by JOIN memberships m ON m.tenant_id=t.id AND m.user_id=u.id AND m.role='owner' WHERE t.id=?").bind(v.tenantId).first<{id:string;email:string}>();if(!owner||owner.email.toLowerCase()===process.env.PLATFORM_ADMIN_EMAIL?.toLowerCase())throw new ApiError(404,'OWNER_NOT_FOUND');await database().batch([database().prepare('UPDATE users SET password_hash=? WHERE id=?').bind(await hashPassword(v.password),owner.id),database().prepare('DELETE FROM auth_sessions WHERE user_id=?').bind(owner.id)]);await audit(u.userId,'store.owner_password_reset',v.tenantId);return Response.json({saved:true});}
 if(action==='set_store_status'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const v=z.object({id:z.string().uuid(),status:z.enum(['draft','active','suspended'])}).parse(data);const tenant=await database().prepare('SELECT activity_id FROM tenants WHERE id=?').bind(v.id).first<{activity_id:string}>();if(!tenant)throw new ApiError(404,'NOT_FOUND');await database().prepare('UPDATE tenants SET status=? WHERE id=?').bind(v.status,v.id).run();await audit(u.userId,'store.status_'+v.status,v.id);return Response.json({saved:true,status:v.status});}
 if(action==='create_store'){const u=await authorize();const v=storeSchema.parse(data);const id=crypto.randomUUID();const collision=await database().prepare('SELECT id FROM tenants WHERE slug=?').bind(v.slug).first();if(collision)throw new ApiError(409,'SLUG_EXISTS');await database().batch([database().prepare('INSERT INTO tenants(id,name,slug,activity_id,country_code,currency,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,v.name,v.slug,v.activityId,v.countryCode,v.currency,'draft',u.userId,Date.now()),database().prepare('INSERT INTO branches(id,tenant_id,name,is_primary) VALUES(?,?,?,1)').bind(crypto.randomUUID(),id,v.name)]);await audit(u.userId,'store.created',id);return Response.json({id}, {status:201});}
 if(action==='send_test'){const v=z.object({tenantId:z.string().optional(),activityId:z.enum(activities.map(a=>a.id) as [string,...string[]]).optional(),locale:z.enum(locales),requestId:z.string().uuid()}).parse(data);const u=await authorize(v.tenantId);if(v.activityId&&(v.tenantId||!u.admin))throw new ApiError(403,'FORBIDDEN');const recent=await database().prepare('SELECT COUNT(*) AS total FROM audit_events WHERE actor_id=? AND action=? AND created_at>?').bind(u.userId,'email.test_requested',Date.now()-3600000).first<{total:number}>();if((recent?.total??0)>=5)throw new ApiError(429,'TEST_LIMIT');await audit(u.userId,'email.test_requested',v.tenantId??null);const tenant=v.tenantId?await database().prepare('SELECT name,currency FROM tenants WHERE id=?').bind(v.tenantId).first<{name:string;currency:string}>():null;const sent=await sendTransactionalMessage({tenantId:v.tenantId,activityId:v.activityId,event:'welcome',locale:v.locale,recipient:u.email,variables:{customer_name:u.displayName,store_name:tenant?.name??'FOON',service_number:'TEST',service_type:'TEST',amount:'0',currency:tenant?.currency??'SAR',date:new Date().toISOString(),plan_name:'TEST',expires_at:'TEST'},idempotencyKey:v.requestId});return Response.json(sent);}
 if(action==='verify_email'){
  const v=z.object({tenantId:z.string().optional(),activityId:z.enum(activities.map(a=>a.id) as [string,...string[]]).optional()}).parse(data);
  const u=await authorize(v.tenantId);if(v.activityId&&(v.tenantId||!u.admin))throw new ApiError(403,'FORBIDDEN');
  const table=v.tenantId?'tenant_email_settings':v.activityId?'activity_email_settings':'platform_email_settings',key=v.tenantId?'tenant_id':v.activityId?'activity_id':'id',id=v.tenantId??v.activityId??'platform';
  try{await verifyEmailIntegration({tenantId:v.tenantId,activityId:v.activityId});await database().prepare("UPDATE "+table+" SET smtp_last_test_at=?,smtp_last_test_status='passed' WHERE "+key+"=?").bind(Date.now(),id).run();await audit(u.userId,'email.smtp_verified',v.tenantId??null);return Response.json({verified:true});}
  catch(error){await database().prepare("UPDATE "+table+" SET smtp_last_test_at=?,smtp_last_test_status='failed' WHERE "+key+"=?").bind(Date.now(),id).run();throw error;}
 }
 if(action==='save_template'){
  const v=templateSchema.parse(data);const u=await authorize(v.tenantId);if(v.activityId&&(v.tenantId||!u.admin))throw new ApiError(403,'FORBIDDEN');
  if(!validPlaceholders(v.subject)||!validPlaceholders(v.body))throw new ApiError(400,'INVALID_PLACEHOLDER');
  if(v.tenantId){if(v.event==='subscription_updated'||v.event==='password_reset')throw new ApiError(403,'FORBIDDEN');await database().prepare('INSERT INTO tenant_message_templates(tenant_id,event,locale,subject,body,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(tenant_id,event,locale) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=excluded.updated_at').bind(v.tenantId,v.event,v.locale,v.subject,v.body,Date.now()).run();}
  else if(v.activityId){if(v.event==='password_reset'||v.event==='subscription_updated')throw new ApiError(403,'FORBIDDEN');await database().prepare('INSERT INTO activity_message_templates(activity_id,event,locale,subject,body,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(activity_id,event,locale) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=excluded.updated_at').bind(v.activityId,v.event,v.locale,v.subject,v.body,Date.now()).run();}
  else await database().prepare('INSERT INTO platform_message_templates(event,locale,subject,body,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(event,locale) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=excluded.updated_at').bind(v.event,v.locale,v.subject,v.body,Date.now()).run();
  await audit(u.userId,'message.template_saved',v.tenantId??null);return Response.json({saved:true});
 }
 if(action==='save_integration'){
  const v=integrationSchema.parse(data);const u=await authorize(v.tenantId);
  if(v.activityId&&(v.tenantId||!u.admin||v.kind!=='email'))throw new ApiError(403,'FORBIDDEN');
  if(v.kind==='email'&&v.provider!=='smtp')throw new ApiError(400,'INVALID_PROVIDER');
  if(v.kind==='payment'&&!['moyasar','stripe'].includes(v.provider))throw new ApiError(400,'INVALID_PROVIDER');
  const activityScope=Boolean(v.activityId);
  const table=v.tenantId?(v.kind==='email'?'tenant_email_settings':'tenant_payment_settings'):activityScope?'activity_email_settings':(v.kind==='email'?'platform_email_settings':'platform_payment_settings');
  const key=v.tenantId?'tenant_id':activityScope?'activity_id':'id';
  const id=v.tenantId??v.activityId??'platform';
  const current=await database().prepare('SELECT secret_ciphertext,provider FROM '+table+' WHERE '+key+'=?').bind(id).first<{secret_ciphertext:string|null;provider:string}>();
  const scope=table+':'+id;
  const secret=v.secret?await encryptSecret(v.secret,scope):current?.provider===v.provider?current.secret_ciphertext:null;
  const inherited=false;
  if(v.enabled&&!inherited&&!secret)throw new ApiError(400,'SECRET_REQUIRED');
  if(v.kind==='email'&&v.enabled&&(!z.string().email().safeParse(v.fromEmail).success||!v.smtpHost||!v.smtpUsername))throw new ApiError(400,'SMTP_CONFIGURATION_REQUIRED');
  if(v.kind==='email'){
   const isTenant=Boolean(v.tenantId),fields=isTenant?'tenant_id,mode,provider,smtp_host,smtp_port,smtp_secure,smtp_username,from_email,from_name,secret_ciphertext,enabled,updated_at':activityScope?'activity_id,provider,smtp_host,smtp_port,smtp_secure,smtp_username,from_email,from_name,secret_ciphertext,enabled,updated_at':'id,provider,smtp_host,smtp_port,smtp_secure,smtp_username,from_email,from_name,secret_ciphertext,enabled,updated_at';
   const values=isTenant?[id,'custom',v.provider,v.smtpHost,v.smtpPort,v.smtpSecure?1:0,v.smtpUsername,v.fromEmail,v.fromName,secret,v.enabled?1:0,Date.now()]:[id,v.provider,v.smtpHost,v.smtpPort,v.smtpSecure?1:0,v.smtpUsername,v.fromEmail,v.fromName,secret,v.enabled?1:0,Date.now()];
   const conflict=isTenant?'mode=excluded.mode,':'';
   await database().prepare('INSERT INTO '+table+'('+fields+') VALUES('+values.map(()=>'?').join(',')+') ON CONFLICT('+key+') DO UPDATE SET '+conflict+'provider=excluded.provider,smtp_host=excluded.smtp_host,smtp_port=excluded.smtp_port,smtp_secure=excluded.smtp_secure,smtp_username=excluded.smtp_username,from_email=excluded.from_email,from_name=excluded.from_name,secret_ciphertext=excluded.secret_ciphertext,enabled=excluded.enabled,smtp_last_test_at=NULL,smtp_last_test_status=?,updated_at=excluded.updated_at').bind(...values,'not_tested').run();
  }else{
   await database().prepare('INSERT INTO '+table+'('+key+',provider,public_key,secret_ciphertext,enabled,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT('+key+') DO UPDATE SET provider=excluded.provider,public_key=excluded.public_key,secret_ciphertext=excluded.secret_ciphertext,enabled=excluded.enabled,updated_at=excluded.updated_at').bind(id,v.provider,v.publicKey,secret,v.enabled?1:0,Date.now()).run();
  }
  await audit(u.userId,activityScope?'activity.email.settings_saved':v.kind+'.settings_saved',v.tenantId??null);return Response.json({saved:true});
 }
 throw new ApiError(400,'INVALID_ACTION');}catch(e){return failure(e)}}
