import { database } from '@/db';
import { ApiError,actor,authorize,sameOrigin,encryptSecret,audit } from '@/lib/platform/security';
import { activities } from '@/lib/platform/activities';
import { events,locales,defaultTemplate,validPlaceholders } from '@/lib/platform/messages';
import { z } from 'zod';
import {sendTransactionalMessage} from '@/lib/platform/delivery';
export const dynamic='force-dynamic';
const storeSchema=z.object({name:z.string().trim().min(2).max(120),slug:z.string().regex(/^[a-z][a-z0-9-]{2,59}$/),activityId:z.enum(activities.map(a=>a.id) as [string,...string[]]),countryCode:z.string().regex(/^[A-Z]{2}$/),currency:z.string().regex(/^[A-Z]{3}$/)});
const integrationSchema=z.object({kind:z.enum(['email','payment']),tenantId:z.string().optional(),mode:z.enum(['platform','custom']).optional(),provider:z.string(),fromEmail:z.string().max(200).optional().default(''),fromName:z.string().max(120).optional().default(''),publicKey:z.string().max(500).optional().default(''),secret:z.string().max(2000).optional().default(''),enabled:z.boolean()});
const templateSchema=z.object({tenantId:z.string().optional(),event:z.enum(events),locale:z.enum(locales),subject:z.string().trim().min(1).max(300),body:z.string().trim().min(1).max(12000)});
function failure(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT'},{status:400});console.error('Control operation failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503});}
async function config(kind:'email'|'payment',tenantId?:string){const table=tenantId?(kind==='email'?'tenant_email_settings':'tenant_payment_settings'):(kind==='email'?'platform_email_settings':'platform_payment_settings');const column=tenantId?'tenant_id':'id';const row=await database().prepare(`SELECT * FROM ${table} WHERE ${column}=?`).bind(tenantId??'platform').first<Record<string,unknown>>();if(!row)return null;const {secret_ciphertext,...safe}=row;return {...safe,hasSecret:Boolean(secret_ciphertext)};}
export async function GET(request:Request){try{const url=new URL(request.url);const action=url.searchParams.get('action')??'summary';const tenantId=url.searchParams.get('tenantId')??undefined;
 if(action==='stores'){const u=await actor();const rows=u.admin?await database().prepare('SELECT id,name,slug,activity_id,country_code,currency,status,created_at FROM tenants ORDER BY created_at DESC').all():await database().prepare("SELECT t.id,t.name,t.slug,t.activity_id,t.country_code,t.currency,t.status,t.created_at FROM tenants t JOIN memberships m ON m.tenant_id=t.id WHERE m.user_id=? AND m.role IN ('owner','manager') ORDER BY t.created_at DESC").bind(u.userId).all();return Response.json({stores:rows.results,admin:u.admin});}
 const u=await authorize(tenantId);
 if(action==='settings'){const rows=await database().prepare('SELECT key,value FROM platform_settings').all<{key:string;value:string}>();return Response.json({settings:Object.fromEntries(rows.results.map(r=>[r.key,r.value]))});}
 if(action==='summary'){const row=await database().prepare('SELECT (SELECT COUNT(*) FROM tenants) AS stores,(SELECT COUNT(*) FROM users) AS accounts,(SELECT COUNT(*) FROM platform_message_templates) AS saved_templates,(SELECT COUNT(*) FROM audit_events) AS audit_events').first();return Response.json({summary:row,email:u.email});}
 if(action==='templates'){const saved=tenantId?await database().prepare('SELECT event,locale,subject,body FROM tenant_message_templates WHERE tenant_id=?').bind(tenantId).all<Record<string,string>>():await database().prepare('SELECT event,locale,subject,body FROM platform_message_templates').all<Record<string,string>>();const mode=tenantId?await database().prepare('SELECT mode FROM tenant_email_settings WHERE tenant_id=?').bind(tenantId).first<{mode:string}>():null;const global=tenantId?await database().prepare('SELECT event,locale,subject,body FROM platform_message_templates').all<Record<string,string>>():saved;return Response.json({templates:events.flatMap(event=>locales.map(locale=>{const own=(tenantId&&mode?.mode!=='custom'?[]:saved.results).find(x=>x.event===event&&x.locale===locale);const shared=global.results.find(x=>x.event===event&&x.locale===locale);return own?{...own,source:tenantId?'custom':'platform'}:shared?{...shared,source:'platform'}:defaultTemplate(event,locale)}))});}
 if(action==='integrations')return Response.json({email:await config('email',tenantId),payment:await config('payment',tenantId)});
 throw new ApiError(400,'INVALID_ACTION');}catch(e){return failure(e)}}
export async function POST(request:Request){try{sameOrigin(request);if(Number(request.headers.get('content-length'))>20000)throw new ApiError(413,'INPUT_TOO_LARGE');const raw=await request.text();if(raw.length>20000)throw new ApiError(413,'INPUT_TOO_LARGE');let data:Record<string,unknown>;try{data=JSON.parse(raw)}catch{throw new ApiError(400,'INVALID_INPUT')}const action=data.action;
 if(action==='save_settings'){const u=await authorize();const v=z.object({siteName:z.string().trim().min(2).max(60),supportEmail:z.union([z.string().email(),z.literal('')])}).parse(data);await database().batch([database().prepare('INSERT INTO platform_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind('site_name',v.siteName,Date.now()),database().prepare('INSERT INTO platform_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind('support_email',v.supportEmail,Date.now())]);await audit(u.userId,'platform.settings_saved');return Response.json({saved:true});}
 if(action==='create_store'){const u=await authorize();const v=storeSchema.parse(data);const id=crypto.randomUUID();const collision=await database().prepare('SELECT id FROM tenants WHERE slug=?').bind(v.slug).first();if(collision)throw new ApiError(409,'SLUG_EXISTS');await database().batch([database().prepare('INSERT INTO tenants(id,name,slug,activity_id,country_code,currency,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,v.name,v.slug,v.activityId,v.countryCode,v.currency,'draft',u.userId,Date.now()),database().prepare('INSERT INTO branches(id,tenant_id,name,is_primary) VALUES(?,?,?,1)').bind(crypto.randomUUID(),id,v.name)]);await audit(u.userId,'store.created',id);return Response.json({id}, {status:201});}
 if(action==='send_test'){const v=z.object({tenantId:z.string().optional(),locale:z.enum(locales),requestId:z.string().uuid()}).parse(data);const u=await authorize(v.tenantId);const recent=await database().prepare('SELECT COUNT(*) AS total FROM audit_events WHERE actor_id=? AND action=? AND created_at>?').bind(u.userId,'email.test_requested',Date.now()-3600000).first<{total:number}>();if((recent?.total??0)>=5)throw new ApiError(429,'TEST_LIMIT');await audit(u.userId,'email.test_requested',v.tenantId??null);const tenant=v.tenantId?await database().prepare('SELECT name,currency FROM tenants WHERE id=?').bind(v.tenantId).first<{name:string;currency:string}>():null;const sent=await sendTransactionalMessage({tenantId:v.tenantId,event:'welcome',locale:v.locale,recipient:u.email,variables:{customer_name:u.displayName,store_name:tenant?.name??'FOON',service_number:'TEST',service_type:'TEST',amount:'0',currency:tenant?.currency??'SAR',date:new Date().toISOString(),plan_name:'TEST',expires_at:'TEST'},idempotencyKey:v.requestId});return Response.json(sent);}
 if(action==='save_template'){const v=templateSchema.parse(data);const u=await authorize(v.tenantId);if(!validPlaceholders(v.subject)||!validPlaceholders(v.body))throw new ApiError(400,'INVALID_PLACEHOLDER');if(v.tenantId){if(v.event==='subscription_updated')throw new ApiError(403,'FORBIDDEN');const row=await database().prepare('SELECT mode FROM tenant_email_settings WHERE tenant_id=?').bind(v.tenantId).first<{mode:string}>();if(row?.mode!=='custom')throw new ApiError(409,'CUSTOM_EMAIL_REQUIRED');await database().prepare('INSERT INTO tenant_message_templates(tenant_id,event,locale,subject,body,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(tenant_id,event,locale) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=excluded.updated_at').bind(v.tenantId,v.event,v.locale,v.subject,v.body,Date.now()).run();}else await database().prepare('INSERT INTO platform_message_templates(event,locale,subject,body,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(event,locale) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=excluded.updated_at').bind(v.event,v.locale,v.subject,v.body,Date.now()).run();await audit(u.userId,'template.saved',v.tenantId??null);return Response.json({saved:true});}
 if(action==='save_integration'){const v=integrationSchema.parse(data);const u=await authorize(v.tenantId);if(v.kind==='email'&&v.provider!=='resend')throw new ApiError(400,'INVALID_PROVIDER');if(v.kind==='payment'&&!['moyasar','stripe'].includes(v.provider))throw new ApiError(400,'INVALID_PROVIDER');const table=v.tenantId?(v.kind==='email'?'tenant_email_settings':'tenant_payment_settings'):(v.kind==='email'?'platform_email_settings':'platform_payment_settings');const key=v.tenantId?'tenant_id':'id';const id=v.tenantId??'platform';const current=await database().prepare(`SELECT secret_ciphertext,provider FROM ${table} WHERE ${key}=?`).bind(id).first<{secret_ciphertext:string|null,provider:string}>();const secret=v.secret?await encryptSecret(v.secret,`${table}:${id}`):current?.provider===v.provider?current.secret_ciphertext:null;const inherited=v.kind==='email'&&v.tenantId&&v.mode==='platform';if(v.enabled&&!inherited&&!secret)throw new ApiError(400,'SECRET_REQUIRED');if(v.kind==='email'&&v.enabled&&!inherited&&!z.string().email().safeParse(v.fromEmail).success)throw new ApiError(400,'SENDER_REQUIRED');
 if(v.kind==='email'){const fields=v.tenantId?'tenant_id,mode,provider,from_email,from_name,secret_ciphertext,enabled,updated_at':'id,provider,from_email,from_name,secret_ciphertext,enabled,updated_at';const values=v.tenantId?[id,v.mode??'platform',v.provider,v.fromEmail,v.fromName,secret,v.enabled?1:0,Date.now()]:[id,v.provider,v.fromEmail,v.fromName,secret,v.enabled?1:0,Date.now()];await database().prepare(`INSERT INTO ${table}(${fields}) VALUES(${values.map(()=>'?').join(',')}) ON CONFLICT(${key}) DO UPDATE SET ${v.tenantId?'mode=excluded.mode,':''}provider=excluded.provider,from_email=excluded.from_email,from_name=excluded.from_name,secret_ciphertext=excluded.secret_ciphertext,enabled=excluded.enabled,updated_at=excluded.updated_at`).bind(...values).run();}
 else await database().prepare(`INSERT INTO ${table}(${key},provider,public_key,secret_ciphertext,enabled,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(${key}) DO UPDATE SET provider=excluded.provider,public_key=excluded.public_key,secret_ciphertext=excluded.secret_ciphertext,enabled=excluded.enabled,updated_at=excluded.updated_at`).bind(id,v.provider,v.publicKey,secret,v.enabled?1:0,Date.now()).run();await audit(u.userId,`${v.kind}.settings_saved`,v.tenantId??null);return Response.json({saved:true});}
 throw new ApiError(400,'INVALID_ACTION');}catch(e){return failure(e)}}
