import {z} from 'zod';import {database} from '@/db';import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
export const dynamic='force-dynamic';
const line=z.object({inventoryItemId:z.string().uuid().nullable().optional(),itemName:z.string().trim().min(1).max(180),quantity:z.number().positive().max(1000000),unitCost:z.number().min(0).max(999999999)});
const create=z.object({slug:z.string(),supplierId:z.string().uuid().nullable().optional(),branchId:z.string().uuid().nullable().optional(),reference:z.string().trim().min(1).max(50),tax:z.number().min(0).max(999999999).default(0),notes:z.string().trim().max(1000).optional().default(''),items:z.array(line).min(1).max(200)});
function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT',issues:e.issues},{status:400});console.error('Purchases failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503})}
async function tenant(slug:string){const t=await database().prepare("SELECT id FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);return {...t,userId:u.userId}}
export async function POST(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>100000)throw new ApiError(413,'INPUT_TOO_LARGE');const data=JSON.parse(raw),action=String(data.action||'');
 if(action==='create'){const v=create.parse(data),t=await tenant(v.slug),id=crypto.randomUUID(),now=Date.now();if(v.supplierId&&!await database().prepare('SELECT id FROM suppliers WHERE id=? AND tenant_id=?').bind(v.supplierId,t.id).first())throw new ApiError(400,'INVALID_SUPPLIER');if(v.branchId&&!await database().prepare('SELECT id FROM branches WHERE id=? AND tenant_id=?').bind(v.branchId,t.id).first())throw new ApiError(400,'INVALID_BRANCH');for(const x of v.items)if(x.inventoryItemId&&!await database().prepare('SELECT id FROM inventory_items WHERE id=? AND tenant_id=?').bind(x.inventoryItemId,t.id).first())throw new ApiError(400,'INVALID_INVENTORY_ITEM');const subtotal=v.items.reduce((s,x)=>s+x.quantity*x.unitCost,0),total=subtotal+v.tax;const stmts=[database().prepare("INSERT INTO purchase_orders(id,tenant_id,branch_id,supplier_id,reference,status,subtotal,tax,total,notes,created_at,updated_at) VALUES(?,?,?,?,?,'draft',?,?,?,?,?,?)").bind(id,t.id,v.branchId||null,v.supplierId||null,v.reference,subtotal,v.tax,total,v.notes||null,now,now),...v.items.map(x=>database().prepare('INSERT INTO purchase_order_items(id,purchase_order_id,inventory_item_id,item_name,quantity,unit_cost,line_total) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,x.inventoryItemId||null,x.itemName,x.quantity,x.unitCost,x.quantity*x.unitCost))];await database().batch(stmts);await audit(t.userId,'restaurant.purchase.created',t.id);return Response.json({id,total},{status:201})}
 if(action==='receive'){const slug=z.string().parse(data.slug),id=z.string().uuid().parse(data.id),t=await tenant(slug),po=await database().prepare("SELECT id,branch_id,status FROM purchase_orders WHERE id=? AND tenant_id=?").bind(id,t.id).first<{id:string;branch_id:string|null;status:string}>();if(!po)throw new ApiError(404,'PURCHASE_NOT_FOUND');if(po.status==='received')return Response.json({ok:true,status:'received'});if(!['draft','ordered'].includes(po.status))throw new ApiError(409,'INVALID_PURCHASE_STATUS');const items=(await database().prepare('SELECT inventory_item_id,quantity,unit_cost FROM purchase_order_items WHERE purchase_order_id=?').bind(id).all<{inventory_item_id:string|null;quantity:number|string;unit_cost:number|string}>()).results,now=Date.now(),stmts=[];for(const x of items){if(!x.inventory_item_id)continue;stmts.push(database().prepare('UPDATE inventory_items SET quantity=quantity+?,cost=?,updated_at=? WHERE id=? AND tenant_id=?').bind(Number(x.quantity),Number(x.unit_cost),now,x.inventory_item_id,t.id));stmts.push(database().prepare("INSERT INTO inventory_movements(id,tenant_id,branch_id,inventory_item_id,movement_type,quantity,unit_cost,reference_type,reference_id,note,actor_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),t.id,po.branch_id,x.inventory_item_id,'purchase',Number(x.quantity),Number(x.unit_cost),'purchase',id,'Purchase received',t.userId,now))}stmts.push(database().prepare("UPDATE purchase_orders SET status='received',updated_at=? WHERE id=? AND tenant_id=?").bind(now,id,t.id));await database().batch(stmts);await audit(t.userId,'restaurant.purchase.received',t.id);return Response.json({ok:true,status:'received'})}
 throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}