import {database} from '@/db';
import {ApiError,decryptSecret} from './security';
import {defaultTemplate, type MessageEvent} from './messages';
import type {Locale} from './contracts';
type EmailSettings={provider:string;from_email:string;from_name:string;secret_ciphertext:string|null;enabled:number;mode?:string};
export async function resolveEmailSettings(tenantId?:string,event?:MessageEvent){if(tenantId&&event!=='subscription_updated'){const own=await database().prepare('SELECT * FROM tenant_email_settings WHERE tenant_id=?').bind(tenantId).first<EmailSettings>();if(own?.mode==='custom')return {settings:own,scope:`tenant_email_settings:${tenantId}`,custom:true};}return {settings:await database().prepare('SELECT * FROM platform_email_settings WHERE id=?').bind('platform').first<EmailSettings>(),scope:'platform_email_settings:platform',custom:false};}
export async function resolveTemplate(event:MessageEvent,locale:Locale,tenantId?:string){const delivery=await resolveEmailSettings(tenantId,event);if(delivery.custom&&tenantId){const own=await database().prepare('SELECT subject,body FROM tenant_message_templates WHERE tenant_id=? AND event=? AND locale=?').bind(tenantId,event,locale).first<{subject:string;body:string}>();if(own)return {...own,source:'custom'};}const shared=await database().prepare('SELECT subject,body FROM platform_message_templates WHERE event=? AND locale=?').bind(event,locale).first<{subject:string;body:string}>();return shared?{...shared,source:'platform'}:defaultTemplate(event,locale);}
export function interpolate(value:string,variables:Record<string,string>){return value.replace(/{{\s*([^{}]+)\s*}}/g,(_,key:string)=>{if(!(key.trim() in variables))throw new ApiError(400,'MISSING_VARIABLE');return variables[key.trim()]});}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export async function sendTransactionalMessage(input:{tenantId?:string;event:MessageEvent;locale:Locale;recipient:string;variables:Record<string,string>;idempotencyKey:string}){
 const delivery=await resolveEmailSettings(input.tenantId,input.event);const config=delivery.settings;if(!config?.enabled||!config.secret_ciphertext||!config.from_email)throw new ApiError(409,'EMAIL_NOT_CONFIGURED');
 const template=await resolveTemplate(input.event,input.locale,input.tenantId);const subject=interpolate(template.subject,input.variables);const body=interpolate(template.body,input.variables);if(/[\r\n]/.test(subject))throw new ApiError(400,'INVALID_INPUT');const key=`${input.tenantId??'platform'}:${input.event}:${input.idempotencyKey}`;if(key.length>256)throw new ApiError(400,'INVALID_INPUT');
 const id=crypto.randomUUID();await database().prepare('INSERT OR IGNORE INTO message_outbox(id,tenant_id,event,locale,recipient,subject,body,status,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,\'pending\',?,?)').bind(id,input.tenantId??null,input.event,input.locale,input.recipient,subject,body,key,Date.now()).run();
 const row=await database().prepare('SELECT id,status,recipient,subject,body FROM message_outbox WHERE idempotency_key=?').bind(key).first<{id:string;status:string;recipient:string;subject:string;body:string}>();if(!row)throw new ApiError(503,'SERVICE_UNAVAILABLE');if(row.recipient!==input.recipient||row.subject!==subject||row.body!==body)throw new ApiError(409,'IDEMPOTENCY_CONFLICT');if(row.status==='accepted')return {id:row.id,status:'accepted'};const claim=await database().prepare("UPDATE message_outbox SET status='sending' WHERE id=? AND status='pending'").bind(row.id).run();if(!claim.meta.changes)throw new ApiError(409,'MESSAGE_ALREADY_PROCESSED');
 try{const secret=await decryptSecret(config.secret_ciphertext,delivery.scope);const from=config.from_name?`"${config.from_name.replace(/["\r\n<>]/g,'')}" <${config.from_email}>`:config.from_email;const html=`<div dir="${input.locale==='ar'?'rtl':'ltr'}" lang="${input.locale}" style="font-family:Arial,Tahoma,sans-serif;max-width:600px;margin:auto;padding:32px;color:#142139"><h2 style="color:#2356ed">FOON.</h2><h3>${escapeHtml(subject)}</h3><p style="line-height:1.9;white-space:pre-wrap">${escapeHtml(body)}</p></div>`;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({from,to:[input.recipient],subject,text:body,html}),signal:AbortSignal.timeout(15000)});if(!response.ok){await database().prepare("UPDATE message_outbox SET status='rejected' WHERE id=?").bind(row.id).run();throw new ApiError(502,'EMAIL_PROVIDER_REJECTED');}await database().prepare("UPDATE message_outbox SET status='accepted' WHERE id=?").bind(row.id).run();return {id:row.id,status:'accepted'};
 }catch(error){if(!(error instanceof ApiError))await database().prepare("UPDATE message_outbox SET status='unknown' WHERE id=?").bind(row.id).run();throw error instanceof ApiError?error:new ApiError(502,'EMAIL_STATUS_UNKNOWN');}
}
// No cross-tenant or platform fallback is permitted for payment credentials.
export async function resolvePaymentSettings(tenantId?:string){const table=tenantId?'tenant_payment_settings':'platform_payment_settings';const key=tenantId?'tenant_id':'id';return database().prepare(`SELECT * FROM ${table} WHERE ${key}=? AND enabled=1`).bind(tenantId??'platform').first();}
