export const events=['welcome','order_confirmed','booking_confirmed','table_ready','subscription_updated','password_reset'] as const;
export type MessageEvent=typeof events[number];
export const locales=['ar','en','fr'] as const;
export const placeholders=['customer_name','store_name','service_number','service_type','amount','currency','date','plan_name','expires_at','reset_url'] as const;
const copy={
 ar:{welcome:['مرحبًا {{customer_name}}','أهلًا {{customer_name}}، نرحب بك في {{store_name}}.'],order_confirmed:['تأكيد الطلب {{service_number}}','{{customer_name}}، تم تأكيد طلبك لدى {{store_name}}. رقم الخدمة: {{service_number}}. النوع: {{service_type}}. المبلغ: {{amount}} {{currency}}. التاريخ: {{date}}.'],booking_confirmed:['تأكيد الحجز {{service_number}}','تم تأكيد حجزك لدى {{store_name}}، {{customer_name}}. رقم الحجز: {{service_number}}. الموعد: {{date}}.'],table_ready:['طاولتك جاهزة — {{store_name}}','{{customer_name}}، طاولتك جاهزة لدى {{store_name}}. رقم الخدمة: {{service_number}}.'],subscription_updated:['تحديث الباقة — {{store_name}}','تم تحديث باقة {{store_name}} إلى {{plan_name}}. المبلغ: {{amount}} {{currency}}. رقم العملية: {{service_number}}. التاريخ: {{date}}. انتهاء الباقة: {{expires_at}}.'],password_reset:['إعادة تعيين كلمة المرور','وصلنا طلب لإعادة تعيين كلمة مرور حسابك في FOON. افتح الرابط لإكمال العملية: {{reset_url}}\nينتهي الرابط خلال 30 دقيقة، ويمكن استخدامه مرة واحدة. إذا لم تطلب ذلك فتجاهل الرسالة.']},
 en:{welcome:['Welcome {{customer_name}}','Welcome to {{store_name}}, {{customer_name}}.'],order_confirmed:['Order confirmation {{service_number}}','{{customer_name}}, your order at {{store_name}} is confirmed. Reference: {{service_number}}. Service: {{service_type}}. Amount: {{amount}} {{currency}}. Date: {{date}}.'],booking_confirmed:['Booking confirmation {{service_number}}','Your booking at {{store_name}} is confirmed, {{customer_name}}. Reference: {{service_number}}. Date: {{date}}.'],table_ready:['Your table is ready — {{store_name}}','{{customer_name}}, your table at {{store_name}} is ready. Reference: {{service_number}}.'],subscription_updated:['Plan update — {{store_name}}','The plan for {{store_name}} was updated to {{plan_name}}. Amount: {{amount}} {{currency}}. Transaction: {{service_number}}. Date: {{date}}. Expiry: {{expires_at}}.'],password_reset:['Reset your password','We received a request to reset your FOON password. Open this link to continue: {{reset_url}}\nThis link expires in 30 minutes and can only be used once. If you did not request this, you can ignore this email.']},
 fr:{welcome:['Bienvenue {{customer_name}}','Bienvenue chez {{store_name}}, {{customer_name}}.'],order_confirmed:['Confirmation de commande {{service_number}}','{{customer_name}}, votre commande chez {{store_name}} est confirmée. Référence : {{service_number}}. Service : {{service_type}}. Montant : {{amount}} {{currency}}. Date : {{date}}.'],booking_confirmed:['Confirmation de réservation {{service_number}}','Votre réservation chez {{store_name}} est confirmée, {{customer_name}}. Référence : {{service_number}}. Date : {{date}}.'],table_ready:['Votre table est prête — {{store_name}}','{{customer_name}}, votre table chez {{store_name}} est prête. Référence : {{service_number}}.'],subscription_updated:['Mise à jour de l’offre — {{store_name}}','L’offre de {{store_name}} a été mise à jour : {{plan_name}}. Montant : {{amount}} {{currency}}. Transaction : {{service_number}}. Date : {{date}}. Expiration : {{expires_at}}.'],password_reset:['Réinitialiser votre mot de passe','Nous avons reçu une demande de réinitialisation de votre mot de passe FOON. Ouvrez ce lien pour continuer : {{reset_url}}\nCe lien expire dans 30 minutes et ne peut être utilisé qu’une fois. Si vous n’êtes pas à l’origine de cette demande, ignorez cet e-mail.']}}
export function defaultTemplate(event:MessageEvent,locale:keyof typeof copy){const [subject,body]=copy[locale][event];return {event,locale,subject,body,source:'default'};}
export function validPlaceholders(value:string){return [...value.matchAll(/{{\s*([^{}]+)\s*}}/g)].every(m=>(placeholders as readonly string[]).includes(m[1].trim()));}
