import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/db';
export class ApiError extends Error {constructor(public status:number,public code:string){super(code)}}
export async function actor(){const u=await getChatGPTUser();if(!u)throw new ApiError(401,'SIGN_IN_REQUIRED');const admin=Boolean(env.PLATFORM_ADMIN_EMAIL)&&u.email.toLowerCase()===env.PLATFORM_ADMIN_EMAIL!.toLowerCase();await database().prepare('INSERT INTO users (id,email,display_name,platform_role,created_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,display_name=excluded.display_name,platform_role=excluded.platform_role').bind(u.userId,u.email,u.displayName,admin?'platform_admin':'viewer',Date.now()).run();return {...u,admin};}
export async function authorize(tenantId?:string|null){const u=await actor();if(!tenantId){if(!u.admin)throw new ApiError(403,'FORBIDDEN');return u;}const tenant=await database().prepare('SELECT id FROM tenants WHERE id=?').bind(tenantId).first();if(!tenant)throw new ApiError(404,'NOT_FOUND');if(!u.admin){const m=await database().prepare('SELECT role FROM memberships WHERE tenant_id=? AND user_id=?').bind(tenantId,u.userId).first<{role:string}>();if(!m||!['owner','manager'].includes(m.role))throw new ApiError(403,'FORBIDDEN');}return u;}
export function sameOrigin(request:Request){if(!env.SITE_ORIGIN||request.headers.get('origin')!==env.SITE_ORIGIN)throw new ApiError(403,'INVALID_ORIGIN');}
export async function encryptSecret(value:string,scope:string){if(!env.INTEGRATION_ENCRYPTION_KEY)throw new ApiError(503,'ENCRYPTION_UNAVAILABLE');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(env.INTEGRATION_ENCRYPTION_KEY));const key=await crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(scope)},key,new TextEncoder().encode(value));return JSON.stringify({v:1,iv:btoa(String.fromCharCode(...iv)),data:btoa(String.fromCharCode(...new Uint8Array(cipher)))});}
export async function audit(actorId:string,action:string,tenantId:string|null=null){return database().prepare('INSERT INTO audit_events(id,actor_id,tenant_id,action,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),actorId,tenantId,action,Date.now()).run();}
export async function decryptSecret(value:string,scope:string){if(!env.INTEGRATION_ENCRYPTION_KEY)throw new ApiError(503,'ENCRYPTION_UNAVAILABLE');const payload=JSON.parse(value);if(payload.v!==1)throw new ApiError(503,'INVALID_SECRET');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(env.INTEGRATION_ENCRYPTION_KEY));const key=await crypto.subtle.importKey('raw',digest,'AES-GCM',false,['decrypt']);const iv=Uint8Array.from(atob(payload.iv),c=>c.charCodeAt(0));const cipher=Uint8Array.from(atob(payload.data),c=>c.charCodeAt(0));const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(scope)},key,cipher);return new TextDecoder().decode(clear);}
