'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {LockKeyhole,UserRound,Mail,ShieldCheck,Store} from 'lucide-react';
import {usePreferences} from './preferences';
export default function AccountRegistration(){
 const {locale}=usePreferences(),ar=locale==='ar',fr=locale==='fr',router=useRouter();
 const [data,setData]=useState({name:'',email:'',password:'',terms:false}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const words=ar?{title:'إنشاء حساب موحد',desc:'أنشئ حسابك أولًا، ثم اختر نوع نشاطك وأكمل إعداده.',name:'الاسم الكامل',email:'البريد الإلكتروني',password:'كلمة المرور (9 أحرف على الأقل)',terms:'أوافق على الشروط والأحكام وسياسة الخصوصية',submit:'إنشاء الحساب',busy:'جارٍ إنشاء الحساب…',login:'لديك حساب؟ تسجيل الدخول',exists:'هذا البريد مسجل مسبقًا.',failure:'تعذر إنشاء الحساب. حاول مرة أخرى.'}:fr?{title:'Créer un compte',desc:'Créez votre compte, puis choisissez et configurez votre activité.',name:'Nom complet',email:'E-mail',password:'Mot de passe (9 caractères minimum)',terms:'J’accepte les conditions et la politique de confidentialité',submit:'Créer le compte',busy:'Création…',login:'Déjà un compte ? Se connecter',exists:'Cet e-mail est déjà utilisé.',failure:'Impossible de créer le compte.'}:{title:'Create your account',desc:'Create one account first, then choose and set up your business.',name:'Full name',email:'Email',password:'Password (at least 9 characters)',terms:'I agree to the Terms and Privacy Policy',submit:'Create account',busy:'Creating account…',login:'Already have an account? Sign in',exists:'This email is already registered.',failure:'Could not create the account. Try again.'};
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/auth/account-register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'FAILED');router.replace(result.next||'/onboarding')}catch(error){setError(error instanceof Error&&error.message==='EMAIL_EXISTS'?words.exists:words.failure);setBusy(false)}}
 return <section className="legacy-register-shell"><aside className="legacy-register-story"><div><div className="legacy-register-brand"><span><Store/></span><div><strong>FOON</strong><small>BUSINESS OPERATING PLATFORM</small></div></div><div className="legacy-register-hero"><p><ShieldCheck/> {ar?'حساب واحد، وبداية واضحة':fr?'Un compte, un parcours clair':'One account, one clear starting point'}</p><h1>{words.title}</h1><span>{words.desc}</span></div></div></aside><main className="legacy-register-main"><form className="signup-card legacy-register-card" autoComplete="on" onSubmit={submit}><div className="signup-title"><UserRound/><div><span>01</span><h2>{words.title}</h2></div></div><label>{words.name}<input required minLength={2} maxLength={120} autoComplete="name" value={data.name} onChange={e=>setData(x=>({...x,name:e.target.value}))}/></label><label>{words.email}<input required type="email" maxLength={254} dir="ltr" autoComplete="email" value={data.email} onChange={e=>setData(x=>({...x,email:e.target.value}))}/></label><label>{words.password}<input required type="password" minLength={9} maxLength={128} autoComplete="new-password" value={data.password} onChange={e=>setData(x=>({...x,password:e.target.value}))}/></label><label className="signup-consent"><input required type="checkbox" checked={data.terms} onChange={e=>setData(x=>({...x,terms:e.target.checked}))}/><span>{words.terms}</span></label>{error&&<p role="alert" className="signup-error">{error}</p>}<div className="signup-actions"><button disabled={busy} className="primary-button" type="submit">{busy?words.busy:words.submit}</button></div><p className="signup-choice-note"><Link href="/login">{words.login}</Link></p></form></main></section>
}