'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Building2,Store,ArrowLeft,ShieldCheck} from 'lucide-react';
import {activities} from '@/lib/platform/activities';
import {usePreferences} from './preferences';
type Plan={id:string;name_ar:string;name_en:string;name_fr?:string;monthly_price:number|string;currency:string;description_ar?:string;description_en?:string;description_fr?:string;features?:{feature_id:string;label_ar:string;label_en:string;label_fr?:string;feature_limit?:number|null}[]};
const countries=[['SA','SAR','السعودية'],['AE','AED','الإمارات'],['KW','KWD','الكويت'],['BH','BHD','البحرين'],['QA','QAR','قطر'],['OM','OMR','عُمان']];
export default function BusinessOnboarding(){
 const {locale}=usePreferences(),ar=locale==='ar',fr=locale==='fr',router=useRouter();
 const [plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[data,setData]=useState({activityId:'restaurants',storeName:'',slug:'',countryCode:'SA',currency:'SAR',phone:'',city:'',planId:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const t=ar?{title:'اختر مسار نشاطك',desc:'حدد نوع النشاط لإعداد مساحة العمل المناسبة. يمكنك تغيير التفاصيل قبل الإكمال.',business:'اسم النشاط',slug:'الرابط المختصر بالإنجليزية',country:'الدولة',currency:'العملة',phone:'رقم الجوال',city:'المدينة',plan:'الباقة',submit:'إنشاء مساحة النشاط',busy:'جارٍ إعداد النشاط…',loading:'جارٍ تحميل الباقات…',exists:'رابط النشاط مستخدم مسبقًا.',unavailable:'الباقة غير متاحة.',failure:'تعذر إكمال إعداد النشاط.'}:fr?{title:'Choisissez votre activité',desc:'Sélectionnez le type d’activité pour configurer votre espace.',business:'Nom de l’activité',slug:'Adresse courte en anglais',country:'Pays',currency:'Devise',phone:'Téléphone',city:'Ville',plan:'Forfait',submit:'Créer mon espace',busy:'Configuration…',loading:'Chargement des forfaits…',exists:'Cette adresse est déjà utilisée.',unavailable:'Forfait indisponible.',failure:'Impossible de terminer la configuration.'}:{title:'Choose your business path',desc:'Select the type of business to set up its workspace.',business:'Business name',slug:'Short English URL',country:'Country',currency:'Currency',phone:'Phone number',city:'City',plan:'Plan',submit:'Create business workspace',busy:'Setting up…',loading:'Loading plans…',exists:'This address is already in use.',unavailable:'This plan is unavailable.',failure:'Could not finish setup.'};
 useEffect(()=>{let alive=true;fetch('/api/public/plans',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(j=>{if(alive){const available=Array.isArray(j.plans)?j.plans:[];setPlans(available);if(available.length)setData(x=>({...x,planId:available[0].id}))}}).catch(()=>{if(alive)setError(t.failure)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/auth/complete-onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'FAILED');router.replace(result.next||'/store')}catch(error){const code=error instanceof Error?error.message:'';setError(code==='SLUG_EXISTS'?t.exists:code==='PLAN_UNAVAILABLE'?t.unavailable:t.failure);setBusy(false)}}
 return <section className="legacy-register-shell"><aside className="legacy-register-story"><div><div className="legacy-register-brand"><span><Building2/></span><div><strong>FOON</strong><small>BUSINESS WORKSPACE</small></div></div><div className="legacy-register-hero"><p><ShieldCheck/> {ar?'الخطوة التالية':'NEXT STEP'}</p><h1>{t.title}</h1><span>{t.desc}</span></div></div></aside><main className="legacy-register-main"><form className="signup-card legacy-register-card" onSubmit={submit}><div className="signup-title"><Store/><div><span>02</span><h2>{t.title}</h2></div></div><div className="onboarding-activities">{activities.map(activity=><button type="button" key={activity.id} className={'signup-account-choice'+(data.activityId===activity.id?' active':'')} onClick={()=>setData(x=>({...x,activityId:activity.id}))}><Store/><div><strong>{activity.name[locale]}</strong><span>{activity.engine}</span></div></button>)}</div><label>{t.business}<input required minLength={2} maxLength={120} autoComplete="organization" value={data.storeName} onChange={e=>setData(x=>({...x,storeName:e.target.value,slug:x.slug||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)}))}/></label><label>{t.slug}<input required pattern="[a-z][a-z0-9-]{2,59}" maxLength={60} dir="ltr" value={data.slug} onChange={e=>setData(x=>({...x,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')}))}/></label><div className="onboarding-fields"><label>{t.country}<select value={data.countryCode} onChange={e=>{const c=countries.find(x=>x[0]===e.target.value);setData(x=>({...x,countryCode:e.target.value,currency:c?.[1]||'SAR'}))}}>{countries.map(c=><option key={c[0]} value={c[0]}>{c[2]}</option>)}</select></label><label>{t.currency}<input readOnly value={data.currency}/></label><label>{t.city}<input required minLength={2} maxLength={120} value={data.city} onChange={e=>setData(x=>({...x,city:e.target.value}))}/></label><label>{t.phone}<input required type="tel" minLength={7} maxLength={32} dir="ltr" value={data.phone} onChange={e=>setData(x=>({...x,phone:e.target.value}))}/></label></div><label>{t.plan}{loading?<span>{t.loading}</span>:plans.length===0?<span>{t.failure}</span>:<select required value={data.planId} onChange={e=>setData(x=>({...x,planId:e.target.value}))}>{plans.map(p=><option key={p.id} value={p.id}>{ar?p.name_ar:fr?(p.name_fr||p.name_en):p.name_en} · {Number(p.monthly_price)===0?(ar?'مجانية':'Free'):`${Number(p.monthly_price).toFixed(2)} ${p.currency}/mo`}</option>)}</select>}</label>{error&&<p role="alert" className="signup-error">{error}</p>}<div className="signup-actions"><button type="submit" disabled={busy||loading||plans.length===0} className="primary-button">{busy?t.busy:t.submit}<ArrowLeft size={16}/></button></div></form></main></section>
}