'use client';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Store,Mail,Wallet,ShieldCheck,Layers3,Users,FileText,Activity,Save,Plus,Globe2,LayoutDashboard,Settings2,TrendingUp,ArrowUpRight,Sparkles,Zap} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter} from '@/components/ui/sidebar';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {usePreferences} from './preferences';
import {activities} from '@/lib/platform/activities';
import {events,locales,placeholders} from '@/lib/platform/messages';
type Tenant={id:string;name:string;slug:string;activity_id:string;country_code:string;currency:string;status:string};
type Template={event:string;locale:string;subject:string;body:string;source:string};
type WireResponse={error?:string;stores:Tenant[];summary:Record<string,number>;templates:Template[];email:Config|null;payment:Config|null;id?:string;settings:Record<string,string>};
type Config={provider:string;from_email?:string;from_name?:string;public_key?:string;enabled:number;mode?:string;hasSecret:boolean};
async function api(action:string,tenantId?:string){const url=new URL('/api/control',window.location.origin);url.searchParams.set('action',action);if(tenantId)url.searchParams.set('tenantId',tenantId);const r=await fetch(url,{cache:'no-store'});const d=await r.json() as WireResponse;if(!r.ok)throw new Error(d.error);return d;}
async function post(data:unknown){const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json() as WireResponse;if(!r.ok)throw new Error(d.error);return d;}
export default function ControlPanel({storeMode=false}:{storeMode?:boolean}){
 const params=useSearchParams();const {t,locale}=usePreferences();const [tab,setTab]=useState('overview');const [stores,setStores]=useState<Tenant[]>([]);const [tenantId,setTenantId]=useState('');const [summary,setSummary]=useState<Record<string,number>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [version,setVersion]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);setError('');Promise.all([api('stores'),...(!storeMode?[api('summary')]:[])]).then(([d,s])=>{if(!alive)return;setStores(d.stores);if(s)setSummary(s.summary);if(storeMode)setTenantId(prev=>d.stores.some((x:Tenant)=>x.id===prev)?prev:(d.stores.find((x:Tenant)=>x.id===params.get('tenant'))?.id??d.stores[0]?.id??''));}).catch(()=>{if(alive)setError(t.loadError)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[storeMode,version,t.loadError]);
 const selected=stores.find(s=>s.id===tenantId);
 return <div className="control-panel"><section className="control-heading"><div><p className="eyebrow"><ShieldCheck size={17}/>{t.protected}</p><h1>{storeMode?t.storeWorkspace:t.dashboard}</h1><p>{storeMode?selected?.name:t.sharedRules}</p></div><div className="heading-actions">{storeMode?<Link className="quiet-button" href="/admin">{t.admin}</Link>:<Link className="quiet-button" href="/store">{t.storeWorkspace}</Link>}<a className="quiet-button" href="/logout" target="_top">{t.signOut}</a></div></section>
 {loading?<p className="feedback">{t.loading}</p>:error?<div className="error-state"><p>{error}</p><button className="primary-button" onClick={()=>setVersion(v=>v+1)}>{t.retry}</button></div>:<>
 {storeMode&&stores.length>0&&<div className="scope-select"><label>{t.selectedStore}</label><Picker value={tenantId} onChange={setTenantId} options={stores.map(s=>({value:s.id,label:s.name}))}/><span className="scope-chip">{t.independent}</span></div>}
 {storeMode&&!stores.length?<NoStores/>:<Tabs value={tab} onValueChange={setTab} orientation="vertical" dir={locale==='ar'?'rtl':'ltr'} className="admin-workspace"><SidebarProvider className="workspace-provider"><Sidebar collapsible="none" side={locale==='ar'?'right':'left'} className="workspace-sidebar"><SidebarHeader className="workspace-sidebar-header"><span className="sidebar-brand">FOON<span>.</span></span><span>{storeMode?t.storeWorkspace:t.management}</span></SidebarHeader><SidebarContent><TabsList className="control-tabs" aria-label={t.management}><TabsTrigger value="overview"><LayoutDashboard size={19}/>{t.overview}</TabsTrigger>{!storeMode&&<TabsTrigger value="stores"><Store size={19}/>{t.stores}</TabsTrigger>}<TabsTrigger value="messages"><Mail size={19}/>{t.messageCenter}</TabsTrigger><TabsTrigger value="integrations"><Globe2 size={19}/>{t.integrations}</TabsTrigger><TabsTrigger value="payments"><Wallet size={19}/>{t.paymentGateway}</TabsTrigger>{!storeMode&&<TabsTrigger value="settings"><Settings2 size={19}/>{t.platformSettings}</TabsTrigger>}</TabsList></SidebarContent><SidebarFooter className="workspace-sidebar-footer"><ShieldCheck size={21}/><span>{t.protected}</span></SidebarFooter></Sidebar><div className="workspace-content">
 <TabsContent value="overview"><div className="command-hero"><div><span className="command-kicker"><Sparkles size={15}/> FOON COMMAND CENTER</span><h2>{storeMode?(selected?.name??t.storeWorkspace):t.dashboard}</h2><p>{storeMode?t.storeWorkspace:t.sharedRules}</p></div><div className="command-health"><span className="health-dot"/><div><strong>LIVE</strong><small>{t.protected}</small></div></div></div>{!storeMode&&<div className="metrics">{[[Store,t.stores,summary.stores],[Users,t.accountsCount,summary.accounts],[FileText,t.savedTemplates,summary.saved_templates],[Activity,t.auditCount,summary.audit_events]].map(([Icon,label,count],i)=>{const I=Icon as typeof Store;return <div className="metric" key={i}><I size={22}/><span>{label as string}</span><strong>{count as number??0}</strong><small>{t.liveRecords}</small></div>})}</div>}<div className="ops-grid"><section className="ops-card ops-primary"><div className="ops-card-head"><div><span className="command-kicker"><TrendingUp size={14}/> OPERATIONS</span><h3>{t.policyTitle}</h3></div><span className="pulse-badge"><Zap size={13}/> LIVE</span></div><p>{t.sharedRulesDesc}</p><div className="ops-bars"><span style={{width:'88%'}}/><span style={{width:'64%'}}/><span style={{width:'76%'}}/></div></section><section className="ops-card"><div className="ops-card-head"><div><span className="command-kicker">QUICK ACTIONS</span><h3>{t.management}</h3></div><ArrowUpRight size={20}/></div><div className="quick-actions"><button onClick={()=>setTab('messages')}><Mail/><span>{t.messageCenter}</span></button><button onClick={()=>setTab('payments')}><Wallet/><span>{t.paymentGateway}</span></button>{!storeMode&&<button onClick={()=>setTab('stores')}><Store/><span>{t.stores}</span></button>}</div></section></div><div className="policy-grid"><button onClick={()=>setTab('messages')}><Mail/><span className="scope-chip">{t.central}</span><h3>{t.messageCenter}</h3><p>{t.inheritedNote}</p></button><button onClick={()=>setTab('payments')}><Wallet/><span className="scope-chip">{t.independent}</span><h3>{t.isolatedPayment}</h3><p>{t.noPaymentInheritance}</p></button></div></TabsContent>
 {!storeMode&&<TabsContent value="stores"><StoreManager stores={stores} refresh={()=>setVersion(v=>v+1)}/></TabsContent>}
 <TabsContent value="messages"><MessageEditor tenantId={storeMode?tenantId:undefined}/></TabsContent>
 <TabsContent value="integrations"><IntegrationForm key={'email'+tenantId} kind="email" tenantId={storeMode?tenantId:undefined}/></TabsContent>
 <TabsContent value="payments"><IntegrationForm key={'payment'+tenantId} kind="payment" tenantId={storeMode?tenantId:undefined}/></TabsContent>
 <TabsContent value="settings">{!storeMode&&<PlatformSettings/>}</TabsContent></div></SidebarProvider></Tabs>}
 </>}
 </div>
}
function Picker({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){const {locale}=usePreferences();return <Select value={value} onValueChange={onChange} dir={locale==='ar'?'rtl':'ltr'}><SelectTrigger className="field-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function NoStores(){const {t}=usePreferences();return <Empty className="empty-panel"><EmptyHeader><EmptyMedia variant="icon"><Store/></EmptyMedia><EmptyTitle>{t.noStores}</EmptyTitle><EmptyDescription>{t.createFirst}</EmptyDescription></EmptyHeader></Empty>}
function errorMessage(error:unknown,t:ReturnType<typeof usePreferences>['t']){const code=error instanceof Error?error.message:'';return ({SLUG_EXISTS:t.slugExists,INVALID_PLACEHOLDER:t.invalidPlaceholder,SECRET_REQUIRED:t.secretRequired,SENDER_REQUIRED:t.senderRequired,CUSTOM_EMAIL_REQUIRED:t.customRequired,EMAIL_NOT_CONFIGURED:t.emailMissing,EMAIL_PROVIDER_REJECTED:t.providerRejected,EMAIL_STATUS_UNKNOWN:t.emailUnknown,TEST_LIMIT:t.testLimit} as Record<string,string>)[code]??t.saveError}
function StoreManager({stores,refresh}:{stores:Tenant[];refresh:()=>void}){const {t,locale}=usePreferences();const [name,setName]=useState(''),[slug,setSlug]=useState(''),[country,setCountry]=useState('SA'),[currency,setCurrency]=useState('SAR'),[activity,setActivity]=useState('restaurants');const [busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[failed,setFailed]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setFeedback('');try{await post({action:'create_store',name,slug,activityId:activity,countryCode:country,currency});setName('');setSlug('');setFeedback(t.saved);setFailed(false);refresh()}catch(e){setFeedback(errorMessage(e,t));setFailed(true)}finally{setBusy(false)}}
 return <div className="stores-layout"><form className="form-card" onSubmit={submit}><h2><Plus size={20}/>{t.createStore}</h2><label>{t.storeName}<Input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t.slug}<Input required dir="ltr" pattern="[a-z][a-z0-9-]{2,59}" placeholder="my-store" value={slug} onChange={e=>setSlug(e.target.value)}/></label><label>{t.activity}<Picker value={activity} onChange={setActivity} options={activities.map(a=>({value:a.id,label:a.name[locale]}))}/></label><div className="form-pair"><label>{t.country}<Input required dir="ltr" pattern="[A-Z]{2}" maxLength={2} value={country} onChange={e=>setCountry(e.target.value.toUpperCase())}/><small>{t.countryHint}</small></label><label>{t.currencyLabel}<Input required dir="ltr" pattern="[A-Z]{3}" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/><small>{t.currencyHint}</small></label></div><button className="primary-button" disabled={busy}>{busy?t.saving:t.createStore}</button><p role="status" className={failed?'error-text':'success-text'}>{feedback}</p></form><div className="records-card"><h2>{t.stores}</h2>{!stores.length?<NoStores/>:<Table><TableHeader><TableRow><TableHead>{t.storeName}</TableHead><TableHead>{t.activity}</TableHead><TableHead>{t.country}</TableHead><TableHead>{t.statusLabel}</TableHead><TableHead>{t.openSettings}</TableHead></TableRow></TableHeader><TableBody>{stores.map(s=><TableRow key={s.id}><TableCell><div className="store-identity"><span className="store-avatar">{s.name.trim().slice(0,1)}</span><div><strong>{s.name}</strong><small className="record-meta" dir="ltr">/{s.slug}</small></div></div></TableCell><TableCell>{activities.find(a=>a.id===s.activity_id)?.name[locale]}</TableCell><TableCell><span className="country-code">{s.country_code}</span><small className="record-meta">{s.currency}</small></TableCell><TableCell><span className="store-status">{s.status==='draft'?t.draft:s.status==='active'?t.activeStatus:t.suspendedStatus}</span></TableCell><TableCell><Link className="text-link" href={'/store?tenant='+s.id}>{t.openSettings}</Link></TableCell></TableRow>)}</TableBody></Table>}</div></div>
}
function MessageEditor({tenantId}:{tenantId?:string}){const {t,locale}=usePreferences();const [templates,setTemplates]=useState<Template[]>([]);const [event,setEvent]=useState('welcome'),[lang,setLang]=useState<string>(locale);const [subject,setSubject]=useState(''),[body,setBody]=useState(''),[allowed,setAllowed]=useState(!tenantId);const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[failed,setFailed]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);Promise.all([api('templates',tenantId),...(tenantId?[api('integrations',tenantId)]:[])]).then(([d,c])=>{if(!alive)return;setTemplates(d.templates);setAllowed(!tenantId||c?.email?.mode==='custom');}).catch(()=>{if(alive){setFeedback(t.loadError);setFailed(true)}}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[tenantId,version,t.loadError]);
 useEffect(()=>{const current=templates.find(x=>x.event===event&&x.locale===lang);setSubject(current?.subject??'');setBody(current?.body??'');setFeedback('');},[templates,event,lang]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setFeedback('');try{await post({action:'save_template',tenantId,event,locale:lang,subject,body});setTemplates(prev=>prev.map(x=>x.event===event&&x.locale===lang?{...x,subject,body}:x));setFeedback(t.saved);setFailed(false)}catch(e){setFeedback(errorMessage(e,t));setFailed(true)}finally{setBusy(false)}}
 return <section><div className="section-heading"><div><h2>{t.messageCenter}</h2><p>{tenantId?t.storeScope:t.platformScope}</p></div><span className="scope-chip">{tenantId&&allowed?t.independent:t.central}</span></div>{loading?<p>{t.loading}</p>:!templates.length?<div className="error-state"><p>{t.loadError}</p><button onClick={()=>setVersion(v=>v+1)} className="quiet-button">{t.retry}</button></div>:<>{!allowed&&<p className="info-note">{t.inheritedNote}</p>}<div className="message-layout"><form className="form-card" onSubmit={save}><div className="form-pair"><label>{t.eventLabel}<Picker value={event} onChange={setEvent} options={events.filter(e=>!tenantId||e!=='subscription_updated').map(e=>({value:e,label:t[e]}))}/></label><label>{t.language}<Picker value={lang} onChange={setLang} options={[{value:'ar',label:'العربية'},{value:'en',label:'English'},{value:'fr',label:'Français'}]}/></label></div><label>{t.subject}<Input required maxLength={300} dir={lang==='ar'?'rtl':'ltr'} value={subject} disabled={!allowed} onChange={e=>setSubject(e.target.value)}/></label><label>{t.bodyLabel}<Textarea required maxLength={12000} rows={8} dir={lang==='ar'?'rtl':'ltr'} value={body} disabled={!allowed} onChange={e=>setBody(e.target.value)}/></label><div className="variable-list"><span>{t.variables}</span>{placeholders.map(v=><code key={v} dir="ltr">{'{{'+v+'}}'}</code>)}</div><button disabled={busy||!allowed} className="primary-button"><Save size={17}/>{busy?t.saving:t.save}</button><p role="status" className={failed?'error-text':'success-text'}>{feedback}</p></form><div className="message-preview"><div className="preview-toolbar"><Mail size={18}/>{t.previewMessage}</div><div className="preview-paper" dir={lang==='ar'?'rtl':'ltr'}><span className="mail-brand">FOON.</span><h3>{subject}</h3><p>{body}</p></div></div></div></>}</section>
}
function IntegrationForm({kind,tenantId}:{kind:'email'|'payment';tenantId?:string}){const {t}=usePreferences();const [config,setConfig]=useState<Config|null>(null),[provider,setProvider]=useState(kind==='email'?'resend':'moyasar'),[mode,setMode]=useState('platform'),[fromEmail,setFromEmail]=useState(''),[fromName,setFromName]=useState(''),[publicKey,setPublicKey]=useState(''),[secret,setSecret]=useState(''),[enabled,setEnabled]=useState(false);const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[failed,setFailed]=useState(false),[loadFailed,setLoadFailed]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);setLoadFailed(false);api('integrations',tenantId).then(d=>{if(!alive)return;const c=d[kind];setConfig(c);setProvider(c?.provider??(kind==='email'?'resend':'moyasar'));setMode(c?.mode??'platform');setFromEmail(c?.from_email??'');setFromName(c?.from_name??'');setPublicKey(c?.public_key??'');setEnabled(Boolean(c?.enabled));setSecret('');}).catch(()=>{if(alive)setLoadFailed(true)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[kind,tenantId,version]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setFeedback('');try{await post({action:'save_integration',kind,tenantId,provider,mode,fromEmail,fromName,publicKey,secret,enabled});setSecret('');setFeedback(t.saved);setFailed(false);setVersion(v=>v+1)}catch(e){setFeedback(errorMessage(e,t));setFailed(true)}finally{setBusy(false)}}
 async function sendTest(){setBusy(true);setFeedback('');try{await post({action:'send_test',tenantId,locale:document.documentElement.lang,requestId:crypto.randomUUID()});setFeedback(t.testSent);setFailed(false)}catch(e){setFeedback(errorMessage(e,t));setFailed(true)}finally{setBusy(false)}}
 const inherited=kind==='email'&&tenantId&&mode==='platform';
 return <section><div className="section-heading"><div><h2>{kind==='email'?t.integrations:t.paymentGateway}</h2><p>{tenantId?t.storeScope:t.platformScope}</p></div><span className="scope-chip">{config?t.configured:t.noCredentials}</span></div>{loading?<p>{t.loading}</p>:loadFailed?<div className="error-state"><p>{t.loadError}</p><button onClick={()=>setVersion(v=>v+1)} className="quiet-button">{t.retry}</button></div>:<div className="integration-layout"><form className="form-card" onSubmit={save}>{kind==='email'&&tenantId&&<label>{t.emailMode}<Picker value={mode} onChange={setMode} options={[{value:'platform',label:t.sharedEmail},{value:'custom',label:t.customEmail}]}/></label>}{inherited?<p className="info-note">{t.inheritedNote}</p>:<><label>{t.provider}<Picker value={provider} onChange={v=>{setProvider(v);setSecret('')}} options={kind==='email'?[{value:'resend',label:'Resend'}]:[{value:'moyasar',label:'Moyasar'},{value:'stripe',label:'Stripe'}]}/></label>{kind==='email'?<><label>{t.senderEmail}<Input type="email" dir="ltr" value={fromEmail} onChange={e=>setFromEmail(e.target.value)}/></label><label>{t.senderName}<Input maxLength={120} value={fromName} onChange={e=>setFromName(e.target.value)}/></label></>:<label>{t.publicKey}<Input dir="ltr" value={publicKey} maxLength={500} autoComplete="off" onChange={e=>setPublicKey(e.target.value)}/></label>}<label>{t.secretKey}<Input type="password" dir="ltr" value={secret} maxLength={2000} autoComplete="new-password" onChange={e=>setSecret(e.target.value)}/>{config?.hasSecret&&config.provider===provider&&<small>{t.keySaved}</small>}</label><label className="switch-field"><span>{t.enabledConfig}</span><Switch checked={enabled} onCheckedChange={setEnabled}/></label></>}<button className="primary-button" disabled={busy}><Save size={17}/>{busy?t.saving:t.save}</button>{kind==='email'&&<button type="button" className="quiet-button" disabled={busy} onClick={sendTest}>{t.sendTest}</button>}<p role="status" className={failed?'error-text':'success-text'}>{feedback}</p></form><aside className="integration-note"><span className="integration-emblem">{kind==='email'?<Mail size={35}/>:<Wallet size={35}/>}</span><h3>{kind==='email'?(tenantId?t.emailMode:t.messageCenter):t.isolatedPayment}</h3><p>{kind==='email'?t.emailSetupNote:t.paymentSetupNote}</p>{kind==='payment'&&<p className="note-rule"><ShieldCheck size={18}/>{t.noPaymentInheritance}</p>}</aside></div>}</section>
}

function PlatformSettings(){const {t}=usePreferences();const [name,setName]=useState('FOON'),[email,setEmail]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(false),[feedback,setFeedback]=useState(''),[version,setVersion]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);setError(false);api('settings').then(d=>{if(alive){setName(d.settings.site_name??'FOON');setEmail(d.settings.support_email??'')}}).catch(()=>{if(alive)setError(true)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[version]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await post({action:'save_settings',siteName:name,supportEmail:email});setFeedback(t.saved)}catch(e){setFeedback(errorMessage(e,t))}finally{setBusy(false)}}
 return <section><div className="section-heading"><div><h2>{t.platformSettings}</h2><p>{t.settingsNote}</p></div></div>{loading?<p>{t.loading}</p>:error?<div className="error-state"><p>{t.loadError}</p><button className="quiet-button" onClick={()=>setVersion(v=>v+1)}>{t.retry}</button></div>:<form className="form-card" onSubmit={save}><label>{t.siteName}<Input required minLength={2} maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t.supportEmail}<Input type="email" dir="ltr" value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy} className="primary-button">{busy?t.saving:t.save}</button><p role="status">{feedback}</p></form>}</section>
}
