'use client';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Check,Eye,EyeOff,LockKeyhole,Mail,ShieldCheck,UtensilsCrossed} from 'lucide-react';
import {usePreferences} from './preferences';
const words={
 ar:{eyebrow:'مساحتك التشغيلية تبدأ من هنا',hero:'أدر نشاطك بثقة أكبر.',desc:'وصول آمن إلى متجرك أو مطعمك أو نشاطك، مع الإدارة والطلبات والعملاء والفروع والتقارير في مساحة واحدة.',f1:'مساحة عمل موحدة لكل أنواع الأنشطة والفرق',f2:'بياناتك محمية بصلاحيات واضحة',f3:'متابعة مباشرة من أي جهاز',title:'مرحبًا بعودتك',sub:'سجل الدخول للوصول إلى مساحة عملك المتكاملة.',email:'البريد الإلكتروني',password:'كلمة المرور',forgot:'نسيت كلمة المرور؟',submit:'تسجيل الدخول',busy:'جارٍ تسجيل الدخول…',error:'تعذّر الدخول. تحقق من البيانات أو حاول لاحقًا.',register:'إنشاء حساب جديد',restaurant:'تسجيل مطعم',newStore:'ليس لديك حساب؟'},
 en:{eyebrow:'Your operations workspace starts here',hero:'Run your business with more confidence.',desc:'Secure access to your store, restaurant or business with operations, orders, customers, branches and reports in one workspace.',f1:'One workspace for every business type and team',f2:'Your data protected by clear permissions',f3:'Live follow-up from any device',title:'Welcome back',sub:'Sign in to access your complete business workspace.',email:'Email',password:'Password',forgot:'Forgot password?',submit:'Sign in',busy:'Signing in…',error:'Unable to sign in. Check your details or try later.',register:'Create account',restaurant:'Register restaurant',newStore:'No account yet?'},
 fr:{eyebrow:'Votre espace de travail commence ici',hero:'Gérez votre activité avec plus de confiance.',desc:'Accès sécurisé à votre boutique, restaurant ou activité avec opérations, commandes, clients, sites et rapports dans un seul espace.',f1:'Un espace unifié pour tous les types d’activité',f2:'Vos données protégées par des permissions claires',f3:'Suivi en direct depuis n’importe quel appareil',title:'Bon retour',sub:'Connectez-vous pour accéder à votre espace de travail.',email:'E-mail',password:'Mot de passe',forgot:'Mot de passe oublié ?',submit:'Se connecter',busy:'Connexion…',error:'Connexion impossible. Vérifiez vos informations ou réessayez.',register:'Créer un compte',restaurant:'Inscrire un restaurant',newStore:'Pas encore de compte ?'}
};
export default function LoginForm(){const {locale}=usePreferences();const t=words[locale];const params=useSearchParams();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [show,setShow]=useState(false);return <section className="legacy-login-shell"><aside className="legacy-login-story"><Link href="/" className="legacy-login-brand"><span><UtensilsCrossed/></span><div><strong>FOON</strong><small>BUSINESS OPERATING PLATFORM</small></div></Link><div className="legacy-login-copy"><p>{t.eyebrow}</p><h1>{t.hero}</h1><span>{t.desc}</span><div>{[t.f1,t.f2,t.f3].map(x=><p key={x}><Check/>{x}</p>)}</div></div><small className="legacy-login-secure"><ShieldCheck/> FOON 2026</small></aside><main className="legacy-login-main"><div className="legacy-login-card"><div className="legacy-login-title"><span><LockKeyhole/></span><div><h1>{t.title}</h1><p>{t.sub}</p></div></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password'),next:params.get('next')})});const result=await r.json();if(!r.ok)throw Error();window.location.assign(result.next);}catch{setError(t.error);setBusy(false);}}}><label>{t.email}<span className="legacy-login-input"><Mail/><input name="email" type="email" autoComplete="username" required maxLength={254} dir="ltr"/></span></label><label>{t.password}<span className="legacy-login-input"><LockKeyhole/><input name="password" type={show?'text':'password'} autoComplete="current-password" required maxLength={256}/><button type="button" onClick={()=>setShow(v=>!v)} aria-label="Toggle password">{show?<EyeOff/>:<Eye/>}</button></span></label><div className="legacy-login-forgot"><Link href="/forgot-password">{t.forgot}</Link></div>{error&&<p className="signup-error" role="alert">{error}</p>}<button className="primary-button legacy-login-submit" type="submit" disabled={busy}>{busy?t.busy:t.submit}</button></form><div className="legacy-login-register"><span>{t.newStore}</span><Link href="/register/restaurant">{t.restaurant}</Link><Link href="/register/store">{t.register}</Link></div></div></main></section>}
