'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Bell,Check,X} from 'lucide-react';

type N={user_notification_id:string;id:string;event:string;title:string;body:string;priority:string;channels:string;trace_id:string;created_at:number;read_at:number|null;sound:number;sound_key:string;volume:number;repeat_count:number};
function beep(volume:number,repeat:number){try{const A=window.AudioContext||((window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext);const ctx=new A();if(ctx.state==='suspended')void ctx.resume();let i=0;const play=()=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;g.gain.value=Math.max(0,Math.min(1,volume/100))*.12;o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.16);if(++i<Math.min(3,repeat))setTimeout(play,260)};play()}catch{}}
export default function NotificationBell(){const [rows,setRows]=useState<N[]>([]),[open,setOpen]=useState(false),seen=useRef(new Set<string>()),ready=useRef(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/notifications',{cache:'no-store'});if(!r.ok)return;const d=await r.json(),next:N[]=d.notifications||[];if(ready.current){const fresh=next.filter(n=>!seen.current.has(n.id));for(const n of fresh)if(Number(n.sound)&&n.channels.includes('sound'))beep(Number(n.volume)||80,Number(n.repeat_count)||1)}next.forEach(n=>seen.current.add(n.id));ready.current=true;setRows(next)}catch{}},[]);
 useEffect(()=>{load();const id=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},5000);const onFocus=()=>void load();window.addEventListener('focus',onFocus);return()=>{window.clearInterval(id);window.removeEventListener('focus',onFocus)}},[load]);
 async function act(n:N,action:'read'|'dismiss'){await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:n.user_notification_id,action})});await load()}
 const unread=rows.filter(n=>!n.read_at).length;
 return <div style={{position:'relative'}}><button className="command-icon" onClick={()=>setOpen(v=>!v)} aria-label="الإشعارات" title="الإشعارات"><Bell size={17}/>{unread>0&&<b style={{position:'absolute',insetInlineEnd:-5,top:-6,minWidth:18,height:18,borderRadius:10,display:'grid',placeItems:'center',fontSize:10,background:'var(--primary,#f97316)',color:'#fff'}}>{unread>99?'99+':unread}</b>}</button>{open&&<div className="ops-card" style={{position:'absolute',zIndex:80,insetInlineEnd:0,top:'calc(100% + 10px)',width:'min(380px,calc(100vw - 28px))',maxHeight:'min(560px,70vh)',overflow:'auto',padding:12,boxShadow:'0 18px 50px rgba(0,0,0,.18)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,marginBottom:10}}><strong>الإشعارات</strong><small>{unread} غير مقروء</small></div>{rows.length===0?<p className="feedback">لا توجد إشعارات جديدة</p>:<div style={{display:'grid',gap:8}}>{rows.map(n=><div key={n.user_notification_id} className="activity-strip" style={{opacity:n.read_at?.85:1}}><div style={{minWidth:0}}><strong>{n.title}</strong><small style={{display:'block',whiteSpace:'normal'}}>{n.body}</small><small>{new Date(n.created_at).toLocaleString()} · {n.trace_id}</small></div><div style={{display:'flex',gap:4}}>{!n.read_at&&<button className="quiet-button" onClick={()=>act(n,'read')} aria-label="تمت القراءة"><Check size={14}/></button>}<button className="quiet-button" onClick={()=>act(n,'dismiss')} aria-label="إخفاء"><X size={14}/></button></div></div>)}</div>}</div>}</div>}
