'use client';
import Link from 'next/link';
import {useState} from 'react';
import {LockKeyhole,ArrowLeft} from 'lucide-react';
import {usePreferences} from './preferences';
const words={
 ar:{title:'تعيين كلمة مرور جديدة',subtitle:'اختر كلمة مرور من 9 أحرف على الأقل.',password:'كلمة المرور الجديدة',confirm:'تأكيد كلمة المرور',submit:'حفظ كلمة المرور',busy:'جارٍ الحفظ…',mismatch:'كلمتا المرور غير متطابقتين.',invalid:'الرابط غير صالح أو انتهت صلاحيته. اطلب رابطًا جديدًا.',success:'تم تحديث كلمة المرور. سجّل الدخول من جديد.',back:'تسجيل الدخول',error:'تعذر تحديث كلمة المرور. اطلب رابطًا جديدًا.'},
 en:{title:'Choose a new password',subtitle:'Use at least 9 characters.',password:'New password',confirm:'Confirm password',submit:'Save password',busy:'Saving…',mismatch:'The passwords do not match.',invalid:'This link is invalid or expired. Request a new one.',success:'Password updated. Sign in again.',back:'Sign in',error:'Could not update the password. Request a new link.'},
 fr:{title:'Choisir un nouveau mot de passe',subtitle:'Utilisez au moins 9 caractères.',password:'Nouveau mot de passe',confirm:'Confirmer le mot de passe',submit:'Enregistrer',busy:'Enregistrement…',mismatch:'Les mots de passe ne correspondent pas.',invalid:'Ce lien est invalide ou expiré. Demandez-en un nouveau.',success:'Mot de passe mis à jour. Connectez-vous à nouveau.',back:'Se connecter',error:'Impossible de modifier le mot de passe. Demandez un nouveau lien.'}
};
export default function ResetPasswordForm({token}:{token:string}){const {locale}=usePreferences();const t=words[locale];const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage('');if(password!==confirm){setMessage(t.mismatch);return}setBusy(true);try{const r=await fetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})});const result=await r.json();if(!r.ok){if(result.error==='RESET_LINK_INVALID'){setMessage(t.invalid);return}throw Error()}setDone(true);setMessage(t.success)}catch{setMessage(t.error)}finally{setBusy(false)}}
 return <main className="legacy-login-main"><section className="legacy-login-card"><div className="legacy-login-title"><span><LockKeyhole/></span><div><h1>{t.title}</h1><p>{t.subtitle}</p></div></div>{done?<p className="success-text" role="status">{message}</p>:!token?<p className="signup-error" role="alert">{t.invalid}</p>:<form onSubmit={submit}><label>{t.password}<span className="legacy-login-input"><LockKeyhole/><input type="password" autoComplete="new-password" minLength={9} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></span></label><label>{t.confirm}<span className="legacy-login-input"><LockKeyhole/><input type="password" autoComplete="new-password" minLength={9} maxLength={128} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></span></label>{message&&<p className={message===t.success?'success-text':'signup-error'} role="status">{message}</p>}<button className="primary-button legacy-login-submit" disabled={busy}>{busy?t.busy:t.submit}</button></form>}<div className="legacy-login-register"><Link href="/login"><ArrowLeft size={16}/>{t.back}</Link></div></section></main>
}
