'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {WalletCards,ShieldCheck,Clock3,CheckCircle2,RefreshCw} from 'lucide-react';
import {usePreferences} from './preferences';
type Plan={id:string;name_ar:string;name_en:string;monthly_price:number|string;yearly_price?:number|string;currency:string;description_ar?:string;description_en?:string};
type SetupData={pendingSubscription?:{id:string;plan_id:string;billing_cycle:string;status:string;starts_at:number|null;expires_at:number|null;name_ar:string;name_en:string;monthly_price:number|string;yearly_price:number|string|null;currency:string}|null;subscription?:{id:string;plan_id:string;billing_cycle:string;status:string;name_ar:string;name_en:string;monthly_price:number|string;yearly_price:number|string|null;currency:string}|null;features?:Array<{feature_id:string;label_ar:string;label_en:string;feature_limit:number|null}>;payments?:Array<{id:string;status:string;transaction_reference:string}>;plans?:Plan[]};
export default function SubscriptionSetup(){
 const q=useSearchParams(),tenantId=q.get('tenant')||'',{locale}=usePreferences();
 const [data,setData]=useState<SetupData|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[ref,setRef]=useState(''),[receipt,setReceipt]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[planId,setPlanId]=useState(''),[billingCycle,setBillingCycle]=useState<'monthly'|'yearly'>('monthly');
 const load=useCallback(async()=>{if(!tenantId){setLoading(false);setLoadError('رابط المطعم غير مكتمل. ارجع إلى لوحة المطعم وافتح صفحة الباقة منها.');return}setLoading(true);setLoadError('');try{const r=await fetch('/api/subscription?tenantId='+encodeURIComponent(tenantId),{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'SERVICE_UNAVAILABLE');setData(j);setPlanId(j.pendingSubscription?.plan_id||j.subscription?.plan_id||j.plans?.[0]?.id||'');setBillingCycle((j.pendingSubscription?.billing_cycle||j.subscription?.billing_cycle)==='yearly'?'yearly':'monthly')}catch(e){const code=e instanceof Error?e.message:'SERVICE_UNAVAILABLE';setLoadError(code==='FORBIDDEN'?'ليس لديك صلاحية لعرض اشتراك هذا المطعم.':code==='TENANT_NOT_FOUND'?'لم يتم العثور على المطعم المرتبط بهذا الرابط.':'تعذر تحميل بيانات الاشتراك. تحقق من الاتصال ثم أعد المحاولة.')}finally{setLoading(false)}},[tenantId]);
 useEffect(()=>{void load()},[load]);
 const s=data?.subscription,p=data?.payments?.find(x=>x.status==='pending')||data?.payments?.[0],pendingSub=data?.pendingSubscription,plans=data?.plans||[],selected=plans.find(x=>x.id===planId);
 const planName=(x:Plan)=>locale==='ar'?x.name_ar:locale==='fr'?x.name_en:x.name_en;
 const planPrice=(x:Plan)=>{const amount=billingCycle==='yearly'?Number(x.yearly_price||0):Number(x.monthly_price);return billingCycle==='yearly'&&amount<=0?'السعر السنوي غير محدد':amount===0?'مجانية':amount.toFixed(2)+' '+x.currency+(billingCycle==='yearly'?' / سنة':' / شهر')};
 async function selectPlan(){if(!selected||busy)return;setBusy(true);setMsg('');try{const r=await fetch('/api/subscription',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'select_plan',tenantId,planId:selected.id,billingCycle})}),j=await r.json();if(!r.ok)throw new Error(j.error||'SERVICE_UNAVAILABLE');setMsg(j.status==='active'?'تم تفعيل الباقة المجانية.': 'تم اختيار الباقة. أكمل بيانات التحويل لإرسالها للمراجعة.');await load()}catch(e){const code=e instanceof Error?e.message:'';setMsg(code==='PLAN_ALREADY_ACTIVE'?'هذه الباقة مفعّلة بالفعل.':code==='PAYMENT_REVIEW_PENDING'?'يوجد تحويل قيد المراجعة. انتظر نتيجته قبل تغيير الباقة.':code==='PLAN_UNAVAILABLE'?'الباقة غير متاحة حاليًا.':'تعذر اختيار الباقة. أعد المحاولة.')}finally{setBusy(false)}}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/subscription',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'submit_transfer',tenantId,transactionReference:ref,receiptUrl:receipt})});const j=await r.json();if(!r.ok)throw new Error(j.error||'SERVICE_UNAVAILABLE');setMsg('تم إرسال بيانات التحويل للمراجعة.');setRef('');setReceipt('');await load()}catch(e){const code=e instanceof Error?e.message:'';setMsg(code==='NO_PENDING_SUBSCRIPTION'?'اختر باقة مدفوعة أولًا، ثم أرسل مرجع التحويل.':'تعذر إرسال البيانات. تحقق منها وحاول مرة أخرى.')}finally{setBusy(false)}}
 return <main className="subscription-shell" dir="rtl"><section className="subscription-card"><span className="subscription-icon"><WalletCards/></span><p className="command-kicker">FOON / SUBSCRIPTION</p><h1>تفعيل باقة المطعم</h1>
 {loading?<p role="status">جارٍ تحميل الاشتراك…</p>:loadError?<div className="subscription-error" role="alert"><p>{loadError}</p><button type="button" className="quiet-button" onClick={()=>void load()}><RefreshCw size={16}/> إعادة المحاولة</button></div>:!s?<div className="subscription-error"><p>لا توجد بيانات اشتراك مرتبطة بهذا المطعم.</p><button type="button" className="quiet-button" onClick={()=>void load()}><RefreshCw size={16}/> إعادة المحاولة</button></div>:<><div className="subscription-summary"><div><small>الباقة الحالية</small><strong>{s.name_ar}</strong></div><div><small>{s.billing_cycle==='yearly'?'المبلغ السنوي':'المبلغ الشهري'}</small><strong>{Number(s.billing_cycle==='yearly'?s.yearly_price:s.monthly_price).toFixed(2)} {s.currency}</strong></div><div><small>الحالة</small><strong>{s.status==='active'?'مفعلة':'بانتظار السداد'}</strong></div></div>
 <section className="subscription-plans"><h2>تغيير الباقة أو تجديدها</h2><p>تظل باقتك المفعّلة الحالية كما هي حتى اعتماد التحويل للباقة الجديدة.</p><div className="form-pair"><label>دورة الفوترة<select value={billingCycle} onChange={e=>setBillingCycle(e.target.value as 'monthly'|'yearly')}><option value="monthly">شهري</option><option value="yearly">سنوي</option></select></label></div><div className="signup-plan-grid">{plans.map(x=><button type="button" key={x.id} disabled={billingCycle==='yearly'&&Number(x.yearly_price||0)<=0} className={'signup-plan '+(planId===x.id?'active':'')} onClick={()=>setPlanId(x.id)}><strong>{planName(x)}</strong><b>{planPrice(x)}</b><span>{locale==='ar'?x.description_ar:x.description_en}</span></button>)}</div><button type="button" className="primary-button" disabled={busy||!selected||(billingCycle==='yearly'&&Number(selected.yearly_price||0)<=0)||(s.status==='active'&&s.plan_id===selected.id&&s.billing_cycle===billingCycle)||(s.status==='pending'&&s.plan_id===selected.id&&s.billing_cycle===billingCycle)} onClick={()=>void selectPlan()}>{busy?'جارٍ الحفظ…':'اختيار هذه الباقة'}</button></section>
 {p?.status==='pending'?<div className="subscription-pending"><Clock3/><div><strong>التحويل تحت المراجعة</strong><p>رقم العملية: {p.transaction_reference}</p></div></div>:pendingSub&&selected&&pendingSub.plan_id===selected.id&&pendingSub.billing_cycle===billingCycle?<form onSubmit={submit} className="subscription-form"><div className="bank-transfer-note"><ShieldCheck/><div><strong>تحويل بنكي · {planName(selected)}</strong><p>{planPrice(selected)}</p><p>حوّل قيمة الباقة المختارة إلى حساب المنصة، ثم أدخل رقم العملية. يمكن إضافة رابط إيصال التحويل إن كان متاحًا.</p></div></div><label>رقم العملية / مرجع التحويل<input required minLength={3} maxLength={160} value={ref} onChange={e=>setRef(e.target.value)}/></label><label>رابط الإيصال (اختياري)<input dir="ltr" type="url" value={receipt} onChange={e=>setReceipt(e.target.value)}/></label><button className="primary-button" disabled={busy}>{busy?'جارٍ الإرسال…':'إرسال للمراجعة'}</button></form>:s.status==='active'?<><div className="subscription-success"><CheckCircle2/><div><strong>الباقة مفعلة</strong><p>يمكنك الآن الانتقال إلى لوحة المطعم.</p></div></div>{data?.features?.length?<div className="records-card"><strong>مميزات الباقة المفعلة</strong>{data.features.map(f=><div className="plan-feature-row" key={f.feature_id}><span>{locale==='ar'?f.label_ar:f.label_en}</span><small>{f.feature_limit==null?'بدون حد':'الحد: '+f.feature_limit}</small></div>)}</div>:null}</>:<div className="subscription-pending"><Clock3/><div><strong>اختر الباقة أولًا</strong><p>اضغط «اختيار هذه الباقة» ليتم إنشاء طلب الدفع للباقة المحددة.</p></div></div>}
 <p role="status">{msg}</p><Link className="quiet-button" href={'/store?tenant='+tenantId}>العودة إلى لوحة المطعم</Link></>}
 </section></main>
}