'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import { useSearchParams } from 'next/navigation';
import { Moon,Sun,Store,UtensilsCrossed,ShoppingBag,CalendarDays,PackageCheck,Layers3,ShieldCheck,Globe2,ArrowUpLeft,Sparkles,Radio,Menu,UserRound,Mail,X } from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import { Select, SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { usePreferences } from './preferences';
import { activities } from '@/lib/platform/activities';
import type { Locale } from '@/lib/platform/contracts';
const icons={food:UtensilsCrossed,retail:ShoppingBag,appointments:CalendarDays,services:PackageCheck};
export default function Surface({page='home',content}:{page?:'home'|'activities'|'admin'|'contact';content?:React.ReactNode}){
 const [siteName,setSiteName]=useState('FOON');const [publicSettings,setPublicSettings]=useState<Record<string,string>>({});const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{let alive=true;fetch('/api/public/config',{cache:'no-store'}).then(r=>r.json()).then((d:unknown)=>{const data=d as {settings?:Record<string,string>};if(!alive)return;setPublicSettings(data.settings??{});if(data.settings?.site_name)setSiteName(data.settings.site_name)}).catch(()=>{});return()=>{alive=false}},[]);
 const {locale,dark,setLocale,toggleTheme,t}=usePreferences();const siteUrl=publicSettings.site_url||'https://fooncard.com';const customPages=(()=>{try{return JSON.parse(publicSettings.custom_pages_json||'[]') as {slug:string;titleAr?:string;titleEn?:string;titleFr?:string}[]}catch{return []}})();const params=useSearchParams();const selected=activities.find(a=>a.id===params.get('sector'));
 return <><header className="legacy-public-header production-public-header"><div className="production-public-header-inner"><Link href="/" className="production-public-brand" aria-label="FOON"><span className="brand-mark"><UtensilsCrossed size={20}/></span><span><strong>{siteName}</strong><small>BUSINESS OPERATING PLATFORM</small></span></Link><nav className={menuOpen?'open':''} aria-label={t.home}><Link href="/" onClick={()=>setMenuOpen(false)}>{t.home}</Link><Link href="/activities" onClick={()=>setMenuOpen(false)}>{t.activities}</Link><Link href="/register/store" onClick={()=>setMenuOpen(false)}>{locale==='ar'?'سجل نشاطك':locale==='fr'?'Inscrire votre activité':'Register business'}</Link><Link href="/login" onClick={()=>setMenuOpen(false)}>{locale==='ar'?'تسجيل الدخول':locale==='fr'?'Connexion':'Sign in'}</Link><Select value={locale} onValueChange={v=>setLocale(v as Locale)} dir={locale==='ar'?'rtl':'ltr'}><SelectTrigger aria-label={t.language}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ar">العربية</SelectItem><SelectItem value="en">English</SelectItem><SelectItem value="fr">Français</SelectItem></SelectContent></Select><button className="icon-button" onClick={toggleTheme} aria-label={t.theme}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button></nav><button className="production-public-menu-toggle" aria-label="Menu" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button></div></header> <main className={page==='admin'?"container admin-container":"container"}>
 {page==='home'&&<><section className="hero"><div className="hero-copy"><p className="eyebrow"><span/>{t.eyebrow}</p><h1>{t.headline.split('\n')[0]}<br/><span>{t.headline.split('\n')[1]}</span></h1><p className="intro">{t.intro}</p><div className="hero-actions"><Link className="primary-button" href="/activities">{t.explore}<ArrowUpLeft size={17}/></Link><Link className="hero-ghost" href="/register/store"><span className="live-ring"/>{locale==='ar'?'كن شريكًا':locale==='fr'?'Devenir partenaire':'Become a partner'}</Link></div><div className="trust-rail"><span><ShieldCheck size={14}/>{t.core}</span><i/><span><Radio size={14}/> FOON OS</span><i/><span><Globe2 size={14}/> AR · EN · FR</span></div></div><div className="sector-board premium-board"><div className="board-top"><Layers3 size={26}/><span>{t.sectorTitle}</span><span className="board-index"><Sparkles size={14}/> FOON LIVE</span></div>{(['food','retail','appointments','services'] as const).map((key,i)=>{const Icon=icons[key];return <Link data-engine={key} key={key} href={'/activities?sector='+({food:'restaurants',retail:'clothing',appointments:'beauty',services:'laundry'}[key])} className="board-row"><span className={'board-icon tone-'+i}><Icon size={26}/></span><div><h2>{t[key]}</h2><p>{t[(key+'Desc') as keyof typeof t]}</p></div><span className="row-number">0{i+1}</span></Link>})}<div className="board-bottom"><span>{siteName} / {t.activities}</span><Globe2 size={18}/></div></div></section>
 <section className="sector-section legacy-store-section"><div className="section-heading"><div><p className="eyebrow"><Layers3 size={17}/>{t.activities}</p><h2>{t.sectorTitle}</h2><p>{t.sectorIntro}</p></div><Link className="text-link" href="/activities">{t.all}</Link></div><div className="activity-grid legacy-store-grid">{activities.slice(0,6).map(a=>{const Icon=icons[a.engine];return <Link className="activity-card legacy-store-card" data-engine={a.engine} key={a.id} href={'/activities?sector='+a.id}><Icon size={28}/><h3>{a.name[locale]}</h3><span>{t[a.engine]}</span></Link>})}</div></section>
 <section className="foundation-strip"><ShieldCheck size={36}/><div><h2>{t.core}</h2><p>{t.coreIntro}</p></div></section></>}
 {page==='activities'&&<><section className="page-heading"><p className="eyebrow"><Layers3 size={17}/>{siteName} / {t.activities}</p><h1>{selected?selected.name[locale]:t.directory}</h1><p>{t.directoryIntro}</p></section>{!selected?<><div className="activity-grid directory">{activities.map(a=>{const Icon=icons[a.engine];return <Link className="activity-card" data-engine={a.engine} key={a.id} href={'/activities?sector='+a.id}><Icon size={28}/><h2>{a.name[locale]}</h2><span>{t[a.engine]}</span></Link>})}</div><p className="directory-note"><b>{activities.length}</b> {t.sectorCount}</p></>:<><Link href="/activities" className="text-link">{t.back}</Link><div className="empty-panel"><Empty><EmptyHeader><EmptyMedia variant="icon"><Store/></EmptyMedia><EmptyTitle>{t.empty}</EmptyTitle><EmptyDescription>{t.emptyDesc}</EmptyDescription></EmptyHeader></Empty></div></>}</>}
 {page==='contact'&&<section className="contact-page"><div className="page-heading"><p className="eyebrow"><Mail size={17}/>{siteName}</p><h1>{locale==='ar'?'اتصل بنا':locale==='fr'?'Nous contacter':'Contact us'}</h1><p>{locale==='ar'?'تواصل مع إدارة المنصة عبر القنوات الرسمية المسجلة.':locale==='fr'?'Contactez la plateforme via ses canaux officiels enregistrés.':'Reach the platform through its registered official channels.'}</p></div><div className="contact-grid">{publicSettings.support_email&&<a className="contact-card" href={'mailto:'+publicSettings.support_email}><Mail/><strong>{locale==='ar'?'البريد الإلكتروني':'Email'}</strong><span dir="ltr">{publicSettings.support_email}</span></a>}{publicSettings.instagram_url&&<a className="contact-card" href={publicSettings.instagram_url} target="_blank" rel="noopener noreferrer"><Globe2/><strong>Instagram</strong></a>}{publicSettings.facebook_url&&<a className="contact-card" href={publicSettings.facebook_url} target="_blank" rel="noopener noreferrer"><Globe2/><strong>Facebook</strong></a>}{publicSettings.linkedin_url&&<a className="contact-card" href={publicSettings.linkedin_url} target="_blank" rel="noopener noreferrer"><Globe2/><strong>LinkedIn</strong></a>}{publicSettings.snapchat_url&&<a className="contact-card" href={publicSettings.snapchat_url} target="_blank" rel="noopener noreferrer"><Globe2/><strong>Snapchat</strong></a>}{publicSettings.tiktok_url&&<a className="contact-card" href={publicSettings.tiktok_url} target="_blank" rel="noopener noreferrer"><Globe2/><strong>TikTok</strong></a>}{publicSettings.twitter_url&&<a className="contact-card" href={publicSettings.twitter_url} target="_blank" rel="noopener noreferrer"><Globe2/><strong>X / Twitter</strong></a>}{publicSettings.whatsapp_url&&<a className="contact-card" href={publicSettings.whatsapp_url} target="_blank" rel="noopener noreferrer"><Globe2/><strong>WhatsApp</strong></a>}</div></section>}
 {page==='admin'&&(content??<><section className="page-heading"><p className="eyebrow">FOON / {t.preview}</p><h1>{t.management}</h1><p>{t.adminIntro}</p></section><div className="preview-banner"><ShieldCheck size={22}/><div><strong>{t.preview}</strong><p>{t.previewDesc}</p></div></div><div className="admin-grid"><section className="empty-panel"><Empty><EmptyHeader><EmptyMedia variant="icon"><Layers3/></EmptyMedia><EmptyTitle>{t.notConnected}</EmptyTitle><EmptyDescription>{t.notConnectedDesc}</EmptyDescription></EmptyHeader></Empty></section><section className="admin-catalog"><h2>{t.overview}</h2><dl>{[t.activities,t.stores,t.accounts,t.subscriptions,t.payments,t.platformSettings].map((label,i)=><div key={label}><dt><span>0{i+1}</span>{label}</dt><dd>—</dd></div>)}</dl></section></div><p className="next-note">{t.next}</p></>)}
 </main><footer className="production-public-footer"><div className="production-footer-inner"><div className="production-footer-grid"><div className="production-footer-brand"><div className="production-footer-brandline"><span className="brand-mark"><UtensilsCrossed size={20}/></span><strong>{siteName}</strong></div><p>{t.footer.replace('FOON',siteName)}</p></div><div><h3>{locale==='ar'?'اكتشف':locale==='fr'?'Découvrir':'Discover'}</h3><div><Link href="/activities">{t.activities}</Link><Link href="/register/store">{locale==='ar'?'سجل نشاطك':locale==='fr'?'Inscrire votre activité':'Register business'}</Link><Link href="/login">{locale==='ar'?'تسجيل الدخول':locale==='fr'?'Connexion':'Sign in'}</Link></div></div><div><h3>{locale==='ar'?'الدعم':locale==='fr'?'Assistance':'Support'}</h3><div><Link href="/contact">{locale==='ar'?'اتصل بنا':locale==='fr'?'Contact':'Contact'}</Link>{publicSettings.support_email&&<a href={'mailto:'+publicSettings.support_email} dir="ltr">{publicSettings.support_email}</a>}{publicSettings.whatsapp_url&&<a href={publicSettings.whatsapp_url} target="_blank" rel="noopener noreferrer">WhatsApp</a>}</div></div><div><h3>{locale==='ar'?'الحقوق والسياسات':locale==='fr'?'Mentions légales':'Legal'}</h3><div><Link href="/p/terms">{locale==='ar'?'الشروط والأحكام':locale==='fr'?'Conditions':'Terms & Conditions'}</Link><Link href="/p/privacy">{locale==='ar'?'سياسة الخصوصية':locale==='fr'?'Confidentialité':'Privacy Policy'}</Link><Link href="/p/refund">{locale==='ar'?'سياسة الاسترجاع':locale==='fr'?'Remboursement':'Refund Policy'}</Link>{customPages.filter(p=>p.slug).map(p=><Link key={p.slug} href={'/p/'+p.slug}>{locale==='ar'?(p.titleAr||p.titleEn||p.slug):locale==='fr'?(p.titleFr||p.titleEn||p.slug):(p.titleEn||p.titleAr||p.slug)}</Link>)}</div></div></div><div className="production-footer-qr"><div><strong>{locale==='ar'?'QR الموقع':locale==='fr'?'QR du site':'Site QR'}</strong><span>{locale==='ar'?'امسح الرمز للدخول إلى موقع FOON':locale==='fr'?'Scannez pour ouvrir FOON':'Scan to open FOON'}</span></div><a href={siteUrl} aria-label="FOON QR"><QRCodeSVG value={siteUrl} size={92} level="H"/></a></div><div className="production-footer-bottom"><span>© {new Date().getFullYear()} {siteName}</span><span><Globe2 size={14}/> AR · EN · FR</span></div></div></footer></>;
}