'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import { useSearchParams } from 'next/navigation';
import { Moon,Sun,Store,UtensilsCrossed,ShoppingBag,CalendarDays,PackageCheck,Layers3,ShieldCheck,Globe2 } from 'lucide-react';
import { Select, SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { usePreferences } from './preferences';
import { activities } from '@/lib/platform/activities';
import type { Locale } from '@/lib/platform/contracts';
const icons={food:UtensilsCrossed,retail:ShoppingBag,appointments:CalendarDays,services:PackageCheck};
export default function Surface({page='home',content}:{page?:'home'|'activities'|'admin';content?:React.ReactNode}){
 const [siteName,setSiteName]=useState('FOON');useEffect(()=>{let alive=true;fetch('/api/public/config',{cache:'no-store'}).then(r=>r.json()).then((d:unknown)=>{const data=d as {settings?:{site_name?:string}};if(alive&&data.settings?.site_name)setSiteName(data.settings.site_name)}).catch(()=>{});return()=>{alive=false}},[]);
 const {locale,dark,setLocale,toggleTheme,t}=usePreferences();const params=useSearchParams();const selected=activities.find(a=>a.id===params.get('sector'));
 return <><header className={page==='admin'?"header admin-header":"header"}><div className="container header-inner"><Link href="/" className="brand" aria-label="FOON"><span className="brand-mark">f</span><span>{siteName}<span className="brand-dot">.</span></span></Link><nav aria-label={t.home}><Link href="/" aria-current={page==='home'?'page':undefined}>{t.home}</Link><Link href="/activities" aria-current={page==='activities'?'page':undefined}>{t.activities}</Link><Link href="/admin" aria-current={page==='admin'?'page':undefined}>{t.admin}</Link></nav><div className="preferences"><Select value={locale} onValueChange={v=>setLocale(v as Locale)} dir={locale==='ar'?'rtl':'ltr'}><SelectTrigger aria-label={t.language}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ar">العربية</SelectItem><SelectItem value="en">English</SelectItem><SelectItem value="fr">Français</SelectItem></SelectContent></Select><button className="icon-button" onClick={toggleTheme} aria-label={t.theme}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button></div></div></header>
 <main className={page==='admin'?"container admin-container":"container"}>
 {page==='home'&&<><section className="hero"><div className="hero-copy"><p className="eyebrow"><span/>{t.eyebrow}</p><h1>{t.headline.split('\n')[0]}<br/><span>{t.headline.split('\n')[1]}</span></h1><p className="intro">{t.intro}</p><Link className="primary-button" href="/activities">{t.explore}</Link></div><div className="sector-board premium-board"><div className="board-top"><Layers3 size={26}/><span>{t.sectorTitle}</span><span className="board-index"><Globe2 size={17}/></span></div>{(['food','retail','appointments','services'] as const).map((key,i)=>{const Icon=icons[key];return <Link data-engine={key} key={key} href={'/activities?sector='+({food:'restaurants',retail:'clothing',appointments:'beauty',services:'laundry'}[key])} className="board-row"><span className={'board-icon tone-'+i}><Icon size={26}/></span><div><h2>{t[key]}</h2><p>{t[(key+'Desc') as keyof typeof t]}</p></div><span className="row-number">0{i+1}</span></Link>})}<div className="board-bottom"><span>{siteName} / {t.activities}</span><Globe2 size={18}/></div></div></section>
 <section className="sector-section"><div className="section-heading"><div><p className="eyebrow"><Layers3 size={17}/>{t.activities}</p><h2>{t.sectorTitle}</h2><p>{t.sectorIntro}</p></div><Link className="text-link" href="/activities">{t.all}</Link></div><div className="activity-grid">{activities.slice(0,6).map(a=>{const Icon=icons[a.engine];return <Link className="activity-card" data-engine={a.engine} key={a.id} href={'/activities?sector='+a.id}><Icon size={28}/><h3>{a.name[locale]}</h3><span>{t[a.engine]}</span></Link>})}</div></section>
 <section className="foundation-strip"><ShieldCheck size={36}/><div><h2>{t.core}</h2><p>{t.coreIntro}</p></div></section></>}
 {page==='activities'&&<><section className="page-heading"><p className="eyebrow"><Layers3 size={17}/>{siteName} / {t.activities}</p><h1>{selected?selected.name[locale]:t.directory}</h1><p>{t.directoryIntro}</p></section>{!selected?<><div className="activity-grid directory">{activities.map(a=>{const Icon=icons[a.engine];return <Link className="activity-card" data-engine={a.engine} key={a.id} href={'/activities?sector='+a.id}><Icon size={28}/><h2>{a.name[locale]}</h2><span>{t[a.engine]}</span></Link>})}</div><p className="directory-note"><b>{activities.length}</b> {t.sectorCount}</p></>:<><Link href="/activities" className="text-link">{t.back}</Link><div className="empty-panel"><Empty><EmptyHeader><EmptyMedia variant="icon"><Store/></EmptyMedia><EmptyTitle>{t.empty}</EmptyTitle><EmptyDescription>{t.emptyDesc}</EmptyDescription></EmptyHeader></Empty></div></>}</>}
 {page==='admin'&&(content??<><section className="page-heading"><p className="eyebrow">FOON / {t.preview}</p><h1>{t.management}</h1><p>{t.adminIntro}</p></section><div className="preview-banner"><ShieldCheck size={22}/><div><strong>{t.preview}</strong><p>{t.previewDesc}</p></div></div><div className="admin-grid"><section className="empty-panel"><Empty><EmptyHeader><EmptyMedia variant="icon"><Layers3/></EmptyMedia><EmptyTitle>{t.notConnected}</EmptyTitle><EmptyDescription>{t.notConnectedDesc}</EmptyDescription></EmptyHeader></Empty></section><section className="admin-catalog"><h2>{t.overview}</h2><dl>{[t.activities,t.stores,t.accounts,t.subscriptions,t.payments,t.platformSettings].map((label,i)=><div key={label}><dt><span>0{i+1}</span>{label}</dt><dd>—</dd></div>)}</dl></section></div><p className="next-note">{t.next}</p></>)}
 </main><footer className="container footer"><span>{t.footer.replace('FOON',siteName)}</span><span>{t.foundation}</span></footer></>;
}
