import {z} from 'zod';
import {database} from '@/db';
import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
export const dynamic='force-dynamic';
const promotion=z.object({name:z.string().trim().min(2).max(180),discountType:z.enum(['percent','fixed']),discountValue:z.number().positive().max(100000),startsAt:z.number().int().nullable().optional(),endsAt:z.number().int().nullable().optional()});
const coupon=z.object({code:z.string().trim().min(3).max(80).transform(v=>v.toUpperCase()),discountType:z.enum(['percent','fixed']),discountValue:z.number().positive().max(100000),minOrder:z.number().min(0).max(1000000).default(0),usageLimit:z.number().int().positive().max(10000000).nullable().optional(),startsAt:z.number().int().nullable().optional(),endsAt:z.number().int().nullable().optional()});
function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT',issues:e.issues},{status:400});console.error('Restaurant promotions failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503})}
async function tenant(slug:string){const t=await database().prepare("SELECT id FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);return {...t,userId:u.userId}}
export async function GET(req:Request){try{const t=await tenant(new URL(req.url).searchParams.get('slug')||'');const [promotions,coupons]=await Promise.all([database().prepare('SELECT id,name,discount_type,discount_value,starts_at,ends_at,enabled,created_at FROM restaurant_promotions WHERE tenant_id=? ORDER BY created_at DESC').bind(t.id).all(),database().prepare('SELECT id,code,discount_type,discount_value,min_order,usage_limit,used_count,starts_at,ends_at,enabled,created_at FROM restaurant_coupons WHERE tenant_id=? ORDER BY created_at DESC').bind(t.id).all()]);return Response.json({promotions:promotions.results,coupons:coupons.results})}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>15000)throw new ApiError(413,'INPUT_TOO_LARGE');const data=JSON.parse(raw),t=await tenant(String(data.slug||'')),now=Date.now();if(data.action==='create_promotion'){const v=promotion.parse(data);if(v.startsAt&&v.endsAt&&v.endsAt<=v.startsAt)throw new ApiError(400,'INVALID_DATE_RANGE');const id=crypto.randomUUID();await database().prepare('INSERT INTO restaurant_promotions(id,tenant_id,name,discount_type,discount_value,starts_at,ends_at,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)').bind(id,t.id,v.name,v.discountType,v.discountValue,v.startsAt||null,v.endsAt||null,now,now).run();await audit(t.userId,'restaurant.promotion.created',t.id);return Response.json({id},{status:201})}if(data.action==='create_coupon'){const v=coupon.parse(data);if(v.discountType==='percent'&&v.discountValue>100)throw new ApiError(400,'INVALID_DISCOUNT');if(v.startsAt&&v.endsAt&&v.endsAt<=v.startsAt)throw new ApiError(400,'INVALID_DATE_RANGE');const id=crypto.randomUUID();try{await database().prepare('INSERT INTO restaurant_coupons(id,tenant_id,code,discount_type,discount_value,min_order,usage_limit,used_count,starts_at,ends_at,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,?,?,1,?,?)').bind(id,t.id,v.code,v.discountType,v.discountValue,v.minOrder,v.usageLimit??null,v.startsAt||null,v.endsAt||null,now,now).run()}catch(e){if(e instanceof Error&&/duplicate|unique/i.test(e.message))throw new ApiError(409,'COUPON_EXISTS');throw e}await audit(t.userId,'restaurant.coupon.created',t.id);return Response.json({id},{status:201})}if(data.action==='set_enabled'){const v=z.object({id:z.string().uuid(),kind:z.enum(['promotion','coupon']),enabled:z.boolean()}).parse(data),table=v.kind==='coupon'?'restaurant_coupons':'restaurant_promotions';const result=await database().prepare('UPDATE '+table+' SET enabled=?,updated_at=? WHERE id=? AND tenant_id=?').bind(v.enabled?1:0,now,v.id,t.id).run();if(!result.rowsAffected)throw new ApiError(404,'NOT_FOUND');await audit(t.userId,'restaurant.'+v.kind+'.updated',t.id);return Response.json({ok:true})}throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
