SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS restaurant_reservation_settings (tenant_id VARCHAR(36) NOT NULL,reservations_enabled TINYINT(1) NOT NULL DEFAULT 1,waitlist_enabled TINYINT(1) NOT NULL DEFAULT 1,advance_days INT NOT NULL DEFAULT 7,reservation_grace_minutes INT NOT NULL DEFAULT 15,waiting_grace_minutes INT NOT NULL DEFAULT 5,waitlist_expiry_minutes INT NOT NULL DEFAULT 120,min_party_size INT NOT NULL DEFAULT 1,max_party_size INT NOT NULL DEFAULT 20,updated_at BIGINT NOT NULL,PRIMARY KEY(tenant_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE restaurant_reservation_settings ADD COLUMN reservations_enabled TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE restaurant_reservation_settings ADD COLUMN waitlist_enabled TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE restaurant_reservation_settings ADD COLUMN advance_days INT NOT NULL DEFAULT 7;
ALTER TABLE restaurant_reservation_settings ADD COLUMN reservation_grace_minutes INT NOT NULL DEFAULT 15;
ALTER TABLE restaurant_reservation_settings ADD COLUMN waiting_grace_minutes INT NOT NULL DEFAULT 5;
ALTER TABLE restaurant_reservation_settings ADD COLUMN waitlist_expiry_minutes INT NOT NULL DEFAULT 120;
ALTER TABLE restaurant_reservation_settings ADD COLUMN min_party_size INT NOT NULL DEFAULT 1;
ALTER TABLE restaurant_reservation_settings ADD COLUMN max_party_size INT NOT NULL DEFAULT 20;
ALTER TABLE restaurant_reservations ADD COLUMN table_id VARCHAR(36) NULL;
ALTER TABLE restaurant_reservations ADD COLUMN guests INT NOT NULL DEFAULT 1;
ALTER TABLE restaurant_reservations ADD COLUMN reservation_at BIGINT NOT NULL DEFAULT 0;
ALTER TABLE restaurant_reservations ADD COLUMN notes VARCHAR(1000) NULL;
ALTER TABLE restaurant_reservations ADD COLUMN updated_at BIGINT NOT NULL DEFAULT 0;
ALTER TABLE restaurant_waitlist ADD COLUMN guests INT NOT NULL DEFAULT 1;
ALTER TABLE restaurant_waitlist ADD COLUMN assigned_table_id VARCHAR(36) NULL;
ALTER TABLE restaurant_waitlist ADD COLUMN expires_at BIGINT NULL;
ALTER TABLE restaurant_waitlist ADD COLUMN accepted_at BIGINT NULL;
ALTER TABLE restaurant_waitlist ADD COLUMN completed_at BIGINT NULL;
ALTER TABLE restaurant_waitlist ADD COLUMN cancelled_at BIGINT NULL;
ALTER TABLE restaurant_waitlist ADD COLUMN cancellation_reason VARCHAR(500) NULL;
ALTER TABLE restaurant_waitlist ADD COLUMN updated_at BIGINT NOT NULL DEFAULT 0;
ALTER TABLE restaurant_tables ADD COLUMN section_name VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE restaurant_tables ADD COLUMN capacity INT NOT NULL DEFAULT 2;
ALTER TABLE restaurant_tables ADD COLUMN enabled BIGINT NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS restaurant_table_runtime (tenant_id VARCHAR(36) NOT NULL,table_id VARCHAR(36) NOT NULL,qr_token VARCHAR(64) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'available',waiter_user_id VARCHAR(36) NULL,service_started_at BIGINT NULL,min_order DECIMAL(12,2) NULL,service_fee DECIMAL(12,2) NULL,service_fee_label_ar VARCHAR(160) NULL,service_fee_label_en VARCHAR(160) NULL,service_fee_label_fr VARCHAR(160) NULL,updated_at BIGINT NOT NULL,PRIMARY KEY(table_id),UNIQUE KEY restaurant_table_runtime_qr(qr_token),KEY restaurant_table_runtime_tenant_status(tenant_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE restaurant_table_runtime ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'available';
ALTER TABLE restaurant_table_runtime ADD COLUMN waiter_user_id VARCHAR(36) NULL;
ALTER TABLE restaurant_table_runtime ADD COLUMN service_started_at BIGINT NULL;
ALTER TABLE restaurant_table_runtime ADD COLUMN min_order DECIMAL(12,2) NULL;
ALTER TABLE restaurant_table_runtime ADD COLUMN service_fee DECIMAL(12,2) NULL;
ALTER TABLE restaurant_table_runtime ADD COLUMN service_fee_label_ar VARCHAR(160) NULL;
ALTER TABLE restaurant_table_runtime ADD COLUMN service_fee_label_en VARCHAR(160) NULL;
ALTER TABLE restaurant_table_runtime ADD COLUMN service_fee_label_fr VARCHAR(160) NULL;