import { apiErrorResponse } from '@/lib/platform/error-reporting';
import {z} from 'zod';
import {database} from '@/db';
import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
import {requireTenantFeature} from '@/lib/platform/entitlements';
import {sendAutomaticMessage} from '@/lib/platform/delivery';
export const dynamic='force-dynamic';
const status=z.enum(['pending','confirmed','seated','completed','cancelled','no_show']);
function fail(error: unknown) { return apiErrorResponse(error, '/app/api/restaurant/reservations'); }
async function tenant(slug:string){const t=await database().prepare("SELECT id,name FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string;name:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);await requireTenantFeature(t.id,'reservations');return {...t,userId:u.userId}}
export async function GET(req:Request){try{const u=new URL(req.url),t=await tenant(u.searchParams.get('slug')||''),filter=u.searchParams.get('status')||'',s=filter?status.parse(filter):null;const q=s?"SELECT r.id,r.reference,r.status,r.customer_name,r.customer_email,r.customer_phone,r.guests,r.reservation_at,r.notes,r.table_id,tb.table_number,tb.section_name FROM restaurant_reservations r LEFT JOIN restaurant_tables tb ON tb.id=r.table_id AND tb.tenant_id=r.tenant_id WHERE r.tenant_id=? AND r.status=? ORDER BY r.reservation_at ASC LIMIT 200":"SELECT r.id,r.reference,r.status,r.customer_name,r.customer_email,r.customer_phone,r.guests,r.reservation_at,r.notes,r.table_id,tb.table_number,tb.section_name FROM restaurant_reservations r LEFT JOIN restaurant_tables tb ON tb.id=r.table_id AND tb.tenant_id=r.tenant_id WHERE r.tenant_id=? ORDER BY r.reservation_at ASC LIMIT 200";const rows=s?await database().prepare(q).bind(t.id,s).all():await database().prepare(q).bind(t.id).all();return Response.json({reservations:rows.results})}catch(e){return fail(e)}}
export async function PATCH(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>10000)throw new ApiError(413,'INPUT_TOO_LARGE');const d=JSON.parse(raw),t=await tenant(String(d.slug||'')),id=z.string().uuid().parse(d.id),next=status.parse(d.status);const r=await database().prepare('SELECT id,status,reference,customer_name,customer_email,reservation_at FROM restaurant_reservations WHERE id=? AND tenant_id=? LIMIT 1').bind(id,t.id).first<{id:string;status:string;reference:string;customer_name:string|null;customer_email:string|null;reservation_at:number}>();if(!r)throw new ApiError(404,'RESERVATION_NOT_FOUND');if(r.status!==next){await database().prepare('UPDATE restaurant_reservations SET status=?,updated_at=? WHERE id=? AND tenant_id=?').bind(next,Date.now(),id,t.id).run();await audit(t.userId,`restaurant.reservation.status_changed:${r.status}->${next}`,t.id);
 const event=next==='confirmed'?'booking_confirmed':next==='cancelled'?'booking_cancelled':null;
 if(event&&r.customer_email)await sendAutomaticMessage({tenantId:t.id,event,locale:'ar',recipient:r.customer_email,variables:{customer_name:r.customer_name||'',store_name:t.name,service_name:'restaurant',service_number:r.reference,service_type:'reservation',amount:'0',currency:'SAR',date:new Date(r.reservation_at).toISOString(),plan_name:'',expires_at:''},idempotencyKey:id+':'+next});
 }return Response.json({ok:true,status:next})}catch(e){return fail(e)}}
