import {z} from 'zod';
import {database} from '@/db';
import {authorize,sameOrigin,ApiError,audit} from '@/lib/platform/security';
export const dynamic='force-dynamic';
const submit=z.object({tenantId:z.string().uuid(),transactionReference:z.string().trim().min(3).max(160),receiptUrl:z.union([z.string().url().max(1000),z.literal('')]).optional().default('')});
const review=z.object({tenantId:z.string().uuid(),paymentId:z.string().uuid(),decision:z.enum(['approved','rejected']),note:z.string().trim().max(1000).optional().default('')});
function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT'},{status:400});console.error('Subscription operation failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503})}
export async function GET(request:Request){try{const url=new URL(request.url),tenantId=url.searchParams.get('tenantId')??undefined;const action=url.searchParams.get('action')||'tenant';if(action==='pending'){const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const rows=await database().prepare("SELECT pr.id,pr.tenant_id,pr.amount,pr.currency,pr.transaction_reference,pr.receipt_url,pr.status,pr.submitted_at,t.name AS tenant_name,p.name_ar AS plan_name FROM payment_requests pr JOIN tenants t ON t.id=pr.tenant_id JOIN subscriptions s ON s.id=pr.subscription_id JOIN package_plans p ON p.id=s.plan_id WHERE pr.status='pending' ORDER BY pr.submitted_at ASC").all();return Response.json({payments:rows.results})}const u=await authorize(tenantId);if(!tenantId)throw new ApiError(400,'TENANT_REQUIRED');const subscription=await database().prepare('SELECT s.id,s.plan_id,s.status,s.starts_at,s.expires_at,p.name_ar,p.name_en,p.monthly_price,p.currency FROM subscriptions s JOIN package_plans p ON p.id=s.plan_id WHERE s.tenant_id=? ORDER BY s.created_at DESC LIMIT 1').bind(tenantId).first();const payments=await database().prepare('SELECT id,method,amount,currency,transaction_reference,receipt_url,status,submitted_at,reviewed_at,review_note FROM payment_requests WHERE tenant_id=? ORDER BY submitted_at DESC').bind(tenantId).all();return Response.json({subscription,payments:payments.results,admin:u.admin})}catch(e){return fail(e)}}
export async function POST(request:Request){try{sameOrigin(request);const raw=await request.text();if(raw.length>10000)throw new ApiError(413,'INPUT_TOO_LARGE');const data=JSON.parse(raw);if(data.action==='submit_transfer'){const v=submit.parse(data);const u=await authorize(v.tenantId);const s=await database().prepare("SELECT s.id,p.monthly_price,p.currency FROM subscriptions s JOIN package_plans p ON p.id=s.plan_id WHERE s.tenant_id=? AND s.status='pending' ORDER BY s.created_at DESC LIMIT 1").bind(v.tenantId).first<{id:string;monthly_price:number;currency:string}>();if(!s)throw new ApiError(409,'NO_PENDING_SUBSCRIPTION');const id=crypto.randomUUID();await database().prepare("INSERT INTO payment_requests(id,tenant_id,subscription_id,method,amount,currency,transaction_reference,receipt_url,status,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,v.tenantId,s.id,'bank_transfer',s.monthly_price,s.currency,v.transactionReference,v.receiptUrl||null,'pending',Date.now()).run();await audit(u.userId,'subscription.payment_submitted',v.tenantId);return Response.json({id,status:'pending'},{status:201})}
 if(data.action==='review_transfer'){const v=review.parse(data);const u=await authorize();if(!u.admin)throw new ApiError(403,'FORBIDDEN');const p=await database().prepare("SELECT subscription_id FROM payment_requests WHERE id=? AND tenant_id=? AND status='pending'").bind(v.paymentId,v.tenantId).first<{subscription_id:string}>();if(!p)throw new ApiError(404,'PAYMENT_NOT_FOUND');const now=Date.now();const status=v.decision;const statements=[database().prepare('UPDATE payment_requests SET status=?,reviewed_at=?,reviewed_by=?,review_note=? WHERE id=?').bind(status,now,u.userId,v.note||null,v.paymentId)];if(status==='approved'){statements.push(database().prepare("UPDATE subscriptions SET status='active',starts_at=?,expires_at=?,updated_at=? WHERE id=?").bind(now,now+30*86400000,now,p.subscription_id));statements.push(database().prepare("UPDATE tenants SET status='active' WHERE id=?").bind(v.tenantId))}await database().batch(statements);await audit(u.userId,'subscription.payment_'+status,v.tenantId);return Response.json({status})}
 throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
