import { apiErrorResponse } from '@/lib/platform/error-reporting';
import {z} from 'zod';import {database} from '@/db';import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
export const dynamic='force-dynamic';
const roles=z.enum(['manager','cashier','waiter','kitchen','driver','accountant']);
const staff=z.object({name:z.string().trim().min(1).max(180),email:z.union([z.string().email(),z.literal('')]).default(''),phone:z.string().trim().max(40).default(''),role:roles,branchId:z.string().uuid().nullable().optional()});
const permissions=z.array(z.string().trim().min(1).max(100)).max(100);
function fail(error: unknown) { return apiErrorResponse(error, '/app/api/restaurant/staff'); }
async function tenant(slug:string){const t=await database().prepare("SELECT id FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);return {...t,userId:u.userId}}
export async function GET(req:Request){try{const t=await tenant(new URL(req.url).searchParams.get('slug')||'');const [staff,permissions,attendance]=await Promise.all([database().prepare('SELECT id,user_id,branch_id,name,email,phone,role,status,created_at FROM staff_profiles WHERE tenant_id=? ORDER BY created_at DESC').bind(t.id).all(),database().prepare('SELECT role,permission_key,enabled FROM role_permissions WHERE tenant_id=? ORDER BY role,permission_key').bind(t.id).all(),database().prepare('SELECT a.id,a.staff_id,a.branch_id,a.clock_in,a.clock_out,a.note,s.name FROM staff_attendance a JOIN staff_profiles s ON s.id=a.staff_id AND s.tenant_id=a.tenant_id WHERE a.tenant_id=? ORDER BY a.clock_in DESC LIMIT 100').bind(t.id).all()]);return Response.json({staff:staff.results,permissions:permissions.results,attendance:attendance.results})}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>30000)throw new ApiError(413,'INPUT_TOO_LARGE');const data=JSON.parse(raw),t=await tenant(String(data.slug||'')),action=String(data.action||''),now=Date.now();
 if(action==='create_staff'){const v=staff.parse(data);if(v.branchId&&!await database().prepare('SELECT id FROM branches WHERE id=? AND tenant_id=?').bind(v.branchId,t.id).first())throw new ApiError(400,'INVALID_BRANCH');if(v.email&&await database().prepare('SELECT id FROM staff_profiles WHERE tenant_id=? AND email=?').bind(t.id,v.email).first())throw new ApiError(409,'STAFF_EXISTS');const id=crypto.randomUUID();await database().prepare('INSERT INTO staff_profiles(id,tenant_id,user_id,branch_id,name,email,phone,role,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,t.id,null,v.branchId||null,v.name,v.email||null,v.phone||null,v.role,'active',now,now).run();await audit(t.userId,'restaurant.staff.created:'+v.role,t.id);return Response.json({id},{status:201})}
 if(action==='set_permissions'){const role=roles.parse(data.role),keys=permissions.parse(data.permissions);const allowed=new Set(['orders.view','orders.manage','pos.use','kds.use','menu.manage','inventory.view','inventory.manage','purchases.manage','reservations.manage','tables.manage','customers.view','reports.view','finance.view','staff.manage','settings.manage','printers.manage']);if(keys.some((x:string)=>!allowed.has(x)))throw new ApiError(400,'INVALID_PERMISSION');const current=(await database().prepare('SELECT permission_key FROM role_permissions WHERE tenant_id=? AND role=?').bind(t.id,role).all<{permission_key:string}>()).results;const stmts=current.map(x=>database().prepare('DELETE FROM role_permissions WHERE tenant_id=? AND role=? AND permission_key=?').bind(t.id,role,x.permission_key));for(const key of keys)stmts.push(database().prepare('INSERT INTO role_permissions(tenant_id,role,permission_key,enabled) VALUES(?,?,?,1)').bind(t.id,role,key));if(stmts.length)await database().batch(stmts);await audit(t.userId,'restaurant.staff.permissions_updated:'+role,t.id);return Response.json({ok:true})}
 if(action==='clock_in'){const staffId=z.string().uuid().parse(data.staffId),s=await database().prepare("SELECT id,branch_id FROM staff_profiles WHERE id=? AND tenant_id=? AND status='active'").bind(staffId,t.id).first<{id:string;branch_id:string|null}>();if(!s)throw new ApiError(404,'STAFF_NOT_FOUND');const open=await database().prepare('SELECT id FROM staff_attendance WHERE tenant_id=? AND staff_id=? AND clock_out IS NULL LIMIT 1').bind(t.id,staffId).first();if(open)throw new ApiError(409,'ALREADY_CLOCKED_IN');const id=crypto.randomUUID();await database().prepare('INSERT INTO staff_attendance(id,tenant_id,staff_id,branch_id,clock_in,clock_out,note) VALUES(?,?,?,?,?,NULL,NULL)').bind(id,t.id,staffId,s.branch_id,now).run();await audit(t.userId,'restaurant.staff.clock_in',t.id);return Response.json({id})}
 if(action==='clock_out'){const staffId=z.string().uuid().parse(data.staffId),open=await database().prepare('SELECT id FROM staff_attendance WHERE tenant_id=? AND staff_id=? AND clock_out IS NULL ORDER BY clock_in DESC LIMIT 1').bind(t.id,staffId).first<{id:string}>();if(!open)throw new ApiError(409,'NOT_CLOCKED_IN');await database().prepare('UPDATE staff_attendance SET clock_out=? WHERE id=? AND tenant_id=?').bind(now,open.id,t.id).run();await audit(t.userId,'restaurant.staff.clock_out',t.id);return Response.json({ok:true})}
 throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
