import {z} from 'zod';
import {database} from '@/db';
import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
import {requireTenantFeature} from '@/lib/platform/entitlements';
export const dynamic='force-dynamic';
const next=z.enum(['confirmed','preparing','ready']);
function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT',issues:e.issues},{status:400});console.error('Restaurant KDS failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503})}
async function tenant(slug:string){const t=await database().prepare("SELECT id FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);try{await requireTenantFeature(t.id,'kds')}catch{await requireTenantFeature(t.id,'orders')}return {...t,userId:u.userId}}
export async function GET(req:Request){try{
 const u=new URL(req.url),t=await tenant(u.searchParams.get('slug')||''),station=(u.searchParams.get('station')||'').trim();
 const orders=await database().prepare("SELECT id,reference,source,status,customer_name,created_at,updated_at FROM restaurant_orders WHERE tenant_id=? AND status IN ('confirmed','preparing','ready') ORDER BY CASE status WHEN 'preparing' THEN 1 WHEN 'confirmed' THEN 2 ELSE 3 END,created_at ASC LIMIT 200").bind(t.id).all();
 const ids=(orders.results as any[]).map(x=>x.id);let items:any[]=[];
 if(ids.length){const marks=ids.map(()=>'?').join(','),stationClause=station?" AND COALESCE(r.station_key,'kitchen')=?":'';const sql=`SELECT oi.id,oi.order_id,oi.item_name,oi.quantity,COALESCE(r.station_key,'kitchen') station_key FROM restaurant_order_items oi JOIN restaurant_orders o ON o.id=oi.order_id LEFT JOIN menu_item_station_routes r ON r.tenant_id=o.tenant_id AND r.menu_item_id=oi.menu_item_id WHERE o.tenant_id=? AND oi.order_id IN (${marks})${stationClause} ORDER BY oi.order_id`;items=(await database().prepare(sql).bind(t.id,...ids,...(station?[station]:[])).all()).results as any[]}
 const visible=new Set(items.map(x=>x.order_id));const stations=await database().prepare('SELECT station_key,name FROM restaurant_kds_stations WHERE tenant_id=? AND enabled=1 ORDER BY name').bind(t.id).all();
 return Response.json({orders:(orders.results as any[]).filter(x=>visible.has(x.id)),items,stations:stations.results,station})
}catch(e){return fail(e)}}
export async function PATCH(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>5000)throw new ApiError(413,'INPUT_TOO_LARGE');const d=JSON.parse(raw),t=await tenant(String(d.slug||'')),id=z.string().uuid().parse(d.id),status=next.parse(d.status);const o=await database().prepare("SELECT id,status FROM restaurant_orders WHERE id=? AND tenant_id=? AND status IN ('confirmed','preparing','ready') LIMIT 1").bind(id,t.id).first<{id:string;status:string}>();if(!o)throw new ApiError(404,'ORDER_NOT_FOUND');const allowed=(o.status==='confirmed'&&status==='preparing')||(o.status==='preparing'&&status==='ready')||o.status===status;if(!allowed)throw new ApiError(409,'INVALID_STATUS_TRANSITION');if(o.status!==status){await database().prepare('UPDATE restaurant_orders SET status=?,updated_at=? WHERE id=? AND tenant_id=?').bind(status,Date.now(),id,t.id).run();await audit(t.userId,`restaurant.kds.status_changed:${o.status}->${status}`,t.id)}return Response.json({ok:true,status})}catch(e){return fail(e)}}