import {z} from 'zod';
import {database} from '@/db';
import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
import {requireTenantFeature} from '@/lib/platform/entitlements';
export const dynamic='force-dynamic';
const category=z.object({nameAr:z.string().trim().min(1).max(160),nameEn:z.string().trim().max(160).default(''),nameFr:z.string().trim().max(160).default(''),sortOrder:z.number().int().min(0).max(100000).default(0),enabled:z.boolean().default(true)});
const item=z.object({categoryId:z.string().uuid(),nameAr:z.string().trim().min(1).max(180),nameEn:z.string().trim().max(180).default(''),nameFr:z.string().trim().max(180).default(''),descriptionAr:z.string().max(4000).default(''),descriptionEn:z.string().max(4000).default(''),descriptionFr:z.string().max(4000).default(''),price:z.number().min(0).max(999999999),imageUrl:z.union([z.string().url().max(1000),z.literal('')]).default(''),calories:z.number().int().min(0).max(100000).nullable().default(null),enabled:z.boolean().default(true)});
function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT',issues:e.issues},{status:400});console.error('Restaurant menu failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503})}
async function tenant(slug:string){const t=await database().prepare("SELECT id FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');await authorize(t.id);await requireTenantFeature(t.id,'menu');return t.id}
export async function GET(req:Request){try{const slug=new URL(req.url).searchParams.get('slug')||'';const tenantId=await tenant(slug);const [categories,items]=await Promise.all([database().prepare('SELECT id,name_ar,name_en,name_fr,sort_order,enabled FROM menu_categories WHERE tenant_id=? ORDER BY sort_order,name_ar').bind(tenantId).all(),database().prepare('SELECT id,category_id,name_ar,name_en,name_fr,description_ar,description_en,description_fr,price,image_url,calories,enabled FROM menu_items WHERE tenant_id=? ORDER BY created_at DESC').bind(tenantId).all()]);return Response.json({categories:categories.results,items:items.results})}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>20000)throw new ApiError(413,'INPUT_TOO_LARGE');const data=JSON.parse(raw),tenantId=await tenant(String(data.slug||'')),u=await authorize(tenantId);if(data.action==='create_category'){const v=category.parse(data);const id=crypto.randomUUID();await database().prepare('INSERT INTO menu_categories(id,tenant_id,name_ar,name_en,name_fr,sort_order,enabled,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,tenantId,v.nameAr,v.nameEn,v.nameFr,v.sortOrder,v.enabled?1:0,Date.now()).run();await audit(u.userId,'restaurant.menu.category_created',tenantId);return Response.json({id},{status:201})}if(data.action==='create_item'){const v=item.parse(data);const cat=await database().prepare('SELECT id FROM menu_categories WHERE id=? AND tenant_id=?').bind(v.categoryId,tenantId).first();if(!cat)throw new ApiError(400,'INVALID_CATEGORY');const id=crypto.randomUUID(),now=Date.now();await database().prepare('INSERT INTO menu_items(id,tenant_id,category_id,name_ar,name_en,name_fr,description_ar,description_en,description_fr,price,image_url,calories,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,tenantId,v.categoryId,v.nameAr,v.nameEn,v.nameFr,v.descriptionAr||null,v.descriptionEn||null,v.descriptionFr||null,v.price,v.imageUrl||null,v.calories,v.enabled?1:0,now,now).run();await audit(u.userId,'restaurant.menu.item_created',tenantId);return Response.json({id},{status:201})}throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
export async function PATCH(req:Request){try{sameOrigin(req);const data=JSON.parse(await req.text()),tenantId=await tenant(String(data.slug||'')),u=await authorize(tenantId);if(data.action==='toggle_category'){const id=z.string().uuid().parse(data.id),enabled=z.boolean().parse(data.enabled);await database().prepare('UPDATE menu_categories SET enabled=? WHERE id=? AND tenant_id=?').bind(enabled?1:0,id,tenantId).run();await audit(u.userId,'restaurant.menu.category_toggled',tenantId);return Response.json({ok:true})}if(data.action==='toggle_item'){const id=z.string().uuid().parse(data.id),enabled=z.boolean().parse(data.enabled);await database().prepare('UPDATE menu_items SET enabled=?,updated_at=? WHERE id=? AND tenant_id=?').bind(enabled?1:0,Date.now(),id,tenantId).run();await audit(u.userId,'restaurant.menu.item_toggled',tenantId);return Response.json({ok:true})}throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
export async function DELETE(req:Request){try{sameOrigin(req);const data=JSON.parse(await req.text()),tenantId=await tenant(String(data.slug||'')),u=await authorize(tenantId),id=z.string().uuid().parse(data.id);if(data.kind==='item'){await database().prepare('DELETE FROM menu_items WHERE id=? AND tenant_id=?').bind(id,tenantId).run();await audit(u.userId,'restaurant.menu.item_deleted',tenantId);return Response.json({ok:true})}if(data.kind==='category'){const count=await database().prepare('SELECT COUNT(*) total FROM menu_items WHERE category_id=? AND tenant_id=?').bind(id,tenantId).first<{total:number|string}>();if(Number(count?.total||0)>0)throw new ApiError(409,'CATEGORY_NOT_EMPTY');await database().prepare('DELETE FROM menu_categories WHERE id=? AND tenant_id=?').bind(id,tenantId).run();await audit(u.userId,'restaurant.menu.category_deleted',tenantId);return Response.json({ok:true})}throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
