import { apiErrorResponse } from '@/lib/platform/error-reporting';
import {z} from 'zod';import {database} from '@/db';import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
export const dynamic='force-dynamic';const types=['pickup','takeaway','dine_in','delivery','room_service','reservation'] as const;
function fail(error: unknown) { return apiErrorResponse(error, '/app/api/restaurant/order-policies'); }
async function tenant(slug:string){const t=await database().prepare("SELECT id FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);return {...t,userId:u.userId}}
export async function POST(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>12000)throw new ApiError(413,'INPUT_TOO_LARGE');const d=JSON.parse(raw),t=await tenant(String(d.slug||'')),action=String(d.action||''),now=Date.now();
if(action==='policy'){const type=z.enum(types).parse(d.orderType),min=z.coerce.number().min(0).max(9999999).parse(d.minOrder||0),fee=z.coerce.number().min(0).max(9999999).parse(d.serviceFee||0),max=d.maxActiveOrders===''||d.maxActiveOrders==null?null:z.coerce.number().int().min(1).max(100000).parse(d.maxActiveOrders),requires=type==='delivery'&&Boolean(d.requiresDriver),ar=z.string().trim().max(160).optional().parse(d.labelAr)||'',en=z.string().trim().max(160).optional().parse(d.labelEn)||'',fr=z.string().trim().max(160).optional().parse(d.labelFr)||'';await database().prepare('INSERT INTO restaurant_order_policies(tenant_id,order_type,min_order,service_fee,service_fee_label_ar,service_fee_label_en,service_fee_label_fr,max_active_orders,requires_driver,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE min_order=VALUES(min_order),service_fee=VALUES(service_fee),service_fee_label_ar=VALUES(service_fee_label_ar),service_fee_label_en=VALUES(service_fee_label_en),service_fee_label_fr=VALUES(service_fee_label_fr),max_active_orders=VALUES(max_active_orders),requires_driver=VALUES(requires_driver),updated_at=VALUES(updated_at)').bind(t.id,type,min.toFixed(2),fee.toFixed(2),ar||null,en||null,fr||null,max,requires?1:0,now).run();await audit(t.userId,'restaurant.order_policy.updated:'+type,t.id);return Response.json({ok:true})}
if(action==='drivers'){const count=z.coerce.number().int().min(0).max(10000).parse(d.availableDrivers);await database().prepare('INSERT INTO restaurant_delivery_capacity(tenant_id,available_drivers,updated_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE available_drivers=VALUES(available_drivers),updated_at=VALUES(updated_at)').bind(t.id,count,now).run();await audit(t.userId,'restaurant.delivery_capacity.updated',t.id);return Response.json({ok:true})}
if(action==='hours'){const day=z.coerce.number().int().min(0).max(6).parse(d.day),closed=Boolean(d.closed),time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),open=closed?null:time.parse(d.openTime),close=closed?null:time.parse(d.closeTime);await database().prepare('INSERT INTO restaurant_business_hours(tenant_id,day_of_week,open_time,close_time,closed,updated_at) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE open_time=VALUES(open_time),close_time=VALUES(close_time),closed=VALUES(closed),updated_at=VALUES(updated_at)').bind(t.id,day,open,close,closed?1:0,now).run();await audit(t.userId,'restaurant.hours.updated:'+day,t.id);return Response.json({ok:true})}
throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
