import { apiErrorResponse } from '@/lib/platform/error-reporting';
import {z} from 'zod';import {database} from '@/db';import {ApiError,audit,authorize,sameOrigin} from '@/lib/platform/security';
export const dynamic='force-dynamic';
const key=z.string().trim().regex(/^[a-z0-9_-]{2,60}$/);
function fail(error: unknown) { return apiErrorResponse(error, '/app/api/restaurant/operations-settings'); }
async function tenant(slug:string){const t=await database().prepare("SELECT id FROM tenants WHERE slug=? AND activity_id='restaurants' LIMIT 1").bind(slug).first<{id:string}>();if(!t)throw new ApiError(404,'NOT_FOUND');const u=await authorize(t.id);return {...t,userId:u.userId}}
export async function GET(req:Request){try{const t=await tenant(new URL(req.url).searchParams.get('slug')||'');const [stations,printers,routes,items]=await Promise.all([database().prepare('SELECT id,branch_id,name,station_key,enabled FROM restaurant_kds_stations WHERE tenant_id=? ORDER BY name').bind(t.id).all(),database().prepare('SELECT id,branch_id,name,station,connection_type,connection_value,enabled FROM restaurant_printers WHERE tenant_id=? ORDER BY name').bind(t.id).all(),database().prepare('SELECT printer_id,route_type,route_value FROM printer_routes WHERE tenant_id=?').bind(t.id).all(),database().prepare("SELECT mi.id,mi.name_ar,mi.name_en,mi.name_fr,COALESCE(msr.station_key,'kitchen') station_key FROM menu_items mi LEFT JOIN menu_item_station_routes msr ON msr.tenant_id=mi.tenant_id AND msr.menu_item_id=mi.id WHERE mi.tenant_id=? AND mi.enabled=1 ORDER BY mi.name_ar LIMIT 500").bind(t.id).all()]);return Response.json({stations:stations.results,printers:printers.results,routes:routes.results,items:items.results})}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>20000)throw new ApiError(413,'INPUT_TOO_LARGE');const d=JSON.parse(raw),t=await tenant(String(d.slug||'')),now=Date.now(),action=String(d.action||'');
if(action==='create_station'){const name=z.string().trim().min(1).max(120).parse(d.name),stationKey=key.parse(d.stationKey),branchId=z.string().uuid().nullable().optional().parse(d.branchId);if(branchId&&!await database().prepare('SELECT id FROM branches WHERE id=? AND tenant_id=?').bind(branchId,t.id).first())throw new ApiError(400,'INVALID_BRANCH');const id=crypto.randomUUID();await database().prepare('INSERT INTO restaurant_kds_stations(id,tenant_id,branch_id,name,station_key,enabled,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)').bind(id,t.id,branchId||null,name,stationKey,now,now).run();await audit(t.userId,'restaurant.kds.station_created',t.id);return Response.json({id},{status:201})}
if(action==='create_printer'){const name=z.string().trim().min(1).max(120).parse(d.name),station=key.parse(d.station||'kitchen'),connectionType=z.enum(['network','usb','bluetooth','system']).parse(d.connectionType||'network'),connectionValue=z.string().trim().max(500).optional().parse(d.connectionValue)||'',branchId=z.string().uuid().nullable().optional().parse(d.branchId);if(branchId&&!await database().prepare('SELECT id FROM branches WHERE id=? AND tenant_id=?').bind(branchId,t.id).first())throw new ApiError(400,'INVALID_BRANCH');const id=crypto.randomUUID();await database().prepare('INSERT INTO restaurant_printers(id,tenant_id,branch_id,name,station,connection_type,connection_value,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)').bind(id,t.id,branchId||null,name,station,connectionType,connectionValue||null,now,now).run();await database().prepare("INSERT INTO printer_routes(tenant_id,printer_id,route_type,route_value) VALUES(?,?,'station',?)").bind(t.id,id,station).run();await audit(t.userId,'restaurant.printer.created',t.id);return Response.json({id},{status:201})}
if(action==='route_item'){const itemId=z.string().uuid().parse(d.itemId),stationKey=key.parse(d.stationKey);if(!await database().prepare('SELECT id FROM menu_items WHERE id=? AND tenant_id=?').bind(itemId,t.id).first())throw new ApiError(404,'ITEM_NOT_FOUND');if(stationKey!=='kitchen'&&!await database().prepare('SELECT id FROM restaurant_kds_stations WHERE tenant_id=? AND station_key=? AND enabled=1').bind(t.id,stationKey).first())throw new ApiError(400,'INVALID_STATION');await database().prepare('INSERT INTO menu_item_station_routes(tenant_id,menu_item_id,station_key) VALUES(?,?,?) ON DUPLICATE KEY UPDATE station_key=VALUES(station_key)').bind(t.id,itemId,stationKey).run();await audit(t.userId,'restaurant.kds.item_routed',t.id);return Response.json({ok:true})}
throw new ApiError(400,'INVALID_ACTION')}catch(e){return fail(e)}}
