import {z} from 'zod';
import {database} from '@/db';
import {ApiError,sameOrigin} from '@/lib/platform/security';
import {requireTenantFeature} from '@/lib/platform/entitlements';
import {priceMenuSelection} from '@/lib/restaurant/menu-pricing';

export const dynamic='force-dynamic';
const inputSchema=z.object({slug:z.string().regex(/^[a-z0-9][a-z0-9-]{1,59}$/),clientRequestId:z.string().uuid(),customerName:z.string().trim().min(2).max(160),customerPhone:z.string().trim().min(5).max(32),customerEmail:z.union([z.string().trim().email().max(254),z.literal('')]).optional().default(''),orderType:z.enum(['pickup','dine_in','room_service']),serviceReference:z.string().trim().max(80).optional().default(''),notes:z.string().trim().max(1000).optional().default(''),locale:z.enum(['ar','en','fr']).default('ar'),items:z.array(z.object({id:z.string().uuid(),quantity:z.number().int().min(1).max(99),variantId:z.string().uuid().optional(),options:z.array(z.object({id:z.string().uuid(),quantity:z.number().int().min(1).max(99)})).max(100).default([])})).min(1).max(50)});
function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'INVALID_INPUT'},{status:400});console.error('Public order failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'SERVICE_UNAVAILABLE'},{status:503});}
export async function POST(req:Request){try{
 sameOrigin(req);const raw=await req.text();if(raw.length>12000)throw new ApiError(413,'INPUT_TOO_LARGE');let untrusted:unknown;try{untrusted=JSON.parse(raw)}catch{throw new ApiError(400,'INVALID_INPUT')}const v=inputSchema.parse(untrusted);
 const tenant=await database().prepare("SELECT id,currency FROM tenants WHERE slug=? AND activity_id='restaurants' AND status='active' LIMIT 1").bind(v.slug).first<{id:string;currency:string}>();if(!tenant)throw new ApiError(404,'NOT_FOUND');await requireTenantFeature(tenant.id,'orders');await requireTenantFeature(tenant.id,v.orderType);
 if(v.orderType!=='pickup'&&!v.serviceReference)throw new ApiError(400,'SERVICE_REFERENCE_REQUIRED');
 const clientRequestId=`menu-${v.clientRequestId}`;const existing=await database().prepare('SELECT id,reference,status,total,currency FROM restaurant_orders WHERE tenant_id=? AND client_request_id=? LIMIT 1').bind(tenant.id,clientRequestId).first<Record<string,unknown>>();if(existing)return Response.json({order:existing,duplicate:true});
 const lines=await Promise.all(v.items.map(async line=>({...line,...await priceMenuSelection(tenant.id,line.id,{variantId:line.variantId,options:line.options,locale:v.locale})})));let totalCents=0;for(const line of lines)totalCents+=line.unitCents*line.quantity;if(!Number.isSafeInteger(totalCents)||totalCents<=0)throw new ApiError(400,'INVALID_TOTAL');
 const branch=await database().prepare('SELECT id FROM branches WHERE tenant_id=? ORDER BY is_primary DESC,id ASC LIMIT 1').bind(tenant.id).first<{id:string}>();if(!branch)throw new ApiError(409,'BRANCH_REQUIRED');const id=crypto.randomUUID(),reference=`FN-${Date.now().toString(36).toUpperCase()}-${id.slice(0,6).toUpperCase()}`,now=Date.now(),amount=(totalCents/100).toFixed(2);
 const statements=[database().prepare('INSERT INTO restaurant_orders(id,tenant_id,branch_id,reference,source,status,customer_name,customer_phone,subtotal,total,currency,client_request_id,order_type,service_reference,customer_email,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,tenant.id,branch.id,reference,'menu','new',v.customerName,v.customerPhone,(totalCents/100).toFixed(2),amount,tenant.currency,clientRequestId,v.orderType,v.serviceReference||null,v.customerEmail||null,v.notes||null,now,now)];
 for(const line of lines)statements.push(database().prepare('INSERT INTO restaurant_order_items(id,order_id,menu_item_id,item_name,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,line.id,line.itemName,line.quantity,(line.unitCents/100).toFixed(2),(line.unitCents*line.quantity/100).toFixed(2)));
 try{await database().batch(statements)}catch(error){if(error&&typeof error==='object'&&'code'in error&&error.code==='ER_DUP_ENTRY'){const raced=await database().prepare('SELECT id,reference,status,total,currency FROM restaurant_orders WHERE tenant_id=? AND client_request_id=? LIMIT 1').bind(tenant.id,clientRequestId).first<Record<string,unknown>>();if(raced)return Response.json({order:raced,duplicate:true})}throw error}
 return Response.json({order:{id,reference,status:'new',total:amount,currency:tenant.currency},duplicate:false},{status:201});
}catch(e){return fail(e)}}
